// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkCore/Havok/HkbTypes.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>
#include <cstring>

namespace Firelink::Havok
{

static hkbVariableBindingSetBinding Deser_Inline_hkbVariableBindingSetBinding(TagFileUnpacker& u, size_t base)
{
    hkbVariableBindingSetBinding r{};
    r.memberPath = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    r.variableIndex = u.ReadPodAt<int32_t>(base + 28);
    r.bitIndex = u.ReadPodAt<int8_t>(base + 32);
    r.bindingType = u.ReadPodAt<int8_t>(base + 33);
    return r;
}

std::shared_ptr<HkObject> Deser_hkbVariableBindingSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbVariableBindingSet>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->bindings.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->bindings[_i] = Deser_Inline_hkbVariableBindingSetBinding(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 40);
        }
    }
    r->indexOfBindingToEnable = u.ReadPodAt<int32_t>(base + 40);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBindable(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBindable>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbNode(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbNode>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));

    return r;
}

std::shared_ptr<HkObject> Deser_hkbGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));

    return r;
}

static hkbVariableBounds Deser_Inline_hkbVariableBounds(TagFileUnpacker& u, size_t base)
{
    hkbVariableBounds r{};
    r.min = u.ReadPodAt<hkbVariableValue>(base + 0);
    r.max = u.ReadPodAt<hkbVariableValue>(base + 4);
    return r;
}

std::shared_ptr<HkObject> Deser_hkbBehaviorGraphStringData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBehaviorGraphStringData>();
    const size_t base = item.absoluteDataOffset;

    r->eventNames = u.ReadPodArray<std::string>(base + 24);
    r->attributeNames = u.ReadPodArray<std::string>(base + 40);
    r->variableNames = u.ReadPodArray<std::string>(base + 56);
    r->characterPropertyNames = u.ReadPodArray<std::string>(base + 72);
    r->animationNames = u.ReadPodArray<std::string>(base + 88);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBehaviorGraphData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBehaviorGraphData>();
    const size_t base = item.absoluteDataOffset;

    r->attributeDefaults = u.ReadPodArray<float>(base + 24);
    r->variableInfos = u.ReadPodArray<hkbVariableInfo>(base + 40);
    r->characterPropertyInfos = u.ReadPodArray<hkbVariableInfo>(base + 56);
    r->eventInfos = u.ReadPodArray<hkbEventInfo>(base + 72);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 88));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->variableBounds.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->variableBounds[_i] = Deser_Inline_hkbVariableBounds(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
        }
    }
    // TODO: 'variableInitialValues' at +104 kind=unknown
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 112);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->stringData = std::static_pointer_cast<hkbBehaviorGraphStringData>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBehaviorGraph(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBehaviorGraph>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->variableMode = u.ReadPodAt<int8_t>(base + 152);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 200);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->rootGenerator = std::static_pointer_cast<hkbGenerator>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 208);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->data = std::static_pointer_cast<hkbBehaviorGraphData>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBlenderGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBlenderGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->referencePoseWeightThreshold = u.ReadPodAt<float>(base + 152);
    r->blendParameter = u.ReadPodAt<float>(base + 156);
    r->minCyclicBlendParameter = u.ReadPodAt<float>(base + 160);
    r->maxCyclicBlendParameter = u.ReadPodAt<float>(base + 164);
    r->indexOfSyncMasterChild = u.ReadPodAt<int16_t>(base + 168);
    r->flags = u.ReadPodAt<int16_t>(base + 170);
    r->subtractLastChild = u.ReadPodAt<bool>(base + 172);
    r->children = u.ReadPodArray<Ptr>(base + 176);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBoneWeightArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBoneWeightArray>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->boneWeights = u.ReadPodArray<float>(base + 56);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBlenderGeneratorChild(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBlenderGeneratorChild>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    // TODO: 'generator' at +64 kind=unknown
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 72);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->boneWeights = std::static_pointer_cast<hkbBoneWeightArray>(_obj);
    }
    r->weight = u.ReadPodAt<float>(base + 80);
    r->worldFromModelWeight = u.ReadPodAt<float>(base + 84);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbTransitionEffect(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbTransitionEffect>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->selfTransitionMode = u.ReadPodAt<int8_t>(base + 152);
    r->eventMode = u.ReadPodAt<int8_t>(base + 153);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBlendingTransitionEffect(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBlendingTransitionEffect>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->selfTransitionMode = u.ReadPodAt<int8_t>(base + 152);
    r->eventMode = u.ReadPodAt<int8_t>(base + 153);
    r->duration = u.ReadPodAt<float>(base + 184);
    r->toGeneratorStartTimeFraction = u.ReadPodAt<float>(base + 188);
    r->flags = u.ReadPodAt<uint16_t>(base + 192);
    r->endMode = u.ReadPodAt<int8_t>(base + 194);
    r->blendCurve = u.ReadPodAt<int8_t>(base + 195);
    r->alignmentBone = u.ReadPodAt<int16_t>(base + 196);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbBoneIndexArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbBoneIndexArray>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->boneIndices = u.ReadPodArray<int16_t>(base + 56);

    return r;
}

static hkbEventBase Deser_Inline_hkbEventBase(TagFileUnpacker& u, size_t base)
{
    hkbEventBase r{};
    r.id = u.ReadPodAt<int32_t>(base + 0);
    // TODO: 'payload' at +8 kind=unknown
    return r;
}

static hkbEventProperty Deser_Inline_hkbEventProperty(TagFileUnpacker& u, size_t base)
{
    hkbEventProperty r{};
    r.id = u.ReadPodAt<int32_t>(base + 0);
    // TODO: 'payload' at +8 kind=unknown
    return r;
}

static hkbClipTrigger Deser_Inline_hkbClipTrigger(TagFileUnpacker& u, size_t base)
{
    hkbClipTrigger r{};
    r.localTime = u.ReadPodAt<float>(base + 0);
    r.event = Deser_Inline_hkbEventProperty(u, base + 8);
    r.relativeToEndOfClip = u.ReadPodAt<bool>(base + 24);
    r.acyclic = u.ReadPodAt<bool>(base + 25);
    r.isAnnotation = u.ReadPodAt<bool>(base + 26);
    return r;
}

std::shared_ptr<HkObject> Deser_hkbClipTriggerArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbClipTriggerArray>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->triggers.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->triggers[_i] = Deser_Inline_hkbClipTrigger(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbClipGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbClipGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->animationName = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 152));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 160);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->triggers = std::static_pointer_cast<hkbClipTriggerArray>(_obj);
    }
    r->userPartitionMask = u.ReadPodAt<uint32_t>(base + 168);
    r->cropStartAmountLocalTime = u.ReadPodAt<float>(base + 172);
    r->cropEndAmountLocalTime = u.ReadPodAt<float>(base + 176);
    r->startTime = u.ReadPodAt<float>(base + 180);
    r->playbackSpeed = u.ReadPodAt<float>(base + 184);
    r->enforcedDuration = u.ReadPodAt<float>(base + 188);
    r->userControlledTimeFraction = u.ReadPodAt<float>(base + 192);
    r->mode = u.ReadPodAt<int8_t>(base + 196);
    r->flags = u.ReadPodAt<int8_t>(base + 197);
    r->animationInternalId = u.ReadPodAt<int16_t>(base + 198);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbCondition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbCondition>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hkbCustomIdSelector(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbCustomIdSelector>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

static hkbEvent Deser_Inline_hkbEvent(TagFileUnpacker& u, size_t base)
{
    hkbEvent r{};
    r.id = u.ReadPodAt<int32_t>(base + 0);
    // TODO: 'payload' at +8 kind=unknown
    return r;
}

std::shared_ptr<HkObject> Deser_hkbEventPayload(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbEventPayload>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hkbHoldFromBlendingTransitionEffect(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbHoldFromBlendingTransitionEffect>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->selfTransitionMode = u.ReadPodAt<int8_t>(base + 152);
    r->eventMode = u.ReadPodAt<int8_t>(base + 153);
    r->duration = u.ReadPodAt<float>(base + 184);
    r->toGeneratorStartTimeFraction = u.ReadPodAt<float>(base + 188);
    r->flags = u.ReadPodAt<uint16_t>(base + 192);
    r->endMode = u.ReadPodAt<int8_t>(base + 194);
    r->blendCurve = u.ReadPodAt<int8_t>(base + 195);
    r->alignmentBone = u.ReadPodAt<int16_t>(base + 196);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbModifier(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbModifier>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->enable = u.ReadPodAt<bool>(base + 96);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbKeyframeBonesModifier(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbKeyframeBonesModifier>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->enable = u.ReadPodAt<bool>(base + 96);
    r->keyframeInfo = u.ReadPodArray<hkbKeyframeBonesModifierKeyframeInfo>(base + 104);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 120);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->keyframedBonesList = std::static_pointer_cast<hkbBoneIndexArray>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbLayer(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbLayer>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 64);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->generator = std::static_pointer_cast<hkbGenerator>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 72);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->boneWeights = std::static_pointer_cast<hkbBoneWeightArray>(_obj);
    }
    r->useMotion = u.ReadPodAt<bool>(base + 80);
    r->blendingControlData = u.ReadPodAt<hkbEventDrivenBlendingObject>(base + 84);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbLayerGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbLayerGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->layers = u.ReadPodArray<Ptr>(base + 152);
    r->indexOfSyncMasterChild = u.ReadPodAt<int16_t>(base + 168);
    r->flags = u.ReadPodAt<uint16_t>(base + 170);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbManualSelectorGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbManualSelectorGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->generators = u.ReadPodArray<Ptr>(base + 152);
    r->selectedGeneratorIndex = u.ReadPodAt<int16_t>(base + 168);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 176);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->indexSelector = std::static_pointer_cast<hkbCustomIdSelector>(_obj);
    }
    r->selectedIndexCanChangeAfterActivate = u.ReadPodAt<bool>(base + 184);
    // TODO: 'generatorChangedTransitionEffect' at +192 kind=unknown
    r->sentOnClipEnd = Deser_Inline_hkbEventProperty(u, base + 200);
    r->generatorPreDeleteIndex = u.ReadPodArray<int16_t>(base + 216);
    r->endOfClipEventId = u.ReadPodAt<int32_t>(base + 256);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbModifierGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbModifierGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 152);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->modifier = std::static_pointer_cast<hkbModifier>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 160);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->generator = std::static_pointer_cast<hkbGenerator>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbModifierList(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbModifierList>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->enable = u.ReadPodAt<bool>(base + 96);
    r->modifiers = u.ReadPodArray<Ptr>(base + 104);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbProjectStringData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbProjectStringData>();
    const size_t base = item.absoluteDataOffset;

    r->behaviorFilenames = u.ReadPodArray<std::string>(base + 24);
    r->characterFilenames = u.ReadPodArray<std::string>(base + 40);
    r->eventNames = u.ReadPodArray<std::string>(base + 56);
    r->animationPath = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->behaviorPath = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 80));
    r->characterPath = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 88));
    r->scriptsPath = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 96));
    r->fullPathToSource = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 104));

    return r;
}

std::shared_ptr<HkObject> Deser_hkbProjectData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbProjectData>();
    const size_t base = item.absoluteDataOffset;

    r->worldUpWS = u.ReadPodAt<hkVector4>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 48);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->stringData = std::static_pointer_cast<hkbProjectStringData>(_obj);
    }
    r->defaultEventMode = u.ReadPodAt<int8_t>(base + 56);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbReferencePoseGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbReferencePoseGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));

    return r;
}

std::shared_ptr<HkObject> Deser_hkbScriptGenerator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbScriptGenerator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 152);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->child = std::static_pointer_cast<hkbGenerator>(_obj);
    }
    r->onActivateScript = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 160));
    r->onPreUpdateScript = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 168));
    r->onGenerateScript = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 176));
    r->onHandleEventScript = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 184));
    r->onDeactivateScript = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 192));

    return r;
}

std::shared_ptr<HkObject> Deser_hkbStateListener(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbStateListener>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hkbStateMachine(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbStateMachine>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->userData = u.ReadPodAt<uint64_t>(base + 64);
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 72));
    r->eventToSendWhenStateOrTransitionChanges = Deser_Inline_hkbEvent(u, base + 152);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 176);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->startStateIdSelector = std::static_pointer_cast<hkbCustomIdSelector>(_obj);
    }
    r->startStateId = u.ReadPodAt<int32_t>(base + 184);
    r->returnToPreviousStateEventId = u.ReadPodAt<int32_t>(base + 188);
    r->randomTransitionEventId = u.ReadPodAt<int32_t>(base + 192);
    r->transitionToNextHigherStateEventId = u.ReadPodAt<int32_t>(base + 196);
    r->transitionToNextLowerStateEventId = u.ReadPodAt<int32_t>(base + 200);
    r->syncVariableIndex = u.ReadPodAt<int32_t>(base + 204);
    r->wrapAroundStateId = u.ReadPodAt<bool>(base + 212);
    r->maxSimultaneousTransitions = u.ReadPodAt<int8_t>(base + 213);
    r->startStateMode = u.ReadPodAt<int8_t>(base + 214);
    r->selfTransitionMode = u.ReadPodAt<int8_t>(base + 215);
    r->states = u.ReadPodArray<Ptr>(base + 224);
    // TODO: 'wildcardTransitions' at +240 kind=unknown

    return r;
}

std::shared_ptr<HkObject> Deser_hkbStateMachineEventPropertyArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbStateMachineEventPropertyArray>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->events.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->events[_i] = Deser_Inline_hkbEventProperty(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }

    return r;
}

static hkbStateMachineTransitionInfo Deser_Inline_hkbStateMachineTransitionInfo(TagFileUnpacker& u, size_t base)
{
    hkbStateMachineTransitionInfo r{};
    r.triggerInterval = u.ReadPodAt<hkbStateMachineTimeInterval>(base + 0);
    r.initiateInterval = u.ReadPodAt<hkbStateMachineTimeInterval>(base + 16);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 32);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.transition = std::static_pointer_cast<hkbTransitionEffect>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.condition = std::static_pointer_cast<hkbCondition>(_obj);
    }
    r.eventId = u.ReadPodAt<int32_t>(base + 48);
    r.toStateId = u.ReadPodAt<int32_t>(base + 52);
    r.fromNestedStateId = u.ReadPodAt<int32_t>(base + 56);
    r.toNestedStateId = u.ReadPodAt<int32_t>(base + 60);
    r.priority = u.ReadPodAt<int16_t>(base + 64);
    r.flags = u.ReadPodAt<int16_t>(base + 66);
    return r;
}

std::shared_ptr<HkObject> Deser_hkbStateMachineTransitionInfoArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbStateMachineTransitionInfoArray>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->transitions.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->transitions[_i] = Deser_Inline_hkbStateMachineTransitionInfo(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 72);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkbStateMachineStateInfo(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbStateMachineStateInfo>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->variableBindingSet = std::static_pointer_cast<hkbVariableBindingSet>(_obj);
    }
    r->listeners = u.ReadPodArray<Ptr>(base + 56);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 72);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->enterNotifyEvents = std::static_pointer_cast<hkbStateMachineEventPropertyArray>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 80);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->exitNotifyEvents = std::static_pointer_cast<hkbStateMachineEventPropertyArray>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 88);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->transitions = std::static_pointer_cast<hkbStateMachineTransitionInfoArray>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 96);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->generator = std::static_pointer_cast<hkbGenerator>(_obj);
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 104));
    r->stateId = u.ReadPodAt<int32_t>(base + 112);
    r->probability = u.ReadPodAt<float>(base + 116);
    r->enable = u.ReadPodAt<bool>(base + 120);

    return r;
}

std::shared_ptr<HkObject> Deser_hkbVariableValueSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkbVariableValueSet>();
    const size_t base = item.absoluteDataOffset;

    r->wordVariableValues = u.ReadPodArray<hkbVariableValue>(base + 24);
    r->quadVariableValues = u.ReadPodArray<hkVector4>(base + 40);
    r->variantVariableValues = u.ReadPodArray<std::shared_ptr<hkReferencedObject>>(base + 56);

    return r;
}

void RegisterHkbDispatch(TagFileUnpacker& u)
{
    u.Register("hkbVariableBindingSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbVariableBindingSet(u_, i_);
    });
    u.Register("hkbBindable", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBindable(u_, i_);
    });
    u.Register("hkbNode", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbNode(u_, i_);
    });
    u.Register("hkbGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbGenerator(u_, i_);
    });
    u.Register("hkbBehaviorGraphStringData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBehaviorGraphStringData(u_, i_);
    });
    u.Register("hkbBehaviorGraphData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBehaviorGraphData(u_, i_);
    });
    u.Register("hkbBehaviorGraph", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBehaviorGraph(u_, i_);
    });
    u.Register("hkbBlenderGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBlenderGenerator(u_, i_);
    });
    u.Register("hkbBoneWeightArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBoneWeightArray(u_, i_);
    });
    u.Register("hkbBlenderGeneratorChild", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBlenderGeneratorChild(u_, i_);
    });
    u.Register("hkbTransitionEffect", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbTransitionEffect(u_, i_);
    });
    u.Register("hkbBlendingTransitionEffect", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBlendingTransitionEffect(u_, i_);
    });
    u.Register("hkbBoneIndexArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbBoneIndexArray(u_, i_);
    });
    u.Register("hkbClipTriggerArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbClipTriggerArray(u_, i_);
    });
    u.Register("hkbClipGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbClipGenerator(u_, i_);
    });
    u.Register("hkbCondition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbCondition(u_, i_);
    });
    u.Register("hkbCustomIdSelector", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbCustomIdSelector(u_, i_);
    });
    u.Register("hkbEventPayload", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbEventPayload(u_, i_);
    });
    u.Register("hkbHoldFromBlendingTransitionEffect", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbHoldFromBlendingTransitionEffect(u_, i_);
    });
    u.Register("hkbModifier", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbModifier(u_, i_);
    });
    u.Register("hkbKeyframeBonesModifier", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbKeyframeBonesModifier(u_, i_);
    });
    u.Register("hkbLayer", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbLayer(u_, i_);
    });
    u.Register("hkbLayerGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbLayerGenerator(u_, i_);
    });
    u.Register("hkbManualSelectorGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbManualSelectorGenerator(u_, i_);
    });
    u.Register("hkbModifierGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbModifierGenerator(u_, i_);
    });
    u.Register("hkbModifierList", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbModifierList(u_, i_);
    });
    u.Register("hkbProjectStringData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbProjectStringData(u_, i_);
    });
    u.Register("hkbProjectData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbProjectData(u_, i_);
    });
    u.Register("hkbReferencePoseGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbReferencePoseGenerator(u_, i_);
    });
    u.Register("hkbScriptGenerator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbScriptGenerator(u_, i_);
    });
    u.Register("hkbStateListener", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbStateListener(u_, i_);
    });
    u.Register("hkbStateMachine", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbStateMachine(u_, i_);
    });
    u.Register("hkbStateMachine::EventPropertyArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbStateMachineEventPropertyArray(u_, i_);
    });
    u.Register("hkbStateMachine::TransitionInfoArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbStateMachineTransitionInfoArray(u_, i_);
    });
    u.Register("hkbStateMachine::StateInfo", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbStateMachineStateInfo(u_, i_);
    });
    u.Register("hkbVariableValueSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkbVariableValueSet(u_, i_);
    });
}

}  // namespace Firelink::Havok