// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <../include/FirelinkERHavok/HknpTypes.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>
#include <cstring>

namespace Firelink::Havok
{

std::shared_ptr<HkObject> Deser_hknpShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpShape>();
    const size_t base = item.absoluteDataOffset;

    r->flags = u.ReadPodAt<uint16_t>(base + 20);
    r->type = u.ReadPodAt<uint8_t>(base + 22);
    r->numShapeKeyBits = u.ReadPodAt<uint8_t>(base + 23);
    r->dispatchType = u.ReadPodAt<uint8_t>(base + 24);
    r->convexRadius = u.ReadPodAt<float>(base + 28);
    r->userData = u.ReadPodAt<uint64_t>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->properties = std::static_pointer_cast<hkRefCountedProperties>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hknpRefMassDistribution(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpRefMassDistribution>();
    const size_t base = item.absoluteDataOffset;

    r->massDistribution = u.ReadPodAt<hknpMassDistribution>(base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpRefDragProperties(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpRefDragProperties>();
    const size_t base = item.absoluteDataOffset;

    r->dragProperties = u.ReadPodAt<hknpDragProperties>(base + 32);

    return r;
}

static hknpBodyCinfo Deser_Inline_hknpBodyCinfo(TagFileUnpacker& u, size_t base)
{
    hknpBodyCinfo r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.shape = std::static_pointer_cast<hknpShape>(_obj);
    }
    r.flags = u.ReadPodAt<int32_t>(base + 8);
    r.collisionCntrl = u.ReadPodAt<int16_t>(base + 12);
    r.collisionFilterInfo = u.ReadPodAt<uint32_t>(base + 16);
    r.materialId = u.ReadPodAt<uint16_t>(base + 20);
    r.qualityId = u.ReadPodAt<uint8_t>(base + 22);
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r.userData = u.ReadPodAt<uint64_t>(base + 32);
    r.motionType = u.ReadPodAt<uint8_t>(base + 40);
    r.position = u.ReadPodAt<hkVector4>(base + 48);
    r.orientation = u.ReadPodAt<hkQuaternion>(base + 64);
    r.linearVelocity = u.ReadPodAt<hkVector4>(base + 80);
    r.angularVelocity = u.ReadPodAt<hkVector4>(base + 96);
    r.mass = u.ReadPodAt<float>(base + 112);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 120);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.massDistribution = std::static_pointer_cast<hknpRefMassDistribution>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 128);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.dragProperties = std::static_pointer_cast<hknpRefDragProperties>(_obj);
    }
    r.motionPropertiesId = u.ReadPodAt<uint16_t>(base + 136);
    r.desiredBodyId = u.ReadPodAt<hknpBodyId>(base + 140);
    r.motionId = u.ReadPodAt<uint32_t>(base + 144);
    r.collisionLookAheadDistance = u.ReadPodAt<float>(base + 148);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 152);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.localFrame = std::static_pointer_cast<hkLocalFrame>(_obj);
    }
    r.activationPriority = u.ReadPodAt<int8_t>(base + 160);
    return r;
}

std::shared_ptr<HkObject> Deser_hknpBodyIntegrator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpBodyIntegrator>();
    const size_t base = item.absoluteDataOffset;

    r->bodyFlagsForcingNormalCollisions = u.ReadPodAt<uint32_t>(base + 20);
    r->typeForDynamicBodies = u.ReadPodAt<hk>(base + 24);
    r->typeForTriggers = u.ReadPodAt<hk>(base + 28);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpBodyQuality(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpBodyQuality>();
    const size_t base = item.absoluteDataOffset;

    r->priority = u.ReadPodAt<int32_t>(base + 20);
    r->supportedFlags = u.ReadPodAt<uint32_t>(base + 24);
    r->requestedFlags = u.ReadPodAt<uint32_t>(base + 28);
    r->contactCachingRelativeMovementThreshold = u.ReadPodAt<float>(base + 32);
    r->motionRangeBreachPolicy = u.ReadPodAt<hk>(base + 36);
    r->motionWeldBreachPolicy = u.ReadPodAt<hk>(base + 40);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpBodyQualityLibrary(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpBodyQualityLibrary>();
    const size_t base = item.absoluteDataOffset;

    r->qualities = u.ReadPodAt<std::array<hknpBodyQuality, 32>>(base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpBroadPhaseConfig(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpBroadPhaseConfig>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hknpConvexShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpConvexShape>();
    const size_t base = item.absoluteDataOffset;

    r->flags = u.ReadPodAt<uint16_t>(base + 20);
    r->type = u.ReadPodAt<uint8_t>(base + 22);
    r->numShapeKeyBits = u.ReadPodAt<uint8_t>(base + 23);
    r->dispatchType = u.ReadPodAt<uint8_t>(base + 24);
    r->convexRadius = u.ReadPodAt<float>(base + 28);
    r->userData = u.ReadPodAt<uint64_t>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->properties = std::static_pointer_cast<hkRefCountedProperties>(_obj);
    }
    r->maxAllowedPenetration = u.ReadPodAt<uint16_t>(base + 48);
    // relarray 'vertices' at +50: TODO

    return r;
}

std::shared_ptr<HkObject> Deser_hknpConvexPolytopeShapeConnectivity(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpConvexPolytopeShapeConnectivity>();
    const size_t base = item.absoluteDataOffset;

    r->vertexEdges = u.ReadPodArray<hknpConvexPolytopeShapeConnectivityEdge>(base + 24);
    r->faceLinks = u.ReadPodArray<hknpConvexPolytopeShapeConnectivityEdge>(base + 40);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpConvexPolytopeShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpConvexPolytopeShape>();
    const size_t base = item.absoluteDataOffset;

    r->flags = u.ReadPodAt<uint16_t>(base + 20);
    r->type = u.ReadPodAt<uint8_t>(base + 22);
    r->numShapeKeyBits = u.ReadPodAt<uint8_t>(base + 23);
    r->dispatchType = u.ReadPodAt<uint8_t>(base + 24);
    r->convexRadius = u.ReadPodAt<float>(base + 28);
    r->userData = u.ReadPodAt<uint64_t>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->properties = std::static_pointer_cast<hkRefCountedProperties>(_obj);
    }
    r->maxAllowedPenetration = u.ReadPodAt<uint16_t>(base + 48);
    // relarray 'vertices' at +50: TODO
    // relarray 'planes' at +54: TODO
    // relarray 'faces' at +58: TODO
    // relarray 'indices' at +62: TODO
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 72);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->connectivity = std::static_pointer_cast<hknpConvexPolytopeShapeConnectivity>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hknpCapsuleShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpCapsuleShape>();
    const size_t base = item.absoluteDataOffset;

    r->flags = u.ReadPodAt<uint16_t>(base + 20);
    r->type = u.ReadPodAt<uint8_t>(base + 22);
    r->numShapeKeyBits = u.ReadPodAt<uint8_t>(base + 23);
    r->dispatchType = u.ReadPodAt<uint8_t>(base + 24);
    r->convexRadius = u.ReadPodAt<float>(base + 28);
    r->userData = u.ReadPodAt<uint64_t>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->properties = std::static_pointer_cast<hkRefCountedProperties>(_obj);
    }
    r->maxAllowedPenetration = u.ReadPodAt<uint16_t>(base + 48);
    // relarray 'vertices' at +50: TODO
    // relarray 'planes' at +54: TODO
    // relarray 'faces' at +58: TODO
    // relarray 'indices' at +62: TODO
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 72);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->connectivity = std::static_pointer_cast<hknpConvexPolytopeShapeConnectivity>(_obj);
    }
    r->a = u.ReadPodAt<hkVector4>(base + 80);
    r->b = u.ReadPodAt<hkVector4>(base + 96);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpCollisionFilter(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpCollisionFilter>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<uint8_t>(base + 20);

    return r;
}

static hknpConstraintCinfo Deser_Inline_hknpConstraintCinfo(TagFileUnpacker& u, size_t base)
{
    hknpConstraintCinfo r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.constraintData = std::static_pointer_cast<hkpConstraintData>(_obj);
    }
    r.bodyA = u.ReadPodAt<hknpBodyId>(base + 8);
    r.bodyB = u.ReadPodAt<hknpBodyId>(base + 12);
    r.flags = u.ReadPodAt<uint16_t>(base + 16);
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r.desiredConstraintId = u.ReadPodAt<hknpConstraintId>(base + 32);
    r.constraintGroupId = u.ReadPodAt<hknpConstraintGroupId>(base + 36);
    return r;
}

std::shared_ptr<HkObject> Deser_hknpMaterial(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpMaterial>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 32));
    r->isExclusive = u.ReadPodAt<uint32_t>(base + 40);
    r->flags = u.ReadPodAt<int32_t>(base + 44);
    r->triggerType = u.ReadPodAt<uint8_t>(base + 48);
    r->triggerManifoldTolerance = u.ReadPodAt<hkUFloat8>(base + 49);
    r->dynamicFriction = u.ReadPodAt<uint16_t>(base + 50);
    r->staticFriction = u.ReadPodAt<uint16_t>(base + 52);
    r->restitution = u.ReadPodAt<uint16_t>(base + 54);
    r->frictionCombinePolicy = u.ReadPodAt<uint8_t>(base + 56);
    r->restitutionCombinePolicy = u.ReadPodAt<uint8_t>(base + 57);
    r->weldingTolerance = u.ReadPodAt<float>(base + 60);
    r->maxContactImpulse = u.ReadPodAt<float>(base + 64);
    r->fractionOfClippedImpulseToApply = u.ReadPodAt<float>(base + 68);
    r->massChangerCategory = u.ReadPodAt<uint8_t>(base + 72);
    r->massChangerHeavyObjectFactor = u.ReadPodAt<uint16_t>(base + 74);
    r->softContactForceFactor = u.ReadPodAt<uint16_t>(base + 76);
    r->softContactDampFactor = u.ReadPodAt<uint16_t>(base + 78);
    r->softContactSeparationVelocity = u.ReadPodAt<hkUFloat8>(base + 80);
    // TODO: 'surfaceVelocity' at +88 kind=unknown
    r->disablingCollisionsBetweenCvxCvxDynamicObjectsDistance = u.ReadPodAt<uint16_t>(base + 96);
    r->userData = u.ReadPodAt<uint64_t>(base + 104);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpMaterialLibrary(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpMaterialLibrary>();
    const size_t base = item.absoluteDataOffset;

    // TODO: 'entries' at +48 kind=unknown

    return r;
}

static hknpMotionProperties Deser_Inline_hknpMotionProperties(TagFileUnpacker& u, size_t base)
{
    hknpMotionProperties r{};
    r.isExclusive = u.ReadPodAt<uint32_t>(base + 0);
    r.flags = u.ReadPodAt<uint32_t>(base + 4);
    r.gravityFactor = u.ReadPodAt<float>(base + 8);
    r.timeFactor = u.ReadPodAt<float>(base + 12);
    r.maxLinearSpeed = u.ReadPodAt<float>(base + 16);
    r.maxAngularSpeed = u.ReadPodAt<float>(base + 20);
    r.linearDamping = u.ReadPodAt<float>(base + 24);
    r.angularDamping = u.ReadPodAt<float>(base + 28);
    r.solverStabilizationSpeedThreshold = u.ReadPodAt<float>(base + 32);
    r.solverStabilizationSpeedReduction = u.ReadPodAt<float>(base + 36);
    r.deactivationSettings = u.ReadPodAt<hknpMotionPropertiesDeactivationSettings>(base + 40);
    r.fullCastSettings = u.ReadPodAt<hknpMotionPropertiesFullCastSettings>(base + 64);
    return r;
}

std::shared_ptr<HkObject> Deser_hknpMotionPropertiesLibrary(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpMotionPropertiesLibrary>();
    const size_t base = item.absoluteDataOffset;

    // TODO: 'entries' at +48 kind=unknown

    return r;
}

std::shared_ptr<HkObject> Deser_hknpPhysicsSceneData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpPhysicsSceneData>();
    const size_t base = item.absoluteDataOffset;

    r->systemDatas = u.ReadPodArray<std::shared_ptr<hknpPhysicsSystemData>>(base + 24);
    // TODO: 'worldCinfo' at +40 kind=unknown

    return r;
}

static hknpPhysicsSystemDatabodyCinfoWithAttachment Deser_Inline_hknpPhysicsSystemDatabodyCinfoWithAttachment(TagFileUnpacker& u, size_t base)
{
    hknpPhysicsSystemDatabodyCinfoWithAttachment r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.shape = std::static_pointer_cast<hknpShape>(_obj);
    }
    r.flags = u.ReadPodAt<int32_t>(base + 8);
    r.collisionCntrl = u.ReadPodAt<int16_t>(base + 12);
    r.collisionFilterInfo = u.ReadPodAt<uint32_t>(base + 16);
    r.materialId = u.ReadPodAt<uint16_t>(base + 20);
    r.qualityId = u.ReadPodAt<uint8_t>(base + 22);
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r.userData = u.ReadPodAt<uint64_t>(base + 32);
    r.motionType = u.ReadPodAt<uint8_t>(base + 40);
    r.position = u.ReadPodAt<hkVector4>(base + 48);
    r.orientation = u.ReadPodAt<hkQuaternion>(base + 64);
    r.linearVelocity = u.ReadPodAt<hkVector4>(base + 80);
    r.angularVelocity = u.ReadPodAt<hkVector4>(base + 96);
    r.mass = u.ReadPodAt<float>(base + 112);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 120);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.massDistribution = std::static_pointer_cast<hknpRefMassDistribution>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 128);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.dragProperties = std::static_pointer_cast<hknpRefDragProperties>(_obj);
    }
    r.motionPropertiesId = u.ReadPodAt<uint16_t>(base + 136);
    r.desiredBodyId = u.ReadPodAt<hknpBodyId>(base + 140);
    r.motionId = u.ReadPodAt<uint32_t>(base + 144);
    r.collisionLookAheadDistance = u.ReadPodAt<float>(base + 148);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 152);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.localFrame = std::static_pointer_cast<hkLocalFrame>(_obj);
    }
    r.activationPriority = u.ReadPodAt<int8_t>(base + 160);
    r.attachedBody = u.ReadPodAt<int32_t>(base + 164);
    return r;
}

std::shared_ptr<HkObject> Deser_hknpPhysicsSystemData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpPhysicsSystemData>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->materials.emplace_back(std::static_pointer_cast<hknpMaterial>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 40));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->motionProperties.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->motionProperties[_i] = Deser_Inline_hknpMotionProperties(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 112);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->bodyCinfos.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->bodyCinfos[_i] = Deser_Inline_hknpPhysicsSystemDatabodyCinfoWithAttachment(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 176);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 72));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->constraintCinfos.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->constraintCinfos[_i] = Deser_Inline_hknpConstraintCinfo(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 40);
        }
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 88));
    r->microStepMultiplier = u.ReadPodAt<uint8_t>(base + 96);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpRagdollData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpRagdollData>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->materials.emplace_back(std::static_pointer_cast<hknpMaterial>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 40));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->motionProperties.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->motionProperties[_i] = Deser_Inline_hknpMotionProperties(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 112);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->bodyCinfos.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->bodyCinfos[_i] = Deser_Inline_hknpPhysicsSystemDatabodyCinfoWithAttachment(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 176);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 72));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->constraintCinfos.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->constraintCinfos[_i] = Deser_Inline_hknpConstraintCinfo(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 40);
        }
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 88));
    r->microStepMultiplier = u.ReadPodAt<uint8_t>(base + 96);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 104);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->skeleton = std::static_pointer_cast<hkaSkeleton>(_obj);
    }
    r->boneToBodyMap = u.ReadPodArray<int32_t>(base + 112);
    r->bodyTags = u.ReadPodArray<uint32_t>(base + 128);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpShapeTagCodec(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpShapeTagCodec>();
    const size_t base = item.absoluteDataOffset;

    r->hints = u.ReadPodAt<uint32_t>(base + 20);
    r->type = u.ReadPodAt<uint8_t>(base + 24);

    return r;
}

static hknpWorldCinfo Deser_Inline_hknpWorldCinfo(TagFileUnpacker& u, size_t base)
{
    hknpWorldCinfo r{};
    r.bodyBufferCapacity = u.ReadPodAt<int32_t>(base + 8);
    r.motionBufferCapacity = u.ReadPodAt<int32_t>(base + 24);
    r.constraintBufferCapacity = u.ReadPodAt<int32_t>(base + 40);
    r.constraintGroupBufferCapacity = u.ReadPodAt<int32_t>(base + 56);
    r.useBodyBacklinkBuffer = u.ReadPodAt<bool>(base + 72);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 80);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.materialLibrary = std::static_pointer_cast<hknpMaterialLibrary>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 88);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.motionPropertiesLibrary = std::static_pointer_cast<hknpMotionPropertiesLibrary>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 96);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.qualityLibrary = std::static_pointer_cast<hknpBodyQualityLibrary>(_obj);
    }
    r.simulationType = u.ReadPodAt<uint8_t>(base + 104);
    r.numSplitterCells = u.ReadPodAt<int32_t>(base + 108);
    r.gravity = u.ReadPodAt<hkVector4>(base + 112);
    r.airDensity = u.ReadPodAt<float>(base + 128);
    r.enableContactCaching = u.ReadPodAt<bool>(base + 132);
    r.mergeEventsBeforeDispatch = u.ReadPodAt<bool>(base + 133);
    r.broadPhaseType = u.ReadPodAt<uint8_t>(base + 134);
    r.broadPhaseAabb = u.ReadPodAt<hkAabb>(base + 144);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 176);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.broadPhaseConfig = std::static_pointer_cast<hknpBroadPhaseConfig>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 184);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.collisionFilter = std::static_pointer_cast<hknpCollisionFilter>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 192);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.shapeTagCodec = std::static_pointer_cast<hknpShapeTagCodec>(_obj);
    }
    r.collisionTolerance = u.ReadPodAt<float>(base + 200);
    r.relativeCollisionAccuracy = u.ReadPodAt<float>(base + 204);
    r.aabbMargin = u.ReadPodAt<float>(base + 208);
    r.enableWeldingForDefaultObjects = u.ReadPodAt<bool>(base + 212);
    r.enableWeldingForCriticalObjects = u.ReadPodAt<bool>(base + 213);
    r.weldingConfig = u.ReadPodAt<hknpWeldingConfig>(base + 216);
    r.lodManagerCinfo = u.ReadPodAt<hknpLodManagerCinfo>(base + 220);
    r.enableSdfEdgeCollisions = u.ReadPodAt<bool>(base + 244);
    r.enableCollideWorkStealing = u.ReadPodAt<bool>(base + 245);
    r.particlesLandscapeQuadCacheSize = u.ReadPodAt<int32_t>(base + 248);
    r.solverTau = u.ReadPodAt<float>(base + 252);
    r.solverDamp = u.ReadPodAt<float>(base + 256);
    r.solverIterations = u.ReadPodAt<int32_t>(base + 260);
    r.solverMicrosteps = u.ReadPodAt<int32_t>(base + 264);
    r.enableDeactivation = u.ReadPodAt<bool>(base + 268);
    r.enablePenetrationRecovery = u.ReadPodAt<bool>(base + 269);
    r.maxApproachSpeedForHighQualitySolver = u.ReadPodAt<float>(base + 272);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 280);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.bodyIntegrator = std::static_pointer_cast<hknpBodyIntegrator>(_obj);
    }
    r.adjustSolverSettingsBasedOnTimestep = u.ReadPodAt<bool>(base + 288);
    r.expectedDeltaTime = u.ReadPodAt<float>(base + 292);
    r.minSolverIterations = u.ReadPodAt<int32_t>(base + 296);
    r.maxSolverIterations = u.ReadPodAt<int32_t>(base + 300);
    return r;
}

std::shared_ptr<HkObject> Deser_hknpRefWorldCinfo(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpRefWorldCinfo>();
    const size_t base = item.absoluteDataOffset;

    r->info = Deser_Inline_hknpWorldCinfo(u, base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpShapeMassProperties(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpShapeMassProperties>();
    const size_t base = item.absoluteDataOffset;

    r->compressedMassProperties = u.ReadPodAt<hkCompressedMassProperties>(base + 24);

    return r;
}

std::shared_ptr<HkObject> Deser_hknpSurfaceVelocity(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hknpSurfaceVelocity>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

void RegisterHknpDispatch(TagFileUnpacker& u)
{
    u.Register("hknpShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpShape(u_, i_);
    });
    u.Register("hknpRefMassDistribution", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpRefMassDistribution(u_, i_);
    });
    u.Register("hknpRefDragProperties", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpRefDragProperties(u_, i_);
    });
    u.Register("hknpBodyIntegrator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpBodyIntegrator(u_, i_);
    });
    u.Register("hknpBodyQuality", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpBodyQuality(u_, i_);
    });
    u.Register("hknpBodyQualityLibrary", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpBodyQualityLibrary(u_, i_);
    });
    u.Register("hknpBroadPhaseConfig", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpBroadPhaseConfig(u_, i_);
    });
    u.Register("hknpConvexShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpConvexShape(u_, i_);
    });
    u.Register("hknpConvexPolytopeShape::Connectivity", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpConvexPolytopeShapeConnectivity(u_, i_);
    });
    u.Register("hknpConvexPolytopeShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpConvexPolytopeShape(u_, i_);
    });
    u.Register("hknpCapsuleShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpCapsuleShape(u_, i_);
    });
    u.Register("hknpCollisionFilter", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpCollisionFilter(u_, i_);
    });
    u.Register("hknpMaterial", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpMaterial(u_, i_);
    });
    u.Register("hknpMaterialLibrary", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpMaterialLibrary(u_, i_);
    });
    u.Register("hknpMotionPropertiesLibrary", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpMotionPropertiesLibrary(u_, i_);
    });
    u.Register("hknpPhysicsSceneData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpPhysicsSceneData(u_, i_);
    });
    u.Register("hknpPhysicsSystemData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpPhysicsSystemData(u_, i_);
    });
    u.Register("hknpRagdollData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpRagdollData(u_, i_);
    });
    u.Register("hknpShapeTagCodec", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpShapeTagCodec(u_, i_);
    });
    u.Register("hknpRefWorldCinfo", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpRefWorldCinfo(u_, i_);
    });
    u.Register("hknpShapeMassProperties", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpShapeMassProperties(u_, i_);
    });
    u.Register("hknpSurfaceVelocity", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hknpSurfaceVelocity(u_, i_);
    });
}

}  // namespace Firelink::Havok