// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkCore/Havok/HkxTypes.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>
#include <cstring>

namespace Firelink::Havok
{

static hkxAttribute Deser_Inline_hkxAttribute(TagFileUnpacker& u, size_t base)
{
    hkxAttribute r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 8);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.value = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    return r;
}

static hkxAttributeGroup Deser_Inline_hkxAttributeGroup(TagFileUnpacker& u, size_t base)
{
    hkxAttributeGroup r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 8));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.attributes.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.attributes[_i] = Deser_Inline_hkxAttribute(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    return r;
}

std::shared_ptr<HkObject> Deser_hkxAttributeHolder(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxAttributeHolder>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->attributeGroups.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->attributeGroups[_i] = Deser_Inline_hkxAttributeGroup(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkxIndexBuffer(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxIndexBuffer>();
    const size_t base = item.absoluteDataOffset;

    r->indexType = u.ReadPodAt<int8_t>(base + 24);
    r->indices16 = u.ReadPodArray<uint16_t>(base + 32);
    r->indices32 = u.ReadPodArray<uint32_t>(base + 48);
    r->vertexBaseOffset = u.ReadPodAt<uint32_t>(base + 64);
    r->length = u.ReadPodAt<uint32_t>(base + 68);

    return r;
}

static hkxMaterialTextureStage Deser_Inline_hkxMaterialTextureStage(TagFileUnpacker& u, size_t base)
{
    hkxMaterialTextureStage r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.texture = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    r.usageHint = u.ReadPodAt<int32_t>(base + 8);
    r.tcoordChannel = u.ReadPodAt<int32_t>(base + 12);
    return r;
}

std::shared_ptr<HkObject> Deser_hkxMaterial(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxMaterial>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->attributeGroups.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->attributeGroups[_i] = Deser_Inline_hkxAttributeGroup(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 40));
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->stages.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->stages[_i] = Deser_Inline_hkxMaterialTextureStage(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    r->diffuseColor = u.ReadPodAt<hkVector4>(base + 64);
    r->ambientColor = u.ReadPodAt<hkVector4>(base + 80);
    r->specularColor = u.ReadPodAt<hkVector4>(base + 96);
    r->emissiveColor = u.ReadPodAt<hkVector4>(base + 112);
    r->subMaterials = u.ReadPodArray<std::shared_ptr<DefType>>(base + 128);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 144);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->extraData = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    r->uvMapScale = u.ReadPodAt<std::array<float, 2>>(base + 152);
    r->uvMapOffset = u.ReadPodAt<std::array<float, 2>>(base + 160);
    r->uvMapRotation = u.ReadPodAt<float>(base + 168);
    r->uvMapAlgorithm = u.ReadPodAt<uint32_t>(base + 172);
    r->specularMultiplier = u.ReadPodAt<float>(base + 176);
    r->specularExponent = u.ReadPodAt<float>(base + 180);
    r->transparency = u.ReadPodAt<uint8_t>(base + 184);
    r->userData = u.ReadPodAt<uint64_t>(base + 192);
    r->properties = u.ReadPodArray<hkxMaterialProperty>(base + 200);

    return r;
}

std::shared_ptr<HkObject> Deser_hkxMesh(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxMesh>();
    const size_t base = item.absoluteDataOffset;

    r->sections = u.ReadPodArray<std::shared_ptr<hkxMeshSection>>(base + 24);
    r->userChannelInfos = u.ReadPodArray<std::shared_ptr<hkxMeshUserChannelInfo>>(base + 40);

    return r;
}

static hkxVertexBufferVertexData Deser_Inline_hkxVertexBufferVertexData(TagFileUnpacker& u, size_t base)
{
    hkxVertexBufferVertexData r{};
    r.vectorData = u.ReadPodArray<uint32_t>(base + 0);
    r.floatData = u.ReadPodArray<uint32_t>(base + 16);
    r.uint32Data = u.ReadPodArray<uint32_t>(base + 32);
    r.uint16Data = u.ReadPodArray<uint16_t>(base + 48);
    r.uint8Data = u.ReadPodArray<uint8_t>(base + 64);
    r.numVerts = u.ReadPodAt<uint32_t>(base + 80);
    r.vectorStride = u.ReadPodAt<uint32_t>(base + 84);
    r.floatStride = u.ReadPodAt<uint32_t>(base + 88);
    r.uint32Stride = u.ReadPodAt<uint32_t>(base + 92);
    r.uint16Stride = u.ReadPodAt<uint32_t>(base + 96);
    r.uint8Stride = u.ReadPodAt<uint32_t>(base + 100);
    return r;
}

static hkxVertexDescriptionElementDecl Deser_Inline_hkxVertexDescriptionElementDecl(TagFileUnpacker& u, size_t base)
{
    hkxVertexDescriptionElementDecl r{};
    r.byteOffset = u.ReadPodAt<uint32_t>(base + 0);
    r.type = u.ReadPodAt<uint16_t>(base + 4);
    r.usage = u.ReadPodAt<uint16_t>(base + 6);
    r.byteStride = u.ReadPodAt<uint32_t>(base + 8);
    r.numElements = u.ReadPodAt<uint8_t>(base + 12);
    r.channelID = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 16));
    return r;
}

static hkxVertexDescription Deser_Inline_hkxVertexDescription(TagFileUnpacker& u, size_t base)
{
    hkxVertexDescription r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 0));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.decls.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.decls[_i] = Deser_Inline_hkxVertexDescriptionElementDecl(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    return r;
}

std::shared_ptr<HkObject> Deser_hkxVertexBuffer(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxVertexBuffer>();
    const size_t base = item.absoluteDataOffset;

    r->data = Deser_Inline_hkxVertexBufferVertexData(u, base + 24);
    r->desc = Deser_Inline_hkxVertexDescription(u, base + 128);

    return r;
}

std::shared_ptr<HkObject> Deser_hkxMeshSection(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxMeshSection>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->vertexBuffer = std::static_pointer_cast<hkxVertexBuffer>(_obj);
    }
    r->indexBuffers = u.ReadPodArray<std::shared_ptr<hkxIndexBuffer>>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 48);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->material = std::static_pointer_cast<hkxMaterial>(_obj);
    }
    r->userChannels = u.ReadPodArray<std::shared_ptr<hkReferencedObject>>(base + 56);
    r->vertexAnimations = u.ReadPodArray<std::shared_ptr<hkxVertexAnimation>>(base + 72);
    r->linearKeyFrameHints = u.ReadPodArray<_float>(base + 88);
    r->boneMatrixMap = u.ReadPodArray<hkMeshBoneIndexMapping>(base + 104);

    return r;
}

std::shared_ptr<HkObject> Deser_hkxMeshUserChannelInfo(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxMeshUserChannelInfo>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->attributeGroups.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->attributeGroups[_i] = Deser_Inline_hkxAttributeGroup(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 40));
    r->className = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 48));

    return r;
}

std::shared_ptr<HkObject> Deser_hkxVertexAnimation(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkxVertexAnimation>();
    const size_t base = item.absoluteDataOffset;

    r->time = u.ReadPodAt<float>(base + 24);
    r->vertData = Deser_Inline_hkxVertexBuffer(u, base + 32);
    r->vertexIndexMap = u.ReadPodArray<int32_t>(base + 176);
    r->componentMap = u.ReadPodArray<hkxVertexAnimationUsageMap>(base + 192);

    return r;
}

void RegisterHkxDispatch(TagFileUnpacker& u)
{
    u.Register("hkxAttributeHolder", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxAttributeHolder(u_, i_);
    });
    u.Register("hkxIndexBuffer", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxIndexBuffer(u_, i_);
    });
    u.Register("hkxMaterial", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxMaterial(u_, i_);
    });
    u.Register("hkxMesh", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxMesh(u_, i_);
    });
    u.Register("hkxVertexBuffer", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxVertexBuffer(u_, i_);
    });
    u.Register("hkxMeshSection", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxMeshSection(u_, i_);
    });
    u.Register("hkxMesh::UserChannelInfo", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxMeshUserChannelInfo(u_, i_);
    });
    u.Register("hkxVertexAnimation", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkxVertexAnimation(u_, i_);
    });
}

}  // namespace Firelink::Havok