"""Type stubs for the _pyrelink_er_maps C++ extension module."""

from __future__ import annotations

import enum
from typing import Optional, Sequence, Union
from os import PathLike

# ── GroupBitSet ──────────────────────────────────────────────────────────

class GroupBitSet128:
    def __init__(self, bits: set[int] = ...) -> None: ...
    @staticmethod
    def all_on() -> GroupBitSet128: ...
    @staticmethod
    def all_off() -> GroupBitSet128: ...
    def enable(self, index: int) -> None: ...
    def disable(self, index: int) -> None: ...
    def __getitem__(self, i: int) -> bool: ...
    def to_list(self) -> list[int]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GroupBitSet256:
    def __init__(self, bits: set[int] = ...) -> None: ...
    @staticmethod
    def all_on() -> GroupBitSet256: ...
    @staticmethod
    def all_off() -> GroupBitSet256: ...
    def enable(self, index: int) -> None: ...
    def disable(self, index: int) -> None: ...
    def __getitem__(self, i: int) -> bool: ...
    def to_list(self) -> list[int]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

class GroupBitSet1024:
    def __init__(self, bits: set[int] = ...) -> None: ...
    @staticmethod
    def all_on() -> GroupBitSet1024: ...
    @staticmethod
    def all_off() -> GroupBitSet1024: ...
    def enable(self, index: int) -> None: ...
    def disable(self, index: int) -> None: ...
    def __getitem__(self, i: int) -> bool: ...
    def to_list(self) -> list[int]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

# ── Shapes ───────────────────────────────────────────────────────────────

class Shape:
    @property
    def shape_type_name(self) -> str: ...
    @property
    def has_shape_data(self) -> bool: ...

class PointShape(Shape):
    def __init__(self) -> None: ...

class CircleShape(Shape):
    def __init__(self, radius: float = ...) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, value: float) -> None: ...

class SphereShape(Shape):
    def __init__(self, radius: float = ...) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, value: float) -> None: ...

class CylinderShape(Shape):
    def __init__(self, radius: float = ..., height: float = ...) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...

class RectangleShape(Shape):
    def __init__(self, width: float = ..., depth: float = ...) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def depth(self) -> float: ...
    @depth.setter
    def depth(self, value: float) -> None: ...

class BoxShape(Shape):
    def __init__(self, width: float = ..., depth: float = ..., height: float = ...) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def depth(self) -> float: ...
    @depth.setter
    def depth(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...

class CompositeShape(Shape):
    def __init__(self) -> None: ...

class ShapeType(enum.IntEnum):
    Point: int
    Circle: int
    Sphere: int
    Cylinder: int
    Rectangle: int
    Box: int
    Composite: int

# ── Part struct components ───────────────────────────────────────────────

class DrawInfo1:
    def __init__(self) -> None: ...
    display_groups: GroupBitSet256
    draw_groups: GroupBitSet256
    collision_mask: GroupBitSet1024
    condition_1a: int
    condition_1b: int
    unk_c2: int
    unk_c3: int
    unk_c4: int
    unk_c6: int

class DrawInfo2:
    def __init__(self) -> None: ...
    condition_2: int
    display_groups_2: GroupBitSet256
    unk_24: int
    unk_26: int

class GParam:
    def __init__(self) -> None: ...
    light_set_id: int
    fog_id: int
    light_scattering_id: int
    environment_map_id: int

class SceneGParam:
    def __init__(self) -> None: ...
    transition_time: float
    unk_18: int
    unk_19: int
    unk_1a: int
    unk_1b: int
    unk_1c: int
    unk_1d: int
    unk_20: int
    unk_21: int

class GrassConfig:
    def __init__(self) -> None: ...
    unk_00: int
    unk_04: int
    unk_08: int
    unk_0c: int
    unk_10: int
    unk_14: int
    unk_18: int

class UnkPartStruct8:
    def __init__(self) -> None: ...
    unk_00: int

class UnkPartStruct9:
    def __init__(self) -> None: ...
    unk_00: int

class TileLoadConfig:
    def __init__(self) -> None: ...
    map_id: int
    unk_04: int
    unk_0c: int
    unk_10: int
    unk_14: int

class UnkPartStruct11:
    def __init__(self) -> None: ...
    unk_00: int
    unk_04: int

class ExtraAssetData1:
    def __init__(self) -> None: ...
    unk_00: int
    unk_04: int
    disable_torrent_asset_only: bool
    unk_1c: int
    unk_24: int
    unk_26: int
    unk_28: int
    unk_2c: int

class ExtraAssetData2:
    def __init__(self) -> None: ...
    unk_00: int
    unk_04: int
    unk_14: int
    unk_1c: int
    unk_1d: int
    unk_1e: int
    unk_1f: int

class ExtraAssetData3:
    def __init__(self) -> None: ...
    unk_00: int
    unk_04: int
    unk_09: int
    unk_0a: int
    unk_0b: int
    unk_0c: int
    unk_0e: int
    unk_10: int
    unk_18: int
    unk_1c: int
    unk_20: int
    unk_24: int
    unk_25: int

class ExtraAssetData4:
    def __init__(self) -> None: ...
    unk_00: int
    unk_01: int
    unk_02: int
    unk_03: int

# ── Enums ────────────────────────────────────────────────────────────────

class ModelType(enum.IntEnum):
    MapPiece: int
    Character: int
    Player: int
    Collision: int
    Asset: int

class EventType(enum.IntEnum):
    Treasure: int
    Spawner: int
    ObjAct: int
    Navigation: int
    NPCInvasion: int
    Platoon: int
    PatrolRoute: int
    Mount: int
    SignPool: int
    RetryPoint: int
    AreaTeam: int
    Other: int

class RegionType(enum.IntEnum):
    InvasionPoint: int
    EnvironmentMapPoint: int
    Sound: int
    VFX: int
    WindVFX: int
    SpawnPoint: int
    Message: int
    EnvironmentMapEffectBox: int
    WindArea: int
    Connection: int
    PatrolRoute22: int
    BuddySummonPoint: int
    MufflingBox: int
    MufflingPortal: int
    OtherSound: int
    MufflingPlane: int
    PatrolRoute: int
    MapPoint: int
    WeatherOverride: int
    AutoDrawGroupPoint: int
    GroupDefeatReward: int
    MapPointDiscoveryOverride: int
    MapPointParticipationOverride: int
    Hitset: int
    FastTravelRestriction: int
    WeatherCreateAssetPoint: int
    PlayArea: int
    EnvironmentMapOutput: int
    MountJump: int
    Dummy: int
    FallPreventionRemoval: int
    NavmeshCutting: int
    MapNameOverride: int
    MountJumpFall: int
    HorseRideOverride: int
    Other: int

class PartType(enum.IntEnum):
    MapPiece: int
    Character: int
    PlayerStart: int
    Collision: int
    DummyAsset: int
    DummyCharacter: int
    ConnectCollision: int
    Asset: int

class RouteType(enum.IntEnum):
    MufflingPortalLink: int
    MufflingBoxLink: int
    Other: int

class CollisionHitFilter(enum.IntEnum):
    Normal: int
    CameraOnly: int
    NPCOnly: int
    FallDeathCam: int
    Kill: int
    Unk16: int
    Unk17: int
    Unk19: int
    Unk20: int
    Unk22: int
    Unk23: int
    Unk24: int
    Unk29: int

class HorseRideOverrideType(enum.IntEnum):
    Default: int
    Prevent: int
    Allow: int

class DCXType(enum.IntEnum):
    Unknown: int
    Null: int
    Zlib: int
    DCP_EDGE: int
    DCP_DFLT: int
    DCX_EDGE: int
    DCX_DFLT_10000_24_9: int
    DCX_DFLT_10000_44_9: int
    DCX_DFLT_11000_44_8: int
    DCX_DFLT_11000_44_9: int
    DCX_DFLT_11000_44_9_15: int
    DCX_KRAK: int
    DCX_ZSTD: int

# ── Models ───────────────────────────────────────────────────────────────

class Model:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def model_type(self) -> ModelType: ...
    def __repr__(self) -> str: ...

class MapPieceModel(Model):
    def __init__(self, name: str = ...) -> None: ...

class AssetModel(Model):
    def __init__(self, name: str = ...) -> None: ...

class CharacterModel(Model):
    def __init__(self, name: str = ...) -> None: ...

class PlayerModel(Model):
    def __init__(self, name: str = ...) -> None: ...

class CollisionModel(Model):
    def __init__(self, name: str = ...) -> None: ...

# ── Events ───────────────────────────────────────────────────────────────

class Event:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def event_type(self) -> EventType: ...
    @property
    def entity_id(self) -> int: ...
    @entity_id.setter
    def entity_id(self, value: int) -> None: ...
    @property
    def attached_part(self) -> Optional[Part]: ...
    @attached_part.setter
    def attached_part(self, value: Optional[Part]) -> None: ...
    @property
    def attached_region(self) -> Optional[Region]: ...
    @attached_region.setter
    def attached_region(self, value: Optional[Region]) -> None: ...
    @property
    def h_unk_14(self) -> int: ...
    @h_unk_14.setter
    def h_unk_14(self, value: int) -> None: ...
    @property
    def d_unk_0c(self) -> int: ...
    @d_unk_0c.setter
    def d_unk_0c(self, value: int) -> None: ...
    @property
    def map_id(self) -> int: ...
    @map_id.setter
    def map_id(self, value: int) -> None: ...
    @property
    def e_unk_04(self) -> int: ...
    @e_unk_04.setter
    def e_unk_04(self, value: int) -> None: ...
    @property
    def e_unk_08(self) -> int: ...
    @e_unk_08.setter
    def e_unk_08(self, value: int) -> None: ...
    @property
    def e_unk_0c(self) -> int: ...
    @e_unk_0c.setter
    def e_unk_0c(self, value: int) -> None: ...
    def __repr__(self) -> str: ...

class TreasureEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def treasure_part(self) -> Optional[Part]: ...
    @treasure_part.setter
    def treasure_part(self, value: Optional[Part]) -> None: ...
    @property
    def item_lot(self) -> int: ...
    @item_lot.setter
    def item_lot(self, value: int) -> None: ...
    @property
    def action_button_id(self) -> int: ...
    @action_button_id.setter
    def action_button_id(self, value: int) -> None: ...
    @property
    def pickup_animation_id(self) -> int: ...
    @pickup_animation_id.setter
    def pickup_animation_id(self, value: int) -> None: ...
    @property
    def in_chest(self) -> bool: ...
    @in_chest.setter
    def in_chest(self, value: bool) -> None: ...
    @property
    def starts_disabled(self) -> bool: ...
    @starts_disabled.setter
    def starts_disabled(self, value: bool) -> None: ...

class SpawnerEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def max_count(self) -> int: ...
    @max_count.setter
    def max_count(self, value: int) -> None: ...
    @property
    def spawner_type(self) -> int: ...
    @spawner_type.setter
    def spawner_type(self, value: int) -> None: ...
    @property
    def limit_count(self) -> int: ...
    @limit_count.setter
    def limit_count(self, value: int) -> None: ...
    @property
    def min_spawner_count(self) -> int: ...
    @min_spawner_count.setter
    def min_spawner_count(self, value: int) -> None: ...
    @property
    def max_spawner_count(self) -> int: ...
    @max_spawner_count.setter
    def max_spawner_count(self, value: int) -> None: ...
    @property
    def min_interval(self) -> float: ...
    @min_interval.setter
    def min_interval(self, value: float) -> None: ...
    @property
    def max_interval(self) -> float: ...
    @max_interval.setter
    def max_interval(self, value: float) -> None: ...
    @property
    def initial_spawn_count(self) -> int: ...
    @initial_spawn_count.setter
    def initial_spawn_count(self, value: int) -> None: ...
    @property
    def spawner_unk_14(self) -> int: ...
    @spawner_unk_14.setter
    def spawner_unk_14(self, value: int) -> None: ...
    @property
    def spawner_unk_18(self) -> int: ...
    @spawner_unk_18.setter
    def spawner_unk_18(self, value: int) -> None: ...
    def get_spawn_part(self, index: int) -> Optional[Part]: ...
    def set_spawn_part(self, index: int, part: Optional[Part]) -> None: ...
    def get_spawn_region(self, index: int) -> Optional[Region]: ...
    def set_spawn_region(self, index: int, region: Optional[Region]) -> None: ...

class NavigationEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def navigation_region(self) -> Optional[Region]: ...
    @navigation_region.setter
    def navigation_region(self, value: Optional[Region]) -> None: ...

class ObjActEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def obj_act_entity_id(self) -> int: ...
    @obj_act_entity_id.setter
    def obj_act_entity_id(self, value: int) -> None: ...
    @property
    def obj_act_part(self) -> Optional[Part]: ...
    @obj_act_part.setter
    def obj_act_part(self, value: Optional[Part]) -> None: ...
    @property
    def obj_act_param_id(self) -> int: ...
    @obj_act_param_id.setter
    def obj_act_param_id(self, value: int) -> None: ...
    @property
    def obj_act_state(self) -> int: ...
    @obj_act_state.setter
    def obj_act_state(self, value: int) -> None: ...
    @property
    def obj_act_flag(self) -> int: ...
    @obj_act_flag.setter
    def obj_act_flag(self, value: int) -> None: ...

class NPCInvasionEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def host_entity_id(self) -> int: ...
    @host_entity_id.setter
    def host_entity_id(self, value: int) -> None: ...
    @property
    def invasion_flag_id(self) -> int: ...
    @invasion_flag_id.setter
    def invasion_flag_id(self, value: int) -> None: ...
    @property
    def activate_good_id(self) -> int: ...
    @activate_good_id.setter
    def activate_good_id(self, value: int) -> None: ...
    @property
    def unk_0c(self) -> int: ...
    @unk_0c.setter
    def unk_0c(self, value: int) -> None: ...
    @property
    def unk_10(self) -> int: ...
    @unk_10.setter
    def unk_10(self, value: int) -> None: ...
    @property
    def unk_14(self) -> int: ...
    @unk_14.setter
    def unk_14(self, value: int) -> None: ...
    @property
    def unk_18(self) -> int: ...
    @unk_18.setter
    def unk_18(self, value: int) -> None: ...
    @property
    def unk_1c(self) -> int: ...
    @unk_1c.setter
    def unk_1c(self, value: int) -> None: ...

class PlatoonEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def platoon_id_script_activate(self) -> int: ...
    @platoon_id_script_activate.setter
    def platoon_id_script_activate(self, value: int) -> None: ...
    @property
    def state(self) -> int: ...
    @state.setter
    def state(self, value: int) -> None: ...
    def get_platoon_part(self, index: int) -> Optional[Part]: ...
    def set_platoon_part(self, index: int, part: Optional[Part]) -> None: ...

class PatrolRouteEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def patrol_type(self) -> int: ...
    @patrol_type.setter
    def patrol_type(self, value: int) -> None: ...
    def get_patrol_region(self, index: int) -> Optional[Region]: ...
    def set_patrol_region(self, index: int, region: Optional[Region]) -> None: ...

class MountEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def rider_part(self) -> Optional[Part]: ...
    @rider_part.setter
    def rider_part(self, value: Optional[Part]) -> None: ...
    @property
    def mount_part(self) -> Optional[Part]: ...
    @mount_part.setter
    def mount_part(self, value: Optional[Part]) -> None: ...

class SignPoolEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def sign_part(self) -> Optional[Part]: ...
    @sign_part.setter
    def sign_part(self, value: Optional[Part]) -> None: ...
    @property
    def sign_pool_unk_04(self) -> int: ...
    @sign_pool_unk_04.setter
    def sign_pool_unk_04(self, value: int) -> None: ...

class RetryPointEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def retry_part(self) -> Optional[Part]: ...
    @retry_part.setter
    def retry_part(self, value: Optional[Part]) -> None: ...
    @property
    def event_flag_id(self) -> int: ...
    @event_flag_id.setter
    def event_flag_id(self, value: int) -> None: ...
    @property
    def retry_point_unk_08(self) -> int: ...
    @retry_point_unk_08.setter
    def retry_point_unk_08(self, value: int) -> None: ...
    @property
    def retry_region(self) -> Optional[Region]: ...
    @retry_region.setter
    def retry_region(self, value: Optional[Region]) -> None: ...

class AreaTeamEvent(Event):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def leader_entity_id(self) -> int: ...
    @leader_entity_id.setter
    def leader_entity_id(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_0c(self) -> int: ...
    @s_unk_0c.setter
    def s_unk_0c(self, value: int) -> None: ...
    @property
    def leader_region_entity_id(self) -> int: ...
    @leader_region_entity_id.setter
    def leader_region_entity_id(self, value: int) -> None: ...
    @property
    def guest_1_region_entity_id(self) -> int: ...
    @guest_1_region_entity_id.setter
    def guest_1_region_entity_id(self, value: int) -> None: ...
    @property
    def guest_2_region_entity_id(self) -> int: ...
    @guest_2_region_entity_id.setter
    def guest_2_region_entity_id(self, value: int) -> None: ...
    @property
    def s_unk_1c(self) -> int: ...
    @s_unk_1c.setter
    def s_unk_1c(self, value: int) -> None: ...
    @property
    def s_unk_20(self) -> int: ...
    @s_unk_20.setter
    def s_unk_20(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> int: ...
    @s_unk_24.setter
    def s_unk_24(self, value: int) -> None: ...
    @property
    def s_unk_28(self) -> int: ...
    @s_unk_28.setter
    def s_unk_28(self, value: int) -> None: ...

class OtherEvent(Event):
    def __init__(self, name: str = ...) -> None: ...

# ── Regions ──────────────────────────────────────────────────────────────

Vec3 = tuple[float, float, float]

class Region:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def region_type(self) -> RegionType: ...
    @property
    def entity_id(self) -> int: ...
    @entity_id.setter
    def entity_id(self, value: int) -> None: ...
    @property
    def translate(self) -> Vec3: ...
    @translate.setter
    def translate(self, value: Sequence[float]) -> None: ...
    @property
    def rotate(self) -> Vec3: ...
    @rotate.setter
    def rotate(self, value: Sequence[float]) -> None: ...
    @property
    def h_unk_40(self) -> int: ...
    @h_unk_40.setter
    def h_unk_40(self, value: int) -> None: ...
    @property
    def event_layer(self) -> int: ...
    @event_layer.setter
    def event_layer(self, value: int) -> None: ...
    @property
    def attached_part(self) -> Optional[Part]: ...
    @attached_part.setter
    def attached_part(self, value: Optional[Part]) -> None: ...
    @property
    def d_unk_08(self) -> int: ...
    @d_unk_08.setter
    def d_unk_08(self, value: int) -> None: ...
    @property
    def map_id(self) -> int: ...
    @map_id.setter
    def map_id(self, value: int) -> None: ...
    @property
    def e_unk_04(self) -> int: ...
    @e_unk_04.setter
    def e_unk_04(self, value: int) -> None: ...
    @property
    def e_unk_0c(self) -> int: ...
    @e_unk_0c.setter
    def e_unk_0c(self, value: int) -> None: ...
    @property
    def shape_type(self) -> ShapeType: ...
    @property
    def shape_type_name(self) -> str: ...
    def set_shape_type(self, shape_type: ShapeType) -> Shape: ...
    @property
    def shape(self) -> Optional[Shape]: ...
    def __repr__(self) -> str: ...

class InvasionPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def priority(self) -> int: ...
    @priority.setter
    def priority(self, value: int) -> None: ...

class EnvironmentMapPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> float: ...
    @s_unk_00.setter
    def s_unk_00(self, value: float) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...
    @property
    def s_unk_0d(self) -> bool: ...
    @s_unk_0d.setter
    def s_unk_0d(self, value: bool) -> None: ...
    @property
    def s_unk_0e(self) -> bool: ...
    @s_unk_0e.setter
    def s_unk_0e(self, value: bool) -> None: ...
    @property
    def s_unk_0f(self) -> bool: ...
    @s_unk_0f.setter
    def s_unk_0f(self, value: bool) -> None: ...
    @property
    def s_unk_10(self) -> float: ...
    @s_unk_10.setter
    def s_unk_10(self, value: float) -> None: ...
    @property
    def s_unk_14(self) -> float: ...
    @s_unk_14.setter
    def s_unk_14(self, value: float) -> None: ...
    @property
    def s_map_id(self) -> int: ...
    @s_map_id.setter
    def s_map_id(self, value: int) -> None: ...
    @property
    def s_unk_20(self) -> int: ...
    @s_unk_20.setter
    def s_unk_20(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> int: ...
    @s_unk_24.setter
    def s_unk_24(self, value: int) -> None: ...
    @property
    def s_unk_28(self) -> int: ...
    @s_unk_28.setter
    def s_unk_28(self, value: int) -> None: ...
    @property
    def s_unk_2c(self) -> int: ...
    @s_unk_2c.setter
    def s_unk_2c(self, value: int) -> None: ...
    @property
    def s_unk_2d(self) -> int: ...
    @s_unk_2d.setter
    def s_unk_2d(self, value: int) -> None: ...

class SoundRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def sound_type(self) -> int: ...
    @sound_type.setter
    def sound_type(self, value: int) -> None: ...
    @property
    def sound_id(self) -> int: ...
    @sound_id.setter
    def sound_id(self, value: int) -> None: ...
    @property
    def s_unk_49(self) -> bool: ...
    @s_unk_49.setter
    def s_unk_49(self, value: bool) -> None: ...
    def get_child_region(self, index: int) -> Optional[Region]: ...
    def set_child_region(self, index: int, region: Optional[Region]) -> None: ...

class VFXRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def effect_id(self) -> int: ...
    @effect_id.setter
    def effect_id(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...

class WindVFXRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def effect_id(self) -> int: ...
    @effect_id.setter
    def effect_id(self, value: int) -> None: ...
    @property
    def wind_region(self) -> Optional[Region]: ...
    @wind_region.setter
    def wind_region(self, value: Optional[Region]) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...

class SpawnPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class MessageRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def message_id(self) -> int: ...
    @message_id.setter
    def message_id(self, value: int) -> None: ...
    @property
    def s_unk_02(self) -> int: ...
    @s_unk_02.setter
    def s_unk_02(self, value: int) -> None: ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, value: bool) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_0c(self) -> int: ...
    @s_unk_0c.setter
    def s_unk_0c(self, value: int) -> None: ...
    @property
    def enable_event_flag_id(self) -> int: ...
    @enable_event_flag_id.setter
    def enable_event_flag_id(self, value: int) -> None: ...
    @property
    def character_model_name(self) -> str: ...
    @character_model_name.setter
    def character_model_name(self, value: str) -> None: ...
    @property
    def character_id(self) -> int: ...
    @character_id.setter
    def character_id(self, value: int) -> None: ...
    @property
    def animation_id(self) -> int: ...
    @animation_id.setter
    def animation_id(self, value: int) -> None: ...
    @property
    def player_id(self) -> int: ...
    @player_id.setter
    def player_id(self, value: int) -> None: ...

class EnvironmentMapEffectBoxRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def enable_dist(self) -> float: ...
    @enable_dist.setter
    def enable_dist(self, value: float) -> None: ...
    @property
    def transition_dist(self) -> float: ...
    @transition_dist.setter
    def transition_dist(self, value: float) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_09(self) -> int: ...
    @s_unk_09.setter
    def s_unk_09(self, value: int) -> None: ...
    @property
    def s_unk_0a(self) -> int: ...
    @s_unk_0a.setter
    def s_unk_0a(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> float: ...
    @s_unk_24.setter
    def s_unk_24(self, value: float) -> None: ...
    @property
    def s_unk_28(self) -> float: ...
    @s_unk_28.setter
    def s_unk_28(self, value: float) -> None: ...
    @property
    def s_unk_2c(self) -> int: ...
    @s_unk_2c.setter
    def s_unk_2c(self, value: int) -> None: ...
    @property
    def s_unk_2e(self) -> bool: ...
    @s_unk_2e.setter
    def s_unk_2e(self, value: bool) -> None: ...
    @property
    def s_unk_2f(self) -> bool: ...
    @s_unk_2f.setter
    def s_unk_2f(self, value: bool) -> None: ...
    @property
    def s_unk_30(self) -> int: ...
    @s_unk_30.setter
    def s_unk_30(self, value: int) -> None: ...
    @property
    def s_unk_33(self) -> bool: ...
    @s_unk_33.setter
    def s_unk_33(self, value: bool) -> None: ...
    @property
    def s_unk_34(self) -> int: ...
    @s_unk_34.setter
    def s_unk_34(self, value: int) -> None: ...
    @property
    def s_unk_36(self) -> int: ...
    @s_unk_36.setter
    def s_unk_36(self, value: int) -> None: ...

class WindAreaRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class ConnectionRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def target_map_id(self) -> tuple[int, int, int, int]: ...
    @target_map_id.setter
    def target_map_id(self, value: tuple[int, int, int, int]) -> None: ...

class PatrolRoute22Region(Region):
    def __init__(self, name: str = ...) -> None: ...

class BuddySummonPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class MufflingBoxRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> float: ...
    @s_unk_24.setter
    def s_unk_24(self, value: float) -> None: ...
    @property
    def s_unk_34(self) -> float: ...
    @s_unk_34.setter
    def s_unk_34(self, value: float) -> None: ...
    @property
    def s_unk_3c(self) -> int: ...
    @s_unk_3c.setter
    def s_unk_3c(self, value: int) -> None: ...
    @property
    def s_unk_40(self) -> float: ...
    @s_unk_40.setter
    def s_unk_40(self, value: float) -> None: ...
    @property
    def s_unk_44(self) -> int: ...
    @s_unk_44.setter
    def s_unk_44(self, value: int) -> None: ...

class MufflingPortalRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...

class OtherSoundRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    @property
    def s_unk_01(self) -> int: ...
    @s_unk_01.setter
    def s_unk_01(self, value: int) -> None: ...
    @property
    def s_unk_02(self) -> int: ...
    @s_unk_02.setter
    def s_unk_02(self, value: int) -> None: ...
    @property
    def s_unk_03(self) -> int: ...
    @s_unk_03.setter
    def s_unk_03(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_0a(self) -> int: ...
    @s_unk_0a.setter
    def s_unk_0a(self, value: int) -> None: ...
    @property
    def s_unk_0c(self) -> int: ...
    @s_unk_0c.setter
    def s_unk_0c(self, value: int) -> None: ...

class MufflingPlaneRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class PatrolRouteRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...

class MapPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_0c(self) -> float: ...
    @s_unk_0c.setter
    def s_unk_0c(self, value: float) -> None: ...
    @property
    def s_unk_14(self) -> float: ...
    @s_unk_14.setter
    def s_unk_14(self, value: float) -> None: ...
    @property
    def s_unk_18(self) -> float: ...
    @s_unk_18.setter
    def s_unk_18(self, value: float) -> None: ...

class WeatherOverrideRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def weather_lot_id(self) -> int: ...
    @weather_lot_id.setter
    def weather_lot_id(self, value: int) -> None: ...

class AutoDrawGroupPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...

class GroupDefeatRewardRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    def get_group_part(self, index: int) -> Optional[Part]: ...
    def set_group_part(self, index: int, part: Optional[Part]) -> None: ...
    @property
    def s_unk_34(self) -> int: ...
    @s_unk_34.setter
    def s_unk_34(self, value: int) -> None: ...
    @property
    def s_unk_38(self) -> int: ...
    @s_unk_38.setter
    def s_unk_38(self, value: int) -> None: ...
    @property
    def s_unk_54(self) -> int: ...
    @s_unk_54.setter
    def s_unk_54(self, value: int) -> None: ...

class MapPointDiscoveryOverrideRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class MapPointParticipationOverrideRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class HitsetRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...

class FastTravelRestrictionRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def event_flag_id(self) -> int: ...
    @event_flag_id.setter
    def event_flag_id(self, value: int) -> None: ...

class WeatherCreateAssetPointRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class PlayAreaRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...

class EnvironmentMapOutputRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class MountJumpRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def jump_height(self) -> float: ...
    @jump_height.setter
    def jump_height(self, value: float) -> None: ...
    @property
    def s_unk_04(self) -> int: ...
    @s_unk_04.setter
    def s_unk_04(self, value: int) -> None: ...

class DummyRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...

class FallPreventionRemovalRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class NavmeshCuttingRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class MapNameOverrideRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def map_name_id(self) -> int: ...
    @map_name_id.setter
    def map_name_id(self, value: int) -> None: ...

class MountJumpFallRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

class HorseRideOverrideRegion(Region):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def override_type(self) -> HorseRideOverrideType: ...
    @override_type.setter
    def override_type(self, value: HorseRideOverrideType) -> None: ...

class OtherRegion(Region):
    def __init__(self, name: str = ...) -> None: ...

# ── Routes ───────────────────────────────────────────────────────────────

class Route:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def route_type(self) -> RouteType: ...
    @property
    def h_unk_08(self) -> int: ...
    @h_unk_08.setter
    def h_unk_08(self, value: int) -> None: ...
    @property
    def h_unk_0c(self) -> int: ...
    @h_unk_0c.setter
    def h_unk_0c(self, value: int) -> None: ...
    def __repr__(self) -> str: ...

class MufflingPortalLinkRoute(Route):
    def __init__(self, name: str = ...) -> None: ...

class MufflingBoxLinkRoute(Route):
    def __init__(self, name: str = ...) -> None: ...

class OtherRoute(Route):
    def __init__(self, name: str = ...) -> None: ...

# ── Parts ────────────────────────────────────────────────────────────────

class Part:
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def part_type(self) -> PartType: ...
    @property
    def entity_id(self) -> int: ...
    @entity_id.setter
    def entity_id(self, value: int) -> None: ...
    @property
    def model(self) -> Optional[Model]: ...
    @model.setter
    def model(self, value: Optional[Model]) -> None: ...
    @property
    def model_instance_id(self) -> int: ...
    @model_instance_id.setter
    def model_instance_id(self, value: int) -> None: ...
    @property
    def sib_path(self) -> str: ...
    @sib_path.setter
    def sib_path(self, value: str) -> None: ...
    @property
    def translate(self) -> Vec3: ...
    @translate.setter
    def translate(self, value: Sequence[float]) -> None: ...
    @property
    def rotate(self) -> Vec3: ...
    @rotate.setter
    def rotate(self, value: Sequence[float]) -> None: ...
    @property
    def scale(self) -> Vec3: ...
    @scale.setter
    def scale(self, value: Sequence[float]) -> None: ...
    @property
    def unk_44(self) -> int: ...
    @unk_44.setter
    def unk_44(self, value: int) -> None: ...
    @property
    def event_layer(self) -> int: ...
    @event_layer.setter
    def event_layer(self, value: int) -> None: ...
    @property
    def unk_04(self) -> int: ...
    @unk_04.setter
    def unk_04(self, value: int) -> None: ...
    @property
    def lod_id(self) -> int: ...
    @lod_id.setter
    def lod_id(self, value: int) -> None: ...
    @property
    def unk_09(self) -> int: ...
    @unk_09.setter
    def unk_09(self, value: int) -> None: ...
    @property
    def is_point_light_shadow_source(self) -> int: ...
    @is_point_light_shadow_source.setter
    def is_point_light_shadow_source(self, value: int) -> None: ...
    @property
    def unk_0b(self) -> int: ...
    @unk_0b.setter
    def unk_0b(self, value: int) -> None: ...
    @property
    def is_shadow_source(self) -> bool: ...
    @is_shadow_source.setter
    def is_shadow_source(self, value: bool) -> None: ...
    @property
    def is_static_shadow_source(self) -> int: ...
    @is_static_shadow_source.setter
    def is_static_shadow_source(self, value: int) -> None: ...
    @property
    def is_cascade_3_shadow_source(self) -> int: ...
    @is_cascade_3_shadow_source.setter
    def is_cascade_3_shadow_source(self, value: int) -> None: ...
    @property
    def unk_0f(self) -> int: ...
    @unk_0f.setter
    def unk_0f(self, value: int) -> None: ...
    @property
    def unk_10(self) -> int: ...
    @unk_10.setter
    def unk_10(self, value: int) -> None: ...
    @property
    def is_shadow_destination(self) -> bool: ...
    @is_shadow_destination.setter
    def is_shadow_destination(self, value: bool) -> None: ...
    @property
    def is_shadow_only(self) -> bool: ...
    @is_shadow_only.setter
    def is_shadow_only(self, value: bool) -> None: ...
    @property
    def draw_by_reflect_cam(self) -> bool: ...
    @draw_by_reflect_cam.setter
    def draw_by_reflect_cam(self, value: bool) -> None: ...
    @property
    def draw_only_reflect_cam(self) -> bool: ...
    @draw_only_reflect_cam.setter
    def draw_only_reflect_cam(self, value: bool) -> None: ...
    @property
    def enable_on_above_shadow(self) -> int: ...
    @enable_on_above_shadow.setter
    def enable_on_above_shadow(self, value: int) -> None: ...
    @property
    def disable_point_light_effect(self) -> bool: ...
    @disable_point_light_effect.setter
    def disable_point_light_effect(self, value: bool) -> None: ...
    @property
    def unk_17(self) -> int: ...
    @unk_17.setter
    def unk_17(self, value: int) -> None: ...
    @property
    def unk_18(self) -> int: ...
    @unk_18.setter
    def unk_18(self, value: int) -> None: ...
    @property
    def entity_group_ids(self) -> list[int]: ...
    @entity_group_ids.setter
    def entity_group_ids(self, value: list[int]) -> None: ...
    @property
    def unk_3c(self) -> int: ...
    @unk_3c.setter
    def unk_3c(self, value: int) -> None: ...
    @property
    def unk_3e(self) -> int: ...
    @unk_3e.setter
    def unk_3e(self, value: int) -> None: ...
    def __repr__(self) -> str: ...

class MapPiecePart(Part):
    def __init__(self, name: str = ...) -> None: ...
    draw_info_1: DrawInfo1
    gparam: GParam
    grass_config: GrassConfig
    unk_struct_8: UnkPartStruct8
    unk_struct_9: UnkPartStruct9
    tile_load_config: TileLoadConfig
    unk_struct_11: UnkPartStruct11

class CharacterPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def ai_id(self) -> int: ...
    @ai_id.setter
    def ai_id(self, value: int) -> None: ...
    @property
    def character_id(self) -> int: ...
    @character_id.setter
    def character_id(self, value: int) -> None: ...
    @property
    def talk_id(self) -> int: ...
    @talk_id.setter
    def talk_id(self, value: int) -> None: ...
    @property
    def s_unk_15(self) -> bool: ...
    @s_unk_15.setter
    def s_unk_15(self, value: bool) -> None: ...
    @property
    def platoon_id(self) -> int: ...
    @platoon_id.setter
    def platoon_id(self, value: int) -> None: ...
    @property
    def player_id(self) -> int: ...
    @player_id.setter
    def player_id(self, value: int) -> None: ...
    @property
    def draw_parent(self) -> Optional[Part]: ...
    @draw_parent.setter
    def draw_parent(self, value: Optional[Part]) -> None: ...
    @property
    def patrol_route_event(self) -> Optional[PatrolRouteEvent]: ...
    @patrol_route_event.setter
    def patrol_route_event(self, value: Optional[PatrolRouteEvent]) -> None: ...
    @property
    def s_unk_24(self) -> int: ...
    @s_unk_24.setter
    def s_unk_24(self, value: int) -> None: ...
    @property
    def s_unk_28(self) -> int: ...
    @s_unk_28.setter
    def s_unk_28(self, value: int) -> None: ...
    @property
    def activate_condition_param_id(self) -> int: ...
    @activate_condition_param_id.setter
    def activate_condition_param_id(self, value: int) -> None: ...
    @property
    def s_unk_34(self) -> int: ...
    @s_unk_34.setter
    def s_unk_34(self, value: int) -> None: ...
    @property
    def back_away_event_animation_id(self) -> int: ...
    @back_away_event_animation_id.setter
    def back_away_event_animation_id(self, value: int) -> None: ...
    @property
    def s_unk_3c(self) -> int: ...
    @s_unk_3c.setter
    def s_unk_3c(self, value: int) -> None: ...
    @property
    def special_effect_set_param_ids(self) -> list[int]: ...
    @special_effect_set_param_ids.setter
    def special_effect_set_param_ids(self, value: list[int]) -> None: ...
    @property
    def s_unk_84(self) -> int: ...
    @s_unk_84.setter
    def s_unk_84(self, value: int) -> None: ...
    draw_info_1: DrawInfo1
    gparam: GParam
    unk_struct_8: UnkPartStruct8
    tile_load_config: TileLoadConfig

class DummyCharacterPart(CharacterPart):
    def __init__(self, name: str = ...) -> None: ...

class PlayerStartPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_00(self) -> int: ...
    @s_unk_00.setter
    def s_unk_00(self, value: int) -> None: ...
    draw_info_1: DrawInfo1
    unk_struct_8: UnkPartStruct8
    tile_load_config: TileLoadConfig

class CollisionPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def hit_filter_id(self) -> int: ...
    @hit_filter_id.setter
    def hit_filter_id(self, value: int) -> None: ...
    @property
    def s_unk_01(self) -> int: ...
    @s_unk_01.setter
    def s_unk_01(self, value: int) -> None: ...
    @property
    def s_unk_02(self) -> int: ...
    @s_unk_02.setter
    def s_unk_02(self, value: int) -> None: ...
    @property
    def s_unk_03(self) -> int: ...
    @s_unk_03.setter
    def s_unk_03(self, value: int) -> None: ...
    @property
    def s_unk_04(self) -> float: ...
    @s_unk_04.setter
    def s_unk_04(self, value: float) -> None: ...
    @property
    def s_unk_14(self) -> int: ...
    @s_unk_14.setter
    def s_unk_14(self, value: int) -> None: ...
    @property
    def s_unk_18(self) -> int: ...
    @s_unk_18.setter
    def s_unk_18(self, value: int) -> None: ...
    @property
    def s_unk_1c(self) -> int: ...
    @s_unk_1c.setter
    def s_unk_1c(self, value: int) -> None: ...
    @property
    def play_region_id(self) -> int: ...
    @play_region_id.setter
    def play_region_id(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> int: ...
    @s_unk_24.setter
    def s_unk_24(self, value: int) -> None: ...
    @property
    def s_unk_26(self) -> int: ...
    @s_unk_26.setter
    def s_unk_26(self, value: int) -> None: ...
    @property
    def s_unk_30(self) -> int: ...
    @s_unk_30.setter
    def s_unk_30(self, value: int) -> None: ...
    @property
    def s_unk_34(self) -> int: ...
    @s_unk_34.setter
    def s_unk_34(self, value: int) -> None: ...
    @property
    def s_unk_35(self) -> int: ...
    @s_unk_35.setter
    def s_unk_35(self, value: int) -> None: ...
    @property
    def disable_torrent(self) -> bool: ...
    @disable_torrent.setter
    def disable_torrent(self, value: bool) -> None: ...
    @property
    def s_unk_3c(self) -> int: ...
    @s_unk_3c.setter
    def s_unk_3c(self, value: int) -> None: ...
    @property
    def s_unk_3e(self) -> int: ...
    @s_unk_3e.setter
    def s_unk_3e(self, value: int) -> None: ...
    @property
    def s_unk_40(self) -> int: ...
    @s_unk_40.setter
    def s_unk_40(self, value: int) -> None: ...
    @property
    def enable_fast_travel_flag_id(self) -> int: ...
    @enable_fast_travel_flag_id.setter
    def enable_fast_travel_flag_id(self, value: int) -> None: ...
    @property
    def s_unk_4c(self) -> int: ...
    @s_unk_4c.setter
    def s_unk_4c(self, value: int) -> None: ...
    @property
    def s_unk_4e(self) -> int: ...
    @s_unk_4e.setter
    def s_unk_4e(self, value: int) -> None: ...
    draw_info_1: DrawInfo1
    draw_info_2: DrawInfo2
    gparam: GParam
    scene_gparam: SceneGParam
    unk_struct_8: UnkPartStruct8
    tile_load_config: TileLoadConfig
    unk_struct_11: UnkPartStruct11

class DummyAssetPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_18(self) -> int: ...
    @s_unk_18.setter
    def s_unk_18(self, value: int) -> None: ...
    draw_info_1: DrawInfo1
    gparam: GParam
    unk_struct_8: UnkPartStruct8
    tile_load_config: TileLoadConfig

class ConnectCollisionPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def collision(self) -> Optional[CollisionPart]: ...
    @collision.setter
    def collision(self, value: Optional[CollisionPart]) -> None: ...
    @property
    def connected_map_id(self) -> tuple[int, int, int, int]: ...
    @connected_map_id.setter
    def connected_map_id(self, value: tuple[int, int, int, int]) -> None: ...
    @property
    def s_unk_08(self) -> int: ...
    @s_unk_08.setter
    def s_unk_08(self, value: int) -> None: ...
    @property
    def s_unk_09(self) -> bool: ...
    @s_unk_09.setter
    def s_unk_09(self, value: bool) -> None: ...
    @property
    def s_unk_0a(self) -> int: ...
    @s_unk_0a.setter
    def s_unk_0a(self, value: int) -> None: ...
    @property
    def s_unk_0b(self) -> bool: ...
    @s_unk_0b.setter
    def s_unk_0b(self, value: bool) -> None: ...
    draw_info_1: DrawInfo1
    draw_info_2: DrawInfo2
    unk_struct_8: UnkPartStruct8
    tile_load_config: TileLoadConfig
    unk_struct_11: UnkPartStruct11

class AssetPart(Part):
    def __init__(self, name: str = ...) -> None: ...
    @property
    def s_unk_02(self) -> int: ...
    @s_unk_02.setter
    def s_unk_02(self, value: int) -> None: ...
    @property
    def s_unk_10(self) -> int: ...
    @s_unk_10.setter
    def s_unk_10(self, value: int) -> None: ...
    @property
    def s_unk_11(self) -> bool: ...
    @s_unk_11.setter
    def s_unk_11(self, value: bool) -> None: ...
    @property
    def s_unk_12(self) -> int: ...
    @s_unk_12.setter
    def s_unk_12(self, value: int) -> None: ...
    @property
    def sfx_param_relative_id(self) -> int: ...
    @sfx_param_relative_id.setter
    def sfx_param_relative_id(self, value: int) -> None: ...
    @property
    def s_unk_1e(self) -> int: ...
    @s_unk_1e.setter
    def s_unk_1e(self, value: int) -> None: ...
    @property
    def s_unk_24(self) -> int: ...
    @s_unk_24.setter
    def s_unk_24(self, value: int) -> None: ...
    @property
    def s_unk_28(self) -> int: ...
    @s_unk_28.setter
    def s_unk_28(self, value: int) -> None: ...
    @property
    def s_unk_30(self) -> int: ...
    @s_unk_30.setter
    def s_unk_30(self, value: int) -> None: ...
    @property
    def s_unk_34(self) -> int: ...
    @s_unk_34.setter
    def s_unk_34(self, value: int) -> None: ...
    def get_draw_parent_part(self, index: int) -> Optional[Part]: ...
    def set_draw_parent_part(self, index: int, part: Optional[Part]) -> None: ...
    @property
    def s_unk_50(self) -> bool: ...
    @s_unk_50.setter
    def s_unk_50(self, value: bool) -> None: ...
    @property
    def s_unk_51(self) -> int: ...
    @s_unk_51.setter
    def s_unk_51(self, value: int) -> None: ...
    @property
    def s_unk_53(self) -> int: ...
    @s_unk_53.setter
    def s_unk_53(self, value: int) -> None: ...
    @property
    def s_unk_54(self) -> int: ...
    @s_unk_54.setter
    def s_unk_54(self, value: int) -> None: ...
    @property
    def s_unk_58(self) -> int: ...
    @s_unk_58.setter
    def s_unk_58(self, value: int) -> None: ...
    @property
    def s_unk_5c(self) -> int: ...
    @s_unk_5c.setter
    def s_unk_5c(self, value: int) -> None: ...
    @property
    def s_unk_60(self) -> int: ...
    @s_unk_60.setter
    def s_unk_60(self, value: int) -> None: ...
    @property
    def s_unk_64(self) -> int: ...
    @s_unk_64.setter
    def s_unk_64(self, value: int) -> None: ...
    draw_info_1: DrawInfo1
    draw_info_2: DrawInfo2
    gparam: GParam
    grass_config: GrassConfig
    unk_struct_8: UnkPartStruct8
    unk_struct_9: UnkPartStruct9
    tile_load_config: TileLoadConfig
    unk_struct_11: UnkPartStruct11
    extra_data_1: ExtraAssetData1
    extra_data_2: ExtraAssetData2
    extra_data_3: ExtraAssetData3
    extra_data_4: ExtraAssetData4

# ── Entry Params ─────────────────────────────────────────────────────────

class ModelParam:
    @property
    def version(self) -> int: ...
    def get_all_entries(self) -> list[Model]: ...
    def __len__(self) -> int: ...
    def add_entry(self, entry: Model) -> None: ...
    def remove_entry(self, entry: Model) -> None: ...

class EventParam:
    @property
    def version(self) -> int: ...
    def get_all_entries(self) -> list[Event]: ...
    def __len__(self) -> int: ...
    def add_entry(self, entry: Event) -> None: ...
    def remove_entry(self, entry: Event) -> None: ...

class RegionParam:
    @property
    def version(self) -> int: ...
    def get_all_entries(self) -> list[Region]: ...
    def __len__(self) -> int: ...
    def add_entry(self, entry: Region) -> None: ...
    def remove_entry(self, entry: Region) -> None: ...

class RouteParam:
    @property
    def version(self) -> int: ...
    def get_all_entries(self) -> list[Route]: ...
    def __len__(self) -> int: ...
    def add_entry(self, entry: Route) -> None: ...
    def remove_entry(self, entry: Route) -> None: ...

class PartParam:
    @property
    def version(self) -> int: ...
    def get_all_entries(self) -> list[Part]: ...
    def __len__(self) -> int: ...
    def add_entry(self, entry: Part) -> None: ...
    def remove_entry(self, entry: Part) -> None: ...

# ── MSB ──────────────────────────────────────────────────────────────────

class MSB:
    def __init__(self) -> None: ...
    @property
    def model_param(self) -> ModelParam: ...
    @property
    def event_param(self) -> EventParam: ...
    @property
    def region_param(self) -> RegionParam: ...
    @property
    def route_param(self) -> RouteParam: ...
    @property
    def part_param(self) -> PartParam: ...
    @property
    def models(self) -> list[Model]: ...
    @property
    def events(self) -> list[Event]: ...
    @property
    def regions(self) -> list[Region]: ...
    @property
    def routes(self) -> list[Route]: ...
    @property
    def parts(self) -> list[Part]: ...
    @staticmethod
    def from_bytes(data: bytes) -> MSB: ...
    def to_bytes(self, dcx_type: int = 0) -> bytes: ...
    @staticmethod
    def from_path(path: Union[str, PathLike]) -> MSB: ...
    def write_to_path(self, path: Union[str, PathLike], dcx_type: int = 0) -> None: ...
    def __repr__(self) -> str: ...

