// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>

namespace Firelink::Havok
{

struct Ptr;  // cross-folder forward declaration
struct _bool;  // cross-folder forward declaration
struct hkHashMap;  // cross-folder forward declaration
struct hkReflectDetailOpaque;  // cross-folder forward declaration
struct hkbBlendingTransitionEffect;  // cross-folder forward declaration
struct hkbCustomIdSelector;  // cross-folder forward declaration
struct hkbEvent;  // cross-folder forward declaration
struct hkbGenerator;  // cross-folder forward declaration
struct hkbModifier;  // cross-folder forward declaration

/// Havok type "CustomLookAtTwistModifier::TwistParam"  (Python class: CustomLookAtTwistModifierTwistParam)
/// byte_size=24, alignment=4
struct CustomLookAtTwistModifierTwistParam
{
    int16_t startBoneIndex{};  // offset 0
    int16_t endBoneIndex{};  // offset 2
    float targetRotationRate{};  // offset 4
    float newTargetGain{};  // offset 8
    float onGain{};  // offset 12
    float offGain{};  // offset 16
    int8_t gainStateX{};  // offset 20 [not serialized]
    int8_t gainStateY{};  // offset 21 [not serialized]
};
static_assert(sizeof(CustomLookAtTwistModifierTwistParam) == 24,
              "Layout mismatch for CustomLookAtTwistModifierTwistParam");

/// Havok type "CustomLookAtTwistModifier"
/// byte_size=208, alignment=8
struct CustomLookAtTwistModifier : hkbModifier
{
    int32_t ModifierID{};  // offset 104
    int8_t rotationAxisType{};  // offset 108
    int32_t SensingDummyPoly{};  // offset 112
    std::vector<CustomLookAtTwistModifierTwistParam> twistParam;  // offset 120
    float UpLimitAngle{};  // offset 136
    float DownLimitAngle{};  // offset 140
    float RightLimitAngle{};  // offset 144
    float LeftLimitAngle{};  // offset 148
    float UpMinimumAngle{};  // offset 152
    float DownMinimumAngle{};  // offset 156
    float RightMinimumAngle{};  // offset 160
    float LeftMinimumAngle{};  // offset 164
    int16_t SensingAngle{};  // offset 168
    int8_t setAngleMethod{};  // offset 170
    bool isAdditive{};  // offset 171
    std::vector<hkReflectDetailOpaque> twistModifierXArray;  // offset 176 [not serialized]
    std::vector<hkReflectDetailOpaque> twistModifierYArray;  // offset 192 [not serialized]
};

/// Havok type "CustomLookAtTwistModifier::GainState"  (Python class: CustomLookAtTwistModifierGainState)
/// byte_size=4, alignment=4
using CustomLookAtTwistModifierGainState = int32_t;  // Havok enum/alias

/// Havok type "CustomLookAtTwistModifier::MultiRotationAxisType"  (Python class: CustomLookAtTwistModifierMultiRotationAxisType)
/// byte_size=4, alignment=4
using CustomLookAtTwistModifierMultiRotationAxisType = int32_t;  // Havok enum/alias

/// Havok type "CustomLookAtTwistModifier::SetAngleMethod"  (Python class: CustomLookAtTwistModifierSetAngleMethod)
/// byte_size=4, alignment=4
using CustomLookAtTwistModifierSetAngleMethod = int32_t;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator"
/// byte_size=280, alignment=8
struct CustomManualSelectorGenerator : hkbGenerator
{
    std::vector<Ptr> generators;  // offset 152
    int32_t offsetType{};  // offset 168
    int32_t animId{};  // offset 172
    int32_t animeEndEventType{};  // offset 176
    bool enableScript{};  // offset 180
    bool enableTae{};  // offset 181
    uint8_t changeTypeOfSelectedIndexAfterActivate{};  // offset 182
    Ptr generatorChangedTransitionEffect;  // offset 184
    int32_t checkAnimEndSlotNo{};  // offset 192
    uint8_t replanningAI{};  // offset 196
    uint8_t rideSync{};  // offset 197
    hkbEvent endEvent;  // offset 200 [not serialized]
    float preLocalTime{};  // offset 224 [not serialized]
    float localTime{};  // offset 228 [not serialized]
    float animeDuration{};  // offset 232 [not serialized]
    int32_t argTaeId{};  // offset 236 [not serialized]
    std::shared_ptr<hkReflectDetailOpaque> scriptGenerator;  // offset 240 [not serialized]
    int32_t stateId{};  // offset 248 [not serialized]
    bool isFirstUpdate{};  // offset 252 [not serialized]
    bool isAnimTest{};  // offset 253 [not serialized]
    bool isSelfTransition{};  // offset 254 [not serialized]
    int16_t currentGeneratorIndex{};  // offset 256 [not serialized]
    int16_t generatorIndexAtActivate{};  // offset 258 [not serialized]
    std::vector<hkReflectDetailOpaque> activeTransitions;  // offset 264 [not serialized]
};

/// Havok type "CustomManualSelectorGenerator::AnimeEndEventType"  (Python class: CustomManualSelectorGeneratorAnimeEndEventType)
/// byte_size=4, alignment=4
using CustomManualSelectorGeneratorAnimeEndEventType = int32_t;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::ChangeTypeOfSelectedIndexAfterActivate"  (Python class: CustomManualSelectorGeneratorChangeTypeOfSelectedIndexAfterActivate)
/// byte_size=4, alignment=4
using CustomManualSelectorGeneratorChangeTypeOfSelectedIndexAfterActivate = int32_t;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::OffsetType"  (Python class: CustomManualSelectorGeneratorOffsetType)
/// byte_size=4, alignment=4
using CustomManualSelectorGeneratorOffsetType = int32_t;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::ReplanningAI"  (Python class: CustomManualSelectorGeneratorReplanningAI)
/// byte_size=4, alignment=4
using CustomManualSelectorGeneratorReplanningAI = int32_t;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::RideSync"  (Python class: CustomManualSelectorGeneratorRideSync)
/// byte_size=4, alignment=4
using CustomManualSelectorGeneratorRideSync = int32_t;  // Havok enum/alias

/// Havok type "CustomPreDeleteIndexSelector"
/// byte_size=24, alignment=8
struct CustomPreDeleteIndexSelector : hkbCustomIdSelector
{
};
static_assert(sizeof(CustomPreDeleteIndexSelector) == 24,
              "Layout mismatch for CustomPreDeleteIndexSelector");

/// Havok type "CustomTransitionEffect"
/// byte_size=368, alignment=16
struct CustomTransitionEffect : hkbBlendingTransitionEffect
{
    float durationBackup{};  // offset 352 [not serialized]
    bool calcDuration{};  // offset 356 [not serialized]
};
static_assert(sizeof(CustomTransitionEffect) == 368,
              "Layout mismatch for CustomTransitionEffect");

/// Havok type "hkAabb"
/// byte_size=32, alignment=16
struct hkAabb
{
    hkVector4 min{};  // offset 0
    hkVector4 max{};  // offset 16
};
static_assert(sizeof(hkAabb) == 32,
              "Layout mismatch for hkAabb");

/// Havok type "hkAssetRefPtr"
/// byte_size=8, alignment=8
struct hkAssetRefPtr
{
    Ptr ptr;  // offset 0
};

/// Havok type "hkBitFieldStorage"
/// byte_size=24, alignment=8
struct hkBitFieldStorage
{
    std::vector<uint32_t> words;  // offset 0
    int32_t numBits{};  // offset 16
};

/// Havok type "hkBitFieldBase"
/// byte_size=24, alignment=8
struct hkBitFieldBase
{
    hkBitFieldStorage storage;  // offset 0
};

/// Havok type "hkBitField"
/// byte_size=24, alignment=8
struct hkBitField : hkBitFieldBase
{
};
static_assert(sizeof(hkBitField) == 24,
              "Layout mismatch for hkBitField");

/// Havok type "hkPackedVector3"
/// byte_size=8, alignment=8
struct hkPackedVector3
{
    std::array<int16_t, 4> values;  // offset 0
};
static_assert(sizeof(hkPackedVector3) == 8,
              "Layout mismatch for hkPackedVector3");

/// Havok type "hkCompressedMassProperties"
/// byte_size=32, alignment=12296
struct hkCompressedMassProperties
{
    hkPackedVector3 centerOfMass;  // offset 0
    hkPackedVector3 inertia;  // offset 8
    std::array<int16_t, 4> majorAxisSpace;  // offset 16
    float mass{};  // offset 24
    float volume{};  // offset 28
};

/// Havok type "hkDefaultPropertyBag"
/// byte_size=72, alignment=8
struct hkDefaultPropertyBag
{
    hkHashMap propertyMap;  // offset 0
    hkHashMap transientPropertyMap;  // offset 32 [not serialized]
    _bool locked;  // offset 64 [not serialized]
};

/// Havok type "hkHandle"
/// byte_size=4, alignment=4
struct hkHandle
{
    uint32_t value{};  // offset 0
};
static_assert(sizeof(hkHandle) == 4,
              "Layout mismatch for hkHandle");

/// Havok type "hkLocalFrame"
/// byte_size=24, alignment=8
struct hkLocalFrame : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkLocalFrame";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};

/// Havok type "hkMeshBoneIndexMapping"
/// byte_size=16, alignment=8
struct hkMeshBoneIndexMapping
{
    std::vector<int16_t> mapping;  // offset 0
};

/// Havok type "hkPropertyFlags::Enum"  (Python class: hkPropertyFlagsEnum)
/// byte_size=4, alignment=4
using hkPropertyFlagsEnum = int32_t;  // Havok enum/alias

/// Havok type "hkRefCountedProperties::Entry"  (Python class: hkRefCountedPropertiesEntry)
/// byte_size=16, alignment=8
struct hkRefCountedPropertiesEntry
{
    std::shared_ptr<hkReferencedObject> object;  // offset 0
    uint16_t key{};  // offset 8
    uint16_t flags{};  // offset 10
};

/// Havok type "hkRefCountedProperties"
/// byte_size=40, alignment=8
struct hkRefCountedProperties : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkRefCountedProperties";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkRefCountedPropertiesEntry> entries;  // offset 24
};

/// Havok type "hkRootLevelContainer::NamedVariant"  (Python class: hkRootLevelContainerNamedVariant)
/// byte_size=24, alignment=8
struct hkRootLevelContainerNamedVariant
{
    std::string name;  // offset 0
    std::string className;  // offset 8
    std::shared_ptr<hkReferencedObject> variant;  // offset 16
};

/// Havok type "hkRootLevelContainer"
/// byte_size=16, alignment=8
struct hkRootLevelContainer
{
    std::vector<hkRootLevelContainerNamedVariant> namedVariants;  // offset 0
};

// Registers all deserializers for this type set.
// Call after constructing TagFileUnpacker (or from TagFileUnpacker::RegisterDispatch).
class TagFileUnpacker;
void RegisterBaseDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok