// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>

namespace Firelink::Havok
{

struct Ptr;  // cross-folder forward declaration
struct hkBitField;  // cross-folder forward declaration
struct hkHandle;  // cross-folder forward declaration
struct hkPackedVector3;  // cross-folder forward declaration

/// Havok type "hclAction"
/// byte_size=24, alignment=8
struct hclAction : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclAction";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};

/// Havok type "hclConstraintSet"
/// byte_size=40, alignment=8
struct hclConstraintSet : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    hkHandle constraintId;  // offset 32
    uint32_t type{};  // offset 36 [not serialized]
};

/// Havok type "hclBendStiffnessConstraintSet::Link"  (Python class: hclBendStiffnessConstraintSetLink)
/// byte_size=32, alignment=4
struct hclBendStiffnessConstraintSetLink
{
    float weightA{};  // offset 0
    float weightB{};  // offset 4
    float weightC{};  // offset 8
    float weightD{};  // offset 12
    float bendStiffness{};  // offset 16
    float restCurvature{};  // offset 20
    uint16_t particleA{};  // offset 24
    uint16_t particleB{};  // offset 26
    uint16_t particleC{};  // offset 28
    uint16_t particleD{};  // offset 30
};
static_assert(sizeof(hclBendStiffnessConstraintSetLink) == 32,
              "Layout mismatch for hclBendStiffnessConstraintSetLink");

/// Havok type "hclBendStiffnessConstraintSet"
/// byte_size=64, alignment=8
struct hclBendStiffnessConstraintSet : hclConstraintSet
{
    static constexpr std::string_view TypeName = "hclBendStiffnessConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclBendStiffnessConstraintSetLink> links;  // offset 40
    float maxRestPoseHeightSq{};  // offset 56
    bool clampBendStiffness{};  // offset 60
    bool useRestPoseConfig{};  // offset 61
};

/// Havok type "hclBlendSomeVerticesOperator::BlendWeightType"  (Python class: hclBlendSomeVerticesOperatorBlendWeightType)
/// byte_size=4, alignment=4
using hclBlendSomeVerticesOperatorBlendWeightType = int32_t;  // Havok enum/alias

/// Havok type "hclBoneSpaceDeformer::FourBlendEntryBlock"  (Python class: hclBoneSpaceDeformerFourBlendEntryBlock)
/// byte_size=48, alignment=2
struct hclBoneSpaceDeformerFourBlendEntryBlock
{
    std::array<uint16_t, 4> vertexIndices;  // offset 0
    std::array<uint16_t, 16> boneIndices;  // offset 8
    std::array<uint8_t, 8> padding;  // offset 40 [not serialized]
};
static_assert(sizeof(hclBoneSpaceDeformerFourBlendEntryBlock) == 48,
              "Layout mismatch for hclBoneSpaceDeformerFourBlendEntryBlock");

/// Havok type "hclBoneSpaceDeformer::ThreeBlendEntryBlock"  (Python class: hclBoneSpaceDeformerThreeBlendEntryBlock)
/// byte_size=48, alignment=2
struct hclBoneSpaceDeformerThreeBlendEntryBlock
{
    std::array<uint16_t, 5> vertexIndices;  // offset 0
    std::array<uint16_t, 15> boneIndices;  // offset 10
    std::array<uint8_t, 8> padding;  // offset 40 [not serialized]
};
static_assert(sizeof(hclBoneSpaceDeformerThreeBlendEntryBlock) == 48,
              "Layout mismatch for hclBoneSpaceDeformerThreeBlendEntryBlock");

/// Havok type "hclBoneSpaceDeformer::TwoBlendEntryBlock"  (Python class: hclBoneSpaceDeformerTwoBlendEntryBlock)
/// byte_size=48, alignment=2
struct hclBoneSpaceDeformerTwoBlendEntryBlock
{
    std::array<uint16_t, 8> vertexIndices;  // offset 0
    std::array<uint16_t, 16> boneIndices;  // offset 16
};
static_assert(sizeof(hclBoneSpaceDeformerTwoBlendEntryBlock) == 48,
              "Layout mismatch for hclBoneSpaceDeformerTwoBlendEntryBlock");

/// Havok type "hclBoneSpaceDeformer::OneBlendEntryBlock"  (Python class: hclBoneSpaceDeformerOneBlendEntryBlock)
/// byte_size=64, alignment=2
struct hclBoneSpaceDeformerOneBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 16> boneIndices;  // offset 32
};
static_assert(sizeof(hclBoneSpaceDeformerOneBlendEntryBlock) == 64,
              "Layout mismatch for hclBoneSpaceDeformerOneBlendEntryBlock");

/// Havok type "hclBoneSpaceDeformer"
/// byte_size=88, alignment=8
struct hclBoneSpaceDeformer
{
    std::vector<hclBoneSpaceDeformerFourBlendEntryBlock> fourBlendEntries;  // offset 0
    std::vector<hclBoneSpaceDeformerThreeBlendEntryBlock> threeBlendEntries;  // offset 16
    std::vector<hclBoneSpaceDeformerTwoBlendEntryBlock> twoBlendEntries;  // offset 32
    std::vector<hclBoneSpaceDeformerOneBlendEntryBlock> oneBlendEntries;  // offset 48
    std::vector<uint8_t> controlBytes;  // offset 64
    uint16_t startVertexIndex{};  // offset 80
    uint16_t endVertexIndex{};  // offset 82
    bool partialWrite{};  // offset 84
};

/// Havok type "hclBoneSpaceDeformer::LocalBlockP"  (Python class: hclBoneSpaceDeformerLocalBlockP)
/// byte_size=256, alignment=16
struct hclBoneSpaceDeformerLocalBlockP
{
    std::array<hkVector4, 16> localPosition;  // offset 0
};
static_assert(sizeof(hclBoneSpaceDeformerLocalBlockP) == 256,
              "Layout mismatch for hclBoneSpaceDeformerLocalBlockP");

/// Havok type "hclBoneSpaceDeformer::LocalBlockUnpackedP"  (Python class: hclBoneSpaceDeformerLocalBlockUnpackedP)
/// byte_size=256, alignment=16
struct hclBoneSpaceDeformerLocalBlockUnpackedP
{
    std::array<hkVector4, 16> localPosition;  // offset 0
};
static_assert(sizeof(hclBoneSpaceDeformerLocalBlockUnpackedP) == 256,
              "Layout mismatch for hclBoneSpaceDeformerLocalBlockUnpackedP");

/// Havok type "hclBufferUsage"
/// byte_size=5, alignment=1
struct hclBufferUsage
{
    std::array<uint8_t, 4> perComponentFlags;  // offset 0
    bool trianglesRead{};  // offset 4
};
static_assert(sizeof(hclBufferUsage) == 5,
              "Layout mismatch for hclBufferUsage");

/// Havok type "hclClothState::BufferAccess"  (Python class: hclClothStateBufferAccess)
/// byte_size=16, alignment=4
struct hclClothStateBufferAccess
{
    uint32_t bufferIndex{};  // offset 0
    hclBufferUsage bufferUsage;  // offset 4
    uint32_t shadowBufferIndex{};  // offset 12
};
static_assert(sizeof(hclClothStateBufferAccess) == 16,
              "Layout mismatch for hclClothStateBufferAccess");

/// Havok type "hclTransformSetUsage::TransformTracker"  (Python class: hclTransformSetUsageTransformTracker)
/// byte_size=72, alignment=8
struct hclTransformSetUsageTransformTracker
{
    hkBitField read;  // offset 0
    hkBitField readBeforeWrite;  // offset 24
    hkBitField written;  // offset 48
};

/// Havok type "hclTransformSetUsage"
/// byte_size=24, alignment=8
struct hclTransformSetUsage
{
    std::array<uint8_t, 2> perComponentFlags;  // offset 0
    std::vector<hclTransformSetUsageTransformTracker> perComponentTransformTrackers;  // offset 8
};

/// Havok type "hclClothState::TransformSetAccess"  (Python class: hclClothStateTransformSetAccess)
/// byte_size=32, alignment=8
struct hclClothStateTransformSetAccess
{
    uint32_t transformSetIndex{};  // offset 0
    hclTransformSetUsage transformSetUsage;  // offset 8
};

/// Havok type "hclOperator"
/// byte_size=72, alignment=8
struct hclOperator : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    uint32_t operatorID{};  // offset 32
    uint32_t type{};  // offset 36 [not serialized]
    std::vector<hclClothStateBufferAccess> usedBuffers;  // offset 40
    std::vector<hclClothStateTransformSetAccess> usedTransformSets;  // offset 56
};

/// Havok type "hclBoneSpaceMeshMeshDeformOperator"
/// byte_size=192, alignment=8
struct hclBoneSpaceMeshMeshDeformOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclBoneSpaceMeshMeshDeformOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t inputBufferIdx{};  // offset 72
    uint32_t outputBufferIdx{};  // offset 76
    uint32_t scaleNormalBehaviour{};  // offset 80
    std::vector<uint16_t> inputTrianglesSubset;  // offset 88
    hclBoneSpaceDeformer boneSpaceDeformer;  // offset 104
};

/// Havok type "hclBoneSpaceMeshMeshDeformOperator::ScaleNormalBehaviour"  (Python class: hclBoneSpaceMeshMeshDeformOperatorScaleNormalBehaviour)
/// byte_size=4, alignment=4
using hclBoneSpaceMeshMeshDeformOperatorScaleNormalBehaviour = int32_t;  // Havok enum/alias

/// Havok type "hclBoneSpaceMeshMeshDeformPOperator"
/// byte_size=224, alignment=8
struct hclBoneSpaceMeshMeshDeformPOperator : hclBoneSpaceMeshMeshDeformOperator
{
    static constexpr std::string_view TypeName = "hclBoneSpaceMeshMeshDeformPOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclBoneSpaceDeformerLocalBlockP> localPs;  // offset 192
    std::vector<hclBoneSpaceDeformerLocalBlockUnpackedP> localUnpackedPs;  // offset 208
};

/// Havok type "hclBufferLayout::BufferElement"  (Python class: hclBufferLayoutBufferElement)
/// byte_size=4, alignment=1
struct hclBufferLayoutBufferElement
{
    uint8_t vectorConversion{};  // offset 0
    uint8_t vectorSize{};  // offset 1
    uint8_t slotId{};  // offset 2
    uint8_t slotStart{};  // offset 3
};
static_assert(sizeof(hclBufferLayoutBufferElement) == 4,
              "Layout mismatch for hclBufferLayoutBufferElement");

/// Havok type "hclBufferLayout::Slot"  (Python class: hclBufferLayoutSlot)
/// byte_size=2, alignment=1
struct hclBufferLayoutSlot
{
    uint8_t flags{};  // offset 0
    uint8_t stride{};  // offset 1
};
static_assert(sizeof(hclBufferLayoutSlot) == 2,
              "Layout mismatch for hclBufferLayoutSlot");

/// Havok type "hclBufferLayout"
/// byte_size=26, alignment=1
struct hclBufferLayout
{
    std::array<hclBufferLayoutBufferElement, 4> elementsLayout;  // offset 0
    std::array<hclBufferLayoutSlot, 4> slots;  // offset 16
    uint8_t numSlots{};  // offset 24
    uint8_t triangleFormat{};  // offset 25
};
static_assert(sizeof(hclBufferLayout) == 26,
              "Layout mismatch for hclBufferLayout");

/// Havok type "hclBufferDefinition"
/// byte_size=80, alignment=8
struct hclBufferDefinition : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclBufferDefinition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    int32_t type{};  // offset 32
    int32_t subType{};  // offset 36
    uint32_t numVertices{};  // offset 40
    uint32_t numTriangles{};  // offset 44
    hclBufferLayout bufferLayout;  // offset 48
};

/// Havok type "hclBufferLayout::SlotFlags"  (Python class: hclBufferLayoutSlotFlags)
/// byte_size=4, alignment=4
using hclBufferLayoutSlotFlags = int32_t;  // Havok enum/alias

/// Havok type "hclBufferLayout::TriangleFormat"  (Python class: hclBufferLayoutTriangleFormat)
/// byte_size=4, alignment=4
using hclBufferLayoutTriangleFormat = int32_t;  // Havok enum/alias

/// Havok type "hclShape"
/// byte_size=24, alignment=8
struct hclShape : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int32_t type{};  // offset 20 [not serialized]
};

/// Havok type "hclCapsuleShape"
/// byte_size=96, alignment=16
struct hclCapsuleShape : hclShape
{
    static constexpr std::string_view TypeName = "hclCapsuleShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkVector4 start{};  // offset 32
    hkVector4 end{};  // offset 48
    hkVector4 dir{};  // offset 64
    float radius{};  // offset 80
    float capLenSqrdInv{};  // offset 84
};

/// Havok type "hclClothContainer"
/// byte_size=56, alignment=8
struct hclClothContainer : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclClothContainer";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hclCollidable>> collidables;  // offset 24
    std::vector<std::shared_ptr<hclClothData>> clothDatas;  // offset 40
};

/// Havok type "hclClothData"
/// byte_size=152, alignment=8
struct hclClothData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclClothData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    std::vector<Ptr> simClothDatas;  // offset 32
    std::vector<Ptr> bufferDefinitions;  // offset 48
    std::vector<Ptr> transformSetDefinitions;  // offset 64
    std::vector<Ptr> operators;  // offset 80
    std::vector<Ptr> clothStateDatas;  // offset 96
    std::vector<Ptr> stateTransitions;  // offset 112
    std::vector<Ptr> actions;  // offset 128
    uint32_t targetPlatform{};  // offset 144
};

/// Havok type "hclClothData::Platform"  (Python class: hclClothDataPlatform)
/// byte_size=4, alignment=4
using hclClothDataPlatform = int32_t;  // Havok enum/alias

/// Havok type "hclClothState"
/// byte_size=104, alignment=8
struct hclClothState : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclClothState";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    std::vector<uint32_t> operators;  // offset 32
    std::vector<hclClothStateBufferAccess> usedBuffers;  // offset 48
    std::vector<hclClothStateTransformSetAccess> usedTransformSets;  // offset 64
    std::vector<uint32_t> usedSimCloths;  // offset 80
    Ptr dependencyGraph;  // offset 96
};

/// Havok type "hclCollidable"
/// byte_size=160, alignment=16
struct hclCollidable : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclCollidable";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkTransform transform{};  // offset 32
    hkVector4 linearVelocity{};  // offset 96
    hkVector4 angularVelocity{};  // offset 112
    uint64_t userData{};  // offset 128
    Ptr shape;  // offset 136
    std::string name;  // offset 144
    float pinchDetectionRadius{};  // offset 152
    int8_t pinchDetectionPriority{};  // offset 156
    bool pinchDetectionEnabled{};  // offset 157
    bool virtualCollisionPointCollisionEnabled{};  // offset 158
    bool enabled{};  // offset 159
};

/// Havok type "hclCopyVerticesOperator"
/// byte_size=96, alignment=8
struct hclCopyVerticesOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclCopyVerticesOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t inputBufferIdx{};  // offset 72
    uint32_t outputBufferIdx{};  // offset 76
    uint32_t numberOfVertices{};  // offset 80
    uint32_t startVertexIn{};  // offset 84
    uint32_t startVertexOut{};  // offset 88
    bool copyNormals{};  // offset 92
};

/// Havok type "hclGatherAllVerticesOperator"
/// byte_size=104, alignment=8
struct hclGatherAllVerticesOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclGatherAllVerticesOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<int16_t> vertexInputFromVertexOutput;  // offset 72
    uint32_t inputBufferIdx{};  // offset 88
    uint32_t outputBufferIdx{};  // offset 92
    bool gatherNormals{};  // offset 96
    bool partialGather{};  // offset 97
};

/// Havok type "hclRuntimeConversionInfo::SlotConversion"  (Python class: hclRuntimeConversionInfoSlotConversion)
/// byte_size=7, alignment=1
struct hclRuntimeConversionInfoSlotConversion
{
    std::array<uint8_t, 4> elements;  // offset 0
    uint8_t numElements{};  // offset 4
    uint8_t index{};  // offset 5
    bool partialWrite{};  // offset 6
};
static_assert(sizeof(hclRuntimeConversionInfoSlotConversion) == 7,
              "Layout mismatch for hclRuntimeConversionInfoSlotConversion");

/// Havok type "hclRuntimeConversionInfo::ElementConversion"  (Python class: hclRuntimeConversionInfoElementConversion)
/// byte_size=3, alignment=1
struct hclRuntimeConversionInfoElementConversion
{
    uint8_t index{};  // offset 0
    uint8_t offset{};  // offset 1
    uint8_t conversion{};  // offset 2
};
static_assert(sizeof(hclRuntimeConversionInfoElementConversion) == 3,
              "Layout mismatch for hclRuntimeConversionInfoElementConversion");

/// Havok type "hclRuntimeConversionInfo"
/// byte_size=42, alignment=1
struct hclRuntimeConversionInfo
{
    std::array<hclRuntimeConversionInfoSlotConversion, 4> slotConversions;  // offset 0
    std::array<hclRuntimeConversionInfoElementConversion, 4> elementConversions;  // offset 28
    uint8_t numSlotsConverted{};  // offset 40
    uint8_t numElementsConverted{};  // offset 41
};
static_assert(sizeof(hclRuntimeConversionInfo) == 42,
              "Layout mismatch for hclRuntimeConversionInfo");

/// Havok type "hclInputConvertOperator"
/// byte_size=128, alignment=8
struct hclInputConvertOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclInputConvertOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t userBufferIndex{};  // offset 72
    uint32_t shadowBufferIndex{};  // offset 76
    hclRuntimeConversionInfo conversionInfo;  // offset 80
};

/// Havok type "hclLocalRangeConstraintSet::LocalConstraint"  (Python class: hclLocalRangeConstraintSetLocalConstraint)
/// byte_size=16, alignment=4
struct hclLocalRangeConstraintSetLocalConstraint
{
    uint16_t particleIndex{};  // offset 0
    uint16_t referenceVertex{};  // offset 2
    float maximumDistance{};  // offset 4
    float maxNormalDistance{};  // offset 8
    float minNormalDistance{};  // offset 12
};
static_assert(sizeof(hclLocalRangeConstraintSetLocalConstraint) == 16,
              "Layout mismatch for hclLocalRangeConstraintSetLocalConstraint");

/// Havok type "hclLocalRangeConstraintSet"
/// byte_size=72, alignment=8
struct hclLocalRangeConstraintSet : hclConstraintSet
{
    static constexpr std::string_view TypeName = "hclLocalRangeConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclLocalRangeConstraintSetLocalConstraint> localConstraints;  // offset 40
    uint32_t referenceMeshBufferIdx{};  // offset 56
    float stiffness{};  // offset 60
    uint32_t shapeType{};  // offset 64
    bool applyNormalComponent{};  // offset 68
};

/// Havok type "hclLocalRangeConstraintSet::ShapeType"  (Python class: hclLocalRangeConstraintSetShapeType)
/// byte_size=4, alignment=4
using hclLocalRangeConstraintSetShapeType = int32_t;  // Havok enum/alias

/// Havok type "hclMoveParticlesOperator::VertexParticlePair"  (Python class: hclMoveParticlesOperatorVertexParticlePair)
/// byte_size=4, alignment=2
struct hclMoveParticlesOperatorVertexParticlePair
{
    uint16_t vertexIndex{};  // offset 0
    uint16_t particleIndex{};  // offset 2
};
static_assert(sizeof(hclMoveParticlesOperatorVertexParticlePair) == 4,
              "Layout mismatch for hclMoveParticlesOperatorVertexParticlePair");

/// Havok type "hclMoveParticlesOperator"
/// byte_size=96, alignment=8
struct hclMoveParticlesOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclMoveParticlesOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclMoveParticlesOperatorVertexParticlePair> vertexParticlePairs;  // offset 72
    uint32_t simClothIndex{};  // offset 88
    uint32_t refBufferIdx{};  // offset 92
};

/// Havok type "hclObjectSpaceDeformer::EightBlendEntryBlock"  (Python class: hclObjectSpaceDeformerEightBlendEntryBlock)
/// byte_size=544, alignment=2
struct hclObjectSpaceDeformerEightBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 128> boneIndices;  // offset 32
    std::array<uint16_t, 128> boneWeights;  // offset 288
};
static_assert(sizeof(hclObjectSpaceDeformerEightBlendEntryBlock) == 544,
              "Layout mismatch for hclObjectSpaceDeformerEightBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::SevenBlendEntryBlock"  (Python class: hclObjectSpaceDeformerSevenBlendEntryBlock)
/// byte_size=480, alignment=2
struct hclObjectSpaceDeformerSevenBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 112> boneIndices;  // offset 32
    std::array<uint16_t, 112> boneWeights;  // offset 256
};
static_assert(sizeof(hclObjectSpaceDeformerSevenBlendEntryBlock) == 480,
              "Layout mismatch for hclObjectSpaceDeformerSevenBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::SixBlendEntryBlock"  (Python class: hclObjectSpaceDeformerSixBlendEntryBlock)
/// byte_size=416, alignment=2
struct hclObjectSpaceDeformerSixBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 96> boneIndices;  // offset 32
    std::array<uint16_t, 96> boneWeights;  // offset 224
};
static_assert(sizeof(hclObjectSpaceDeformerSixBlendEntryBlock) == 416,
              "Layout mismatch for hclObjectSpaceDeformerSixBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::FiveBlendEntryBlock"  (Python class: hclObjectSpaceDeformerFiveBlendEntryBlock)
/// byte_size=352, alignment=2
struct hclObjectSpaceDeformerFiveBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 80> boneIndices;  // offset 32
    std::array<uint16_t, 80> boneWeights;  // offset 192
};
static_assert(sizeof(hclObjectSpaceDeformerFiveBlendEntryBlock) == 352,
              "Layout mismatch for hclObjectSpaceDeformerFiveBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::FourBlendEntryBlock"  (Python class: hclObjectSpaceDeformerFourBlendEntryBlock)
/// byte_size=224, alignment=2
struct hclObjectSpaceDeformerFourBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 64> boneIndices;  // offset 32
    std::array<uint8_t, 64> boneWeights;  // offset 160
};
static_assert(sizeof(hclObjectSpaceDeformerFourBlendEntryBlock) == 224,
              "Layout mismatch for hclObjectSpaceDeformerFourBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::ThreeBlendEntryBlock"  (Python class: hclObjectSpaceDeformerThreeBlendEntryBlock)
/// byte_size=176, alignment=2
struct hclObjectSpaceDeformerThreeBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 48> boneIndices;  // offset 32
    std::array<uint8_t, 48> boneWeights;  // offset 128
};
static_assert(sizeof(hclObjectSpaceDeformerThreeBlendEntryBlock) == 176,
              "Layout mismatch for hclObjectSpaceDeformerThreeBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::TwoBlendEntryBlock"  (Python class: hclObjectSpaceDeformerTwoBlendEntryBlock)
/// byte_size=128, alignment=2
struct hclObjectSpaceDeformerTwoBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 32> boneIndices;  // offset 32
    std::array<uint8_t, 32> boneWeights;  // offset 96
};
static_assert(sizeof(hclObjectSpaceDeformerTwoBlendEntryBlock) == 128,
              "Layout mismatch for hclObjectSpaceDeformerTwoBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer::OneBlendEntryBlock"  (Python class: hclObjectSpaceDeformerOneBlendEntryBlock)
/// byte_size=64, alignment=2
struct hclObjectSpaceDeformerOneBlendEntryBlock
{
    std::array<uint16_t, 16> vertexIndices;  // offset 0
    std::array<uint16_t, 16> boneIndices;  // offset 32
};
static_assert(sizeof(hclObjectSpaceDeformerOneBlendEntryBlock) == 64,
              "Layout mismatch for hclObjectSpaceDeformerOneBlendEntryBlock");

/// Havok type "hclObjectSpaceDeformer"
/// byte_size=152, alignment=8
struct hclObjectSpaceDeformer
{
    std::vector<hclObjectSpaceDeformerEightBlendEntryBlock> eightBlendEntries;  // offset 0
    std::vector<hclObjectSpaceDeformerSevenBlendEntryBlock> sevenBlendEntries;  // offset 16
    std::vector<hclObjectSpaceDeformerSixBlendEntryBlock> sixBlendEntries;  // offset 32
    std::vector<hclObjectSpaceDeformerFiveBlendEntryBlock> fiveBlendEntries;  // offset 48
    std::vector<hclObjectSpaceDeformerFourBlendEntryBlock> fourBlendEntries;  // offset 64
    std::vector<hclObjectSpaceDeformerThreeBlendEntryBlock> threeBlendEntries;  // offset 80
    std::vector<hclObjectSpaceDeformerTwoBlendEntryBlock> twoBlendEntries;  // offset 96
    std::vector<hclObjectSpaceDeformerOneBlendEntryBlock> oneBlendEntries;  // offset 112
    std::vector<uint8_t> controlBytes;  // offset 128
    uint16_t startVertexIndex{};  // offset 144
    uint16_t endVertexIndex{};  // offset 146
    bool partialWrite{};  // offset 148
};

/// Havok type "hclObjectSpaceDeformer::LocalBlockP"  (Python class: hclObjectSpaceDeformerLocalBlockP)
/// byte_size=128, alignment=8
struct hclObjectSpaceDeformerLocalBlockP
{
    std::array<hkPackedVector3, 16> localPosition;  // offset 0
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockP) == 128,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockP");

/// Havok type "hclObjectSpaceDeformer::LocalBlockPN"  (Python class: hclObjectSpaceDeformerLocalBlockPN)
/// byte_size=256, alignment=8
struct hclObjectSpaceDeformerLocalBlockPN
{
    std::array<hkPackedVector3, 16> localPosition;  // offset 0
    std::array<hkPackedVector3, 16> localNormal;  // offset 128
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockPN) == 256,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockPN");

/// Havok type "hclObjectSpaceDeformer::LocalBlockPNT"  (Python class: hclObjectSpaceDeformerLocalBlockPNT)
/// byte_size=384, alignment=8
struct hclObjectSpaceDeformerLocalBlockPNT
{
    std::array<hkPackedVector3, 16> localPosition;  // offset 0
    std::array<hkPackedVector3, 16> localNormal;  // offset 128
    std::array<hkPackedVector3, 16> localTangent;  // offset 256
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockPNT) == 384,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockPNT");

/// Havok type "hclObjectSpaceDeformer::LocalBlockUnpackedP"  (Python class: hclObjectSpaceDeformerLocalBlockUnpackedP)
/// byte_size=256, alignment=16
struct hclObjectSpaceDeformerLocalBlockUnpackedP
{
    std::array<hkVector4, 16> localPosition;  // offset 0
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockUnpackedP) == 256,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockUnpackedP");

/// Havok type "hclObjectSpaceDeformer::LocalBlockUnpackedPN"  (Python class: hclObjectSpaceDeformerLocalBlockUnpackedPN)
/// byte_size=512, alignment=16
struct hclObjectSpaceDeformerLocalBlockUnpackedPN
{
    std::array<hkVector4, 16> localPosition;  // offset 0
    std::array<hkVector4, 16> localNormal;  // offset 256
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockUnpackedPN) == 512,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockUnpackedPN");

/// Havok type "hclObjectSpaceDeformer::LocalBlockUnpackedPNT"  (Python class: hclObjectSpaceDeformerLocalBlockUnpackedPNT)
/// byte_size=768, alignment=16
struct hclObjectSpaceDeformerLocalBlockUnpackedPNT
{
    std::array<hkVector4, 16> localPosition;  // offset 0
    std::array<hkVector4, 16> localNormal;  // offset 256
    std::array<hkVector4, 16> localTangent;  // offset 512
};
static_assert(sizeof(hclObjectSpaceDeformerLocalBlockUnpackedPNT) == 768,
              "Layout mismatch for hclObjectSpaceDeformerLocalBlockUnpackedPNT");

/// Havok type "hclObjectSpaceMeshMeshDeformOperator"
/// byte_size=280, alignment=8
struct hclObjectSpaceMeshMeshDeformOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclObjectSpaceMeshMeshDeformOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t inputBufferIdx{};  // offset 72
    uint32_t outputBufferIdx{};  // offset 76
    uint32_t scaleNormalBehaviour{};  // offset 80
    std::vector<uint16_t> inputTrianglesSubset;  // offset 88
    std::vector<hkMatrix4> triangleFromMeshTransforms;  // offset 104
    hclObjectSpaceDeformer objectSpaceDeformer;  // offset 120
    bool customSkinDeform{};  // offset 272
};

/// Havok type "hclObjectSpaceMeshMeshDeformOperator::ScaleNormalBehaviour"  (Python class: hclObjectSpaceMeshMeshDeformOperatorScaleNormalBehaviour)
/// byte_size=4, alignment=4
using hclObjectSpaceMeshMeshDeformOperatorScaleNormalBehaviour = int32_t;  // Havok enum/alias

/// Havok type "hclObjectSpaceMeshMeshDeformPOperator"
/// byte_size=312, alignment=8
struct hclObjectSpaceMeshMeshDeformPOperator : hclObjectSpaceMeshMeshDeformOperator
{
    static constexpr std::string_view TypeName = "hclObjectSpaceMeshMeshDeformPOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclObjectSpaceDeformerLocalBlockP> localPs;  // offset 280
    std::vector<hclObjectSpaceDeformerLocalBlockUnpackedP> localUnpackedPs;  // offset 296
};

/// Havok type "hclObjectSpaceSkinOperator"
/// byte_size=264, alignment=8
struct hclObjectSpaceSkinOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclObjectSpaceSkinOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkMatrix4> boneFromSkinMeshTransforms;  // offset 72
    std::vector<uint16_t> transformSubset;  // offset 88
    uint32_t outputBufferIndex{};  // offset 104
    uint32_t transformSetIndex{};  // offset 108
    hclObjectSpaceDeformer objectSpaceDeformer;  // offset 112
};

/// Havok type "hclObjectSpaceSkinPNOperator"
/// byte_size=296, alignment=8
struct hclObjectSpaceSkinPNOperator : hclObjectSpaceSkinOperator
{
    static constexpr std::string_view TypeName = "hclObjectSpaceSkinPNOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclObjectSpaceDeformerLocalBlockPN> localPNs;  // offset 264
    std::vector<hclObjectSpaceDeformerLocalBlockUnpackedPN> localUnpackedPNs;  // offset 280
};

/// Havok type "hclObjectSpaceSkinPNTOperator"
/// byte_size=296, alignment=8
struct hclObjectSpaceSkinPNTOperator : hclObjectSpaceSkinOperator
{
    static constexpr std::string_view TypeName = "hclObjectSpaceSkinPNTOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclObjectSpaceDeformerLocalBlockPNT> localPNTs;  // offset 264
    std::vector<hclObjectSpaceDeformerLocalBlockUnpackedPNT> localUnpackedPNTs;  // offset 280
};

/// Havok type "hclOutputConvertOperator"
/// byte_size=128, alignment=8
struct hclOutputConvertOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclOutputConvertOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t userBufferIndex{};  // offset 72
    uint32_t shadowBufferIndex{};  // offset 76
    hclRuntimeConversionInfo conversionInfo;  // offset 80
};

/// Havok type "hclRuntimeConversionInfo::VectorConversion"  (Python class: hclRuntimeConversionInfoVectorConversion)
/// byte_size=4, alignment=4
using hclRuntimeConversionInfoVectorConversion = int32_t;  // Havok enum/alias

/// Havok type "hclScratchBufferDefinition"
/// byte_size=104, alignment=8
struct hclScratchBufferDefinition : hclBufferDefinition
{
    static constexpr std::string_view TypeName = "hclScratchBufferDefinition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<uint16_t> triangleIndices;  // offset 80
    bool storeNormals{};  // offset 96
    bool storeTangentsAndBiTangents{};  // offset 97
};

/// Havok type "hclShadowBufferDefinition"
/// byte_size=104, alignment=8
struct hclShadowBufferDefinition : hclBufferDefinition
{
    static constexpr std::string_view TypeName = "hclShadowBufferDefinition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<uint16_t> triangleIndices;  // offset 80
    bool shadowPositions{};  // offset 96
    bool shadowNormals{};  // offset 97
    bool shadowTangents{};  // offset 98
    bool shadowBiTangents{};  // offset 99
};

/// Havok type "hclSimClothData::OverridableSimulationInfo"  (Python class: hclSimClothDataOverridableSimulationInfo)
/// byte_size=32, alignment=16
struct hclSimClothDataOverridableSimulationInfo
{
    hkVector4 gravity{};  // offset 0
    float globalDampingPerSecond{};  // offset 16
};
static_assert(sizeof(hclSimClothDataOverridableSimulationInfo) == 32,
              "Layout mismatch for hclSimClothDataOverridableSimulationInfo");

/// Havok type "hclSimClothData::ParticleData"  (Python class: hclSimClothDataParticleData)
/// byte_size=16, alignment=4
struct hclSimClothDataParticleData
{
    float mass{};  // offset 0
    float invMass{};  // offset 4
    float radius{};  // offset 8
    float friction{};  // offset 12
};
static_assert(sizeof(hclSimClothDataParticleData) == 16,
              "Layout mismatch for hclSimClothDataParticleData");

/// Havok type "hclSimClothData::CollidableTransformMap"  (Python class: hclSimClothDataCollidableTransformMap)
/// byte_size=40, alignment=8
struct hclSimClothDataCollidableTransformMap
{
    int32_t transformSetIndex{};  // offset 0
    std::vector<uint32_t> transformIndices;  // offset 8
    std::vector<hkMatrix4> offsets;  // offset 24
};

/// Havok type "hclSimClothData::TransferMotionData"  (Python class: hclSimClothDataTransferMotionData)
/// byte_size=48, alignment=4
struct hclSimClothDataTransferMotionData
{
    uint32_t transformSetIndex{};  // offset 0
    uint32_t transformIndex{};  // offset 4
    bool transferTranslationMotion{};  // offset 8
    float minTranslationSpeed{};  // offset 12
    float maxTranslationSpeed{};  // offset 16
    float minTranslationBlend{};  // offset 20
    float maxTranslationBlend{};  // offset 24
    bool transferRotationMotion{};  // offset 28
    float minRotationSpeed{};  // offset 32
    float maxRotationSpeed{};  // offset 36
    float minRotationBlend{};  // offset 40
    float maxRotationBlend{};  // offset 44
};
static_assert(sizeof(hclSimClothDataTransferMotionData) == 48,
              "Layout mismatch for hclSimClothDataTransferMotionData");

/// Havok type "hclSimClothData::LandscapeCollisionData"  (Python class: hclSimClothDataLandscapeCollisionData)
/// byte_size=24, alignment=4
struct hclSimClothDataLandscapeCollisionData
{
    float landscapeRadius{};  // offset 0
    bool enableStuckParticleDetection{};  // offset 4
    float stuckParticlesStretchFactorSq{};  // offset 8
    bool pinchDetectionEnabled{};  // offset 12
    int8_t pinchDetectionPriority{};  // offset 13
    float pinchDetectionRadius{};  // offset 16
    float collisionTolerance{};  // offset 20
};
static_assert(sizeof(hclSimClothDataLandscapeCollisionData) == 24,
              "Layout mismatch for hclSimClothDataLandscapeCollisionData");

/// Havok type "hclSimClothData::CollidablePinchingData"  (Python class: hclSimClothDataCollidablePinchingData)
/// byte_size=8, alignment=4
struct hclSimClothDataCollidablePinchingData
{
    bool pinchDetectionEnabled{};  // offset 0
    int8_t pinchDetectionPriority{};  // offset 1
    float pinchDetectionRadius{};  // offset 4
};
static_assert(sizeof(hclSimClothDataCollidablePinchingData) == 8,
              "Layout mismatch for hclSimClothDataCollidablePinchingData");

/// Havok type "hclVirtualCollisionPointsData::Block"  (Python class: hclVirtualCollisionPointsDataBlock)
/// byte_size=8, alignment=4
struct hclVirtualCollisionPointsDataBlock
{
    float safeDisplacementRadius{};  // offset 0
    uint16_t startingVCPIndex{};  // offset 4
    uint8_t numVCPs{};  // offset 6
};
static_assert(sizeof(hclVirtualCollisionPointsDataBlock) == 8,
              "Layout mismatch for hclVirtualCollisionPointsDataBlock");

/// Havok type "hclVirtualCollisionPointsData::BarycentricDictionaryEntry"  (Python class: hclVirtualCollisionPointsDataBarycentricDictionaryEntry)
/// byte_size=4, alignment=2
struct hclVirtualCollisionPointsDataBarycentricDictionaryEntry
{
    uint16_t startingBarycentricIndex{};  // offset 0
    uint8_t numBarycentrics{};  // offset 2
};
static_assert(sizeof(hclVirtualCollisionPointsDataBarycentricDictionaryEntry) == 4,
              "Layout mismatch for hclVirtualCollisionPointsDataBarycentricDictionaryEntry");

/// Havok type "hclVirtualCollisionPointsData::BarycentricPair"  (Python class: hclVirtualCollisionPointsDataBarycentricPair)
/// byte_size=8, alignment=4
struct hclVirtualCollisionPointsDataBarycentricPair
{
    float u{};  // offset 0
    float v{};  // offset 4
};
static_assert(sizeof(hclVirtualCollisionPointsDataBarycentricPair) == 8,
              "Layout mismatch for hclVirtualCollisionPointsDataBarycentricPair");

/// Havok type "hclVirtualCollisionPointsData::EdgeFanSection"  (Python class: hclVirtualCollisionPointsDataEdgeFanSection)
/// byte_size=4, alignment=2
struct hclVirtualCollisionPointsDataEdgeFanSection
{
    uint16_t oppositeRealParticleIndex{};  // offset 0
    uint16_t barycentricDictionaryIndex{};  // offset 2
};
static_assert(sizeof(hclVirtualCollisionPointsDataEdgeFanSection) == 4,
              "Layout mismatch for hclVirtualCollisionPointsDataEdgeFanSection");

/// Havok type "hclVirtualCollisionPointsData::EdgeFan"  (Python class: hclVirtualCollisionPointsDataEdgeFan)
/// byte_size=6, alignment=2
struct hclVirtualCollisionPointsDataEdgeFan
{
    uint16_t realParticleIndex{};  // offset 0
    uint16_t edgeStartIndex{};  // offset 2
    uint8_t numEdges{};  // offset 4
};
static_assert(sizeof(hclVirtualCollisionPointsDataEdgeFan) == 6,
              "Layout mismatch for hclVirtualCollisionPointsDataEdgeFan");

/// Havok type "hclVirtualCollisionPointsData::TriangleFanSection"  (Python class: hclVirtualCollisionPointsDataTriangleFanSection)
/// byte_size=6, alignment=2
struct hclVirtualCollisionPointsDataTriangleFanSection
{
    std::array<uint16_t, 2> oppositeRealParticleIndices;  // offset 0
    uint16_t barycentricDictionaryIndex{};  // offset 4
};
static_assert(sizeof(hclVirtualCollisionPointsDataTriangleFanSection) == 6,
              "Layout mismatch for hclVirtualCollisionPointsDataTriangleFanSection");

/// Havok type "hclVirtualCollisionPointsData::TriangleFan"  (Python class: hclVirtualCollisionPointsDataTriangleFan)
/// byte_size=6, alignment=2
struct hclVirtualCollisionPointsDataTriangleFan
{
    uint16_t realParticleIndex{};  // offset 0
    uint16_t vcpStartIndex{};  // offset 2
    uint8_t numTriangles{};  // offset 4
};
static_assert(sizeof(hclVirtualCollisionPointsDataTriangleFan) == 6,
              "Layout mismatch for hclVirtualCollisionPointsDataTriangleFan");

/// Havok type "hclVirtualCollisionPointsData::EdgeFanLandscape"  (Python class: hclVirtualCollisionPointsDataEdgeFanLandscape)
/// byte_size=8, alignment=2
struct hclVirtualCollisionPointsDataEdgeFanLandscape
{
    uint16_t realParticleIndex{};  // offset 0
    uint16_t edgeStartIndex{};  // offset 2
    uint16_t vcpStartIndex{};  // offset 4
    uint8_t numEdges{};  // offset 6
};
static_assert(sizeof(hclVirtualCollisionPointsDataEdgeFanLandscape) == 8,
              "Layout mismatch for hclVirtualCollisionPointsDataEdgeFanLandscape");

/// Havok type "hclVirtualCollisionPointsData::TriangleFanLandscape"  (Python class: hclVirtualCollisionPointsDataTriangleFanLandscape)
/// byte_size=8, alignment=2
struct hclVirtualCollisionPointsDataTriangleFanLandscape
{
    uint16_t realParticleIndex{};  // offset 0
    uint16_t triangleStartIndex{};  // offset 2
    uint16_t vcpStartIndex{};  // offset 4
    uint8_t numTriangles{};  // offset 6
};
static_assert(sizeof(hclVirtualCollisionPointsDataTriangleFanLandscape) == 8,
              "Layout mismatch for hclVirtualCollisionPointsDataTriangleFanLandscape");

/// Havok type "hclVirtualCollisionPointsData"
/// byte_size=304, alignment=8
struct hclVirtualCollisionPointsData
{
    std::vector<hclVirtualCollisionPointsDataBlock> blocks;  // offset 0
    uint16_t numVCPoints{};  // offset 16
    std::vector<uint16_t> landscapeParticlesBlockIndex;  // offset 24
    uint16_t numLandscapeVCPoints{};  // offset 40
    std::vector<float> edgeBarycentricsDictionary;  // offset 48
    std::vector<hclVirtualCollisionPointsDataBarycentricDictionaryEntry> edgeDictionaryEntries;  // offset 64
    std::vector<hclVirtualCollisionPointsDataBarycentricPair> triangleBarycentricsDictionary;  // offset 80
    std::vector<hclVirtualCollisionPointsDataBarycentricDictionaryEntry> triangleDictionaryEntries;  // offset 96
    std::vector<hclVirtualCollisionPointsDataEdgeFanSection> edges;  // offset 112
    std::vector<hclVirtualCollisionPointsDataEdgeFan> edgeFans;  // offset 128
    std::vector<hclVirtualCollisionPointsDataTriangleFanSection> triangles;  // offset 144
    std::vector<hclVirtualCollisionPointsDataTriangleFan> triangleFans;  // offset 160
    std::vector<hclVirtualCollisionPointsDataEdgeFanSection> edgesLandscape;  // offset 176
    std::vector<hclVirtualCollisionPointsDataEdgeFanLandscape> edgeFansLandscape;  // offset 192
    std::vector<hclVirtualCollisionPointsDataTriangleFanSection> trianglesLandscape;  // offset 208
    std::vector<hclVirtualCollisionPointsDataTriangleFanLandscape> triangleFansLandscape;  // offset 224
    std::vector<uint16_t> edgeFanIndices;  // offset 240
    std::vector<uint16_t> triangleFanIndices;  // offset 256
    std::vector<uint16_t> edgeFanIndicesLandscape;  // offset 272
    std::vector<uint16_t> triangleFanIndicesLandscape;  // offset 288
};

/// Havok type "hclSimClothData"
/// byte_size=736, alignment=16
struct hclSimClothData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclSimClothData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    hclSimClothDataOverridableSimulationInfo simulationInfo;  // offset 32
    std::vector<hclSimClothDataParticleData> particleDatas;  // offset 64
    std::vector<uint16_t> fixedParticles;  // offset 80
    bool doNormals{};  // offset 96
    std::vector<uint32_t> simOpIds;  // offset 104
    std::vector<Ptr> simClothPoses;  // offset 120
    std::vector<Ptr> staticConstraintSets;  // offset 136
    std::vector<Ptr> antiPinchConstraintSets;  // offset 152
    hclSimClothDataCollidableTransformMap collidableTransformMap;  // offset 168
    std::vector<Ptr> perInstanceCollidables;  // offset 208
    float maxParticleRadius{};  // offset 224
    std::vector<uint32_t> staticCollisionMasks;  // offset 232
    std::vector<Ptr> actions;  // offset 248
    float totalMass{};  // offset 264
    hclSimClothDataTransferMotionData transferMotionData;  // offset 268
    bool transferMotionEnabled{};  // offset 316
    bool landscapeCollisionEnabled{};  // offset 317
    hclSimClothDataLandscapeCollisionData landscapeCollisionData;  // offset 320
    uint32_t numLandscapeCollidableParticles{};  // offset 344
    std::vector<uint16_t> triangleIndices;  // offset 352
    std::vector<uint8_t> triangleFlips;  // offset 368
    bool pinchDetectionEnabled{};  // offset 384
    std::vector<bool> perParticlePinchDetectionEnabledFlags;  // offset 392
    std::vector<hclSimClothDataCollidablePinchingData> collidablePinchingDatas;  // offset 408
    uint16_t minPinchedParticleIndex{};  // offset 424
    uint16_t maxPinchedParticleIndex{};  // offset 426
    uint32_t maxCollisionPairs{};  // offset 428
    hclVirtualCollisionPointsData virtualCollisionPointsData;  // offset 432
};

/// Havok type "hclSimClothPose"
/// byte_size=48, alignment=8
struct hclSimClothPose : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclSimClothPose";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    std::vector<hkVector4> positions;  // offset 32
};

/// Havok type "hclSimpleMeshBoneDeformOperator::TriangleBonePair"  (Python class: hclSimpleMeshBoneDeformOperatorTriangleBonePair)
/// byte_size=4, alignment=2
struct hclSimpleMeshBoneDeformOperatorTriangleBonePair
{
    uint16_t boneOffset{};  // offset 0
    uint16_t triangleOffset{};  // offset 2
};
static_assert(sizeof(hclSimpleMeshBoneDeformOperatorTriangleBonePair) == 4,
              "Layout mismatch for hclSimpleMeshBoneDeformOperatorTriangleBonePair");

/// Havok type "hclSimpleMeshBoneDeformOperator"
/// byte_size=112, alignment=8
struct hclSimpleMeshBoneDeformOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclSimpleMeshBoneDeformOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t inputBufferIdx{};  // offset 72
    uint32_t outputTransformSetIdx{};  // offset 76
    std::vector<hclSimpleMeshBoneDeformOperatorTriangleBonePair> triangleBonePairs;  // offset 80
    std::vector<hkMatrix4> localBoneTransforms;  // offset 96
};

/// Havok type "hclSimulateOperator::Config"  (Python class: hclSimulateOperatorConfig)
/// byte_size=48, alignment=8
struct hclSimulateOperatorConfig
{
    std::string name;  // offset 0
    std::vector<int32_t> constraintExecution;  // offset 8
    std::vector<bool> instanceCollidablesUsed;  // offset 24
    uint8_t subSteps{};  // offset 40
    uint8_t numberOfSolveIterations{};  // offset 41
    bool useAllInstanceCollidables{};  // offset 42
    bool adaptConstraintStiffness{};  // offset 43
};

/// Havok type "hclSimulateOperator"
/// byte_size=96, alignment=8
struct hclSimulateOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclSimulateOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t simClothIndex{};  // offset 72
    std::vector<hclSimulateOperatorConfig> simulateOpConfigs;  // offset 80
};

/// Havok type "hclStandardLinkConstraintSet::Link"  (Python class: hclStandardLinkConstraintSetLink)
/// byte_size=12, alignment=4
struct hclStandardLinkConstraintSetLink
{
    uint16_t particleA{};  // offset 0
    uint16_t particleB{};  // offset 2
    float restLength{};  // offset 4
    float stiffness{};  // offset 8
};
static_assert(sizeof(hclStandardLinkConstraintSetLink) == 12,
              "Layout mismatch for hclStandardLinkConstraintSetLink");

/// Havok type "hclStandardLinkConstraintSet"
/// byte_size=56, alignment=8
struct hclStandardLinkConstraintSet : hclConstraintSet
{
    static constexpr std::string_view TypeName = "hclStandardLinkConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclStandardLinkConstraintSetLink> links;  // offset 40
};

/// Havok type "hclStateDependencyGraph::Branch"  (Python class: hclStateDependencyGraphBranch)
/// byte_size=56, alignment=8
struct hclStateDependencyGraphBranch
{
    int32_t branchId{};  // offset 0
    std::vector<int32_t> stateOperatorIndices;  // offset 8
    std::vector<int32_t> parentBranches;  // offset 24
    std::vector<int32_t> childBranches;  // offset 40
};

/// Havok type "hclStateDependencyGraph"
/// byte_size=96, alignment=8
struct hclStateDependencyGraph : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclStateDependencyGraph";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclStateDependencyGraphBranch> branches;  // offset 24
    std::vector<int32_t> rootBranchIds;  // offset 40
    std::vector<std::vector<int32_t>> children;  // offset 56
    std::vector<std::vector<int32_t>> parents;  // offset 72
    bool multiThreadable{};  // offset 88
};

/// Havok type "hclStateTransition::SimClothTransitionData"  (Python class: hclStateTransitionSimClothTransitionData)
/// byte_size=32, alignment=8
struct hclStateTransitionSimClothTransitionData
{
    bool isSimulated{};  // offset 0
    std::vector<hkHandle> transitionConstraints;  // offset 8
    uint32_t transitionType{};  // offset 24
};

/// Havok type "hclStateTransition::BlendOpTransitionData"  (Python class: hclStateTransitionBlendOpTransitionData)
/// byte_size=48, alignment=8
struct hclStateTransitionBlendOpTransitionData
{
    std::vector<int32_t> bufferASimCloths;  // offset 0
    std::vector<int32_t> bufferBSimCloths;  // offset 16
    uint32_t transitionType{};  // offset 32
    hk blendWeightType{};  // offset 36
    uint32_t blendOperatorId{};  // offset 40
};

/// Havok type "hclStateTransition::StateTransitionData"  (Python class: hclStateTransitionStateTransitionData)
/// byte_size=40, alignment=8
struct hclStateTransitionStateTransitionData
{
    std::vector<hclStateTransitionSimClothTransitionData> simClothTransitionData;  // offset 0
    std::vector<hclStateTransitionBlendOpTransitionData> blendOpTransitionData;  // offset 16
    bool simulatedState{};  // offset 32
    bool emptyState{};  // offset 33
};

/// Havok type "hclStateTransition"
/// byte_size=80, alignment=8
struct hclStateTransition : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclStateTransition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    std::vector<uint32_t> stateIds;  // offset 32
    std::vector<hclStateTransitionStateTransitionData> stateTransitionData;  // offset 48
    std::vector<std::vector<hkHandle>> simClothTransitionConstraints;  // offset 64
};

/// Havok type "hclStateTransition::TransitionType"  (Python class: hclStateTransitionTransitionType)
/// byte_size=4, alignment=4
using hclStateTransitionTransitionType = int32_t;  // Havok enum/alias

/// Havok type "hclStretchLinkConstraintSet::Link"  (Python class: hclStretchLinkConstraintSetLink)
/// byte_size=12, alignment=4
struct hclStretchLinkConstraintSetLink
{
    uint16_t particleA{};  // offset 0
    uint16_t particleB{};  // offset 2
    float restLength{};  // offset 4
    float stiffness{};  // offset 8
};
static_assert(sizeof(hclStretchLinkConstraintSetLink) == 12,
              "Layout mismatch for hclStretchLinkConstraintSetLink");

/// Havok type "hclStretchLinkConstraintSet"
/// byte_size=56, alignment=8
struct hclStretchLinkConstraintSet : hclConstraintSet
{
    static constexpr std::string_view TypeName = "hclStretchLinkConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclStretchLinkConstraintSetLink> links;  // offset 40
};

/// Havok type "hclTaperedCapsuleShape"
/// byte_size=176, alignment=16
struct hclTaperedCapsuleShape : hclShape
{
    static constexpr std::string_view TypeName = "hclTaperedCapsuleShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkVector4 small{};  // offset 32
    hkVector4 big{};  // offset 48
    hkVector4 coneApex{};  // offset 64
    hkVector4 coneAxis{};  // offset 80
    hkVector4 lVec{};  // offset 96
    hkVector4 dVec{};  // offset 112
    hkVector4 tanThetaVecNeg{};  // offset 128
    float smallRadius{};  // offset 144
    float bigRadius{};  // offset 148
    float l{};  // offset 152
    float d{};  // offset 156
    float cosTheta{};  // offset 160
    float sinTheta{};  // offset 164
    float tanTheta{};  // offset 168
    float tanThetaSqr{};  // offset 172
};

/// Havok type "hclTransformSetDefinition"
/// byte_size=40, alignment=8
struct hclTransformSetDefinition : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hclTransformSetDefinition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    int32_t type{};  // offset 32
    uint32_t numTransforms{};  // offset 36
};

/// Havok type "hclTransitionConstraintSet::PerParticle"  (Python class: hclTransitionConstraintSetPerParticle)
/// byte_size=16, alignment=4
struct hclTransitionConstraintSetPerParticle
{
    uint16_t particleIndex{};  // offset 0
    uint16_t referenceVertex{};  // offset 2
    float toAnimDelay{};  // offset 4
    float toSimDelay{};  // offset 8
    float toSimMaxDistance{};  // offset 12
};
static_assert(sizeof(hclTransitionConstraintSetPerParticle) == 16,
              "Layout mismatch for hclTransitionConstraintSetPerParticle");

/// Havok type "hclTransitionConstraintSet"
/// byte_size=80, alignment=8
struct hclTransitionConstraintSet : hclConstraintSet
{
    static constexpr std::string_view TypeName = "hclTransitionConstraintSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hclTransitionConstraintSetPerParticle> perParticleData;  // offset 40
    float toAnimPeriod{};  // offset 56
    float toAnimPlusDelayPeriod{};  // offset 60
    float toSimPeriod{};  // offset 64
    float toSimPlusDelayPeriod{};  // offset 68
    uint32_t referenceMeshBufferIdx{};  // offset 72
};

/// Havok type "hclUpdateAllVertexFramesOperator"
/// byte_size=184, alignment=8
struct hclUpdateAllVertexFramesOperator : hclOperator
{
    static constexpr std::string_view TypeName = "hclUpdateAllVertexFramesOperator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<uint16_t> vertToNormalID;  // offset 72
    std::vector<uint8_t> triangleFlips;  // offset 88
    std::vector<uint16_t> referenceVertices;  // offset 104
    std::vector<float> tangentEdgeCosAngle;  // offset 120
    std::vector<float> tangentEdgeSinAngle;  // offset 136
    std::vector<float> biTangentFlip;  // offset 152
    uint32_t bufferIdx{};  // offset 168
    uint32_t numUniqueNormalIDs{};  // offset 172
    bool updateNormals{};  // offset 176
    bool updateTangents{};  // offset 177
    bool updateBiTangents{};  // offset 178
};

// Registers all deserializers for this type set.
// Call after constructing TagFileUnpacker (or from TagFileUnpacker::RegisterDispatch).
class TagFileUnpacker;
void RegisterHclDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok