// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>

namespace Firelink::Havok
{

struct Ptr;  // cross-folder forward declaration
struct hkCompressedMassProperties;  // cross-folder forward declaration
struct hkFreeListArray;  // cross-folder forward declaration
struct hkHandle;  // cross-folder forward declaration
struct hkLocalFrame;  // cross-folder forward declaration
struct hkRefCountedProperties;  // cross-folder forward declaration
struct hkUFloat8;  // cross-folder forward declaration
struct hkVector4f;  // cross-folder forward declaration
struct hkaSkeleton;  // cross-folder forward declaration
struct hkpConstraintData;  // cross-folder forward declaration

/// Havok type "hknpShape"
/// byte_size=48, alignment=8
struct hknpShape : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint16_t flags{};  // offset 20
    uint8_t type{};  // offset 22
    uint8_t numShapeKeyBits{};  // offset 23
    uint8_t dispatchType{};  // offset 24
    float convexRadius{};  // offset 28
    uint64_t userData{};  // offset 32
    std::shared_ptr<hkRefCountedProperties> properties;  // offset 40
};

/// Havok type "hknpMassDistribution"
/// byte_size=48, alignment=16
struct hknpMassDistribution
{
    hkVector4 centerOfMassAndVolume{};  // offset 0
    hkQuaternion majorAxisSpace{};  // offset 16
    hkVector4 inertiaTensor{};  // offset 32
};
static_assert(sizeof(hknpMassDistribution) == 48,
              "Layout mismatch for hknpMassDistribution");

/// Havok type "hknpRefMassDistribution"
/// byte_size=80, alignment=16
struct hknpRefMassDistribution : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpRefMassDistribution";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hknpMassDistribution massDistribution;  // offset 32
};

/// Havok type "hknpDragProperties"
/// byte_size=192, alignment=16
struct hknpDragProperties
{
    std::array<hkVector4, 3> centerAndOffset;  // offset 0
    std::array<hkVector4, 6> angularEffectsAndArea;  // offset 48
    std::array<float, 12> armUVs;  // offset 144
};
static_assert(sizeof(hknpDragProperties) == 192,
              "Layout mismatch for hknpDragProperties");

/// Havok type "hknpRefDragProperties"
/// byte_size=224, alignment=16
struct hknpRefDragProperties : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpRefDragProperties";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hknpDragProperties dragProperties;  // offset 32
};

/// Havok type "hknpBodyId"
/// byte_size=4, alignment=4
struct hknpBodyId
{
    uint32_t serialAndIndex{};  // offset 0
};
static_assert(sizeof(hknpBodyId) == 4,
              "Layout mismatch for hknpBodyId");

/// Havok type "hknpBodyCinfo"
/// byte_size=176, alignment=16
struct hknpBodyCinfo
{
    std::shared_ptr<hknpShape> shape;  // offset 0
    int32_t flags{};  // offset 8
    int16_t collisionCntrl{};  // offset 12
    uint32_t collisionFilterInfo{};  // offset 16
    uint16_t materialId{};  // offset 20
    uint8_t qualityId{};  // offset 22
    std::string name;  // offset 24
    uint64_t userData{};  // offset 32
    uint8_t motionType{};  // offset 40
    hkVector4 position{};  // offset 48
    hkQuaternion orientation{};  // offset 64
    hkVector4 linearVelocity{};  // offset 80
    hkVector4 angularVelocity{};  // offset 96
    float mass{};  // offset 112
    std::shared_ptr<hknpRefMassDistribution> massDistribution;  // offset 120
    std::shared_ptr<hknpRefDragProperties> dragProperties;  // offset 128
    uint16_t motionPropertiesId{};  // offset 136
    hknpBodyId desiredBodyId;  // offset 140
    uint32_t motionId{};  // offset 144
    float collisionLookAheadDistance{};  // offset 148
    std::shared_ptr<hkLocalFrame> localFrame;  // offset 152
    int8_t activationPriority{};  // offset 160
};

/// Havok type "hknpManifoldType::Enum"  (Python class: hknpManifoldTypeEnum)
/// byte_size=4, alignment=4
using hknpManifoldTypeEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpBodyIntegrator"
/// byte_size=32, alignment=8
struct hknpBodyIntegrator : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpBodyIntegrator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t bodyFlagsForcingNormalCollisions{};  // offset 20
    hk typeForDynamicBodies{};  // offset 24
    hk typeForTriggers{};  // offset 28
};

/// Havok type "hknpMotionRangeBreachPolicy::Enum"  (Python class: hknpMotionRangeBreachPolicyEnum)
/// byte_size=4, alignment=4
using hknpMotionRangeBreachPolicyEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpBodyQuality"
/// byte_size=48, alignment=8
struct hknpBodyQuality : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpBodyQuality";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int32_t priority{};  // offset 20
    uint32_t supportedFlags{};  // offset 24
    uint32_t requestedFlags{};  // offset 28
    float contactCachingRelativeMovementThreshold{};  // offset 32
    hk motionRangeBreachPolicy{};  // offset 36
    hk motionWeldBreachPolicy{};  // offset 40
};

/// Havok type "hknpBodyQuality::FlagsEnum"  (Python class: hknpBodyQualityFlagsEnum)
/// byte_size=4, alignment=4
using hknpBodyQualityFlagsEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpBodyQualityLibrary"
/// byte_size=1568, alignment=16
struct hknpBodyQualityLibrary : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpBodyQualityLibrary";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    Ptr qualityModifiedSignal;  // offset 24 [not serialized]
    std::array<hknpBodyQuality, 32> qualities;  // offset 32
};

/// Havok type "hknpBroadPhaseConfig"
/// byte_size=24, alignment=8
struct hknpBroadPhaseConfig : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpBroadPhaseConfig";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};

/// Havok type "hknpConvexShape"
/// byte_size=56, alignment=8
struct hknpConvexShape : hknpShape
{
    static constexpr std::string_view TypeName = "hknpConvexShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint16_t maxAllowedPenetration{};  // offset 48
    std::vector<hkVector4f> vertices;  // offset 50
};

/// Havok type "hknpConvexPolytopeShape::Face"  (Python class: hknpConvexPolytopeShapeFace)
/// byte_size=4, alignment=2
struct hknpConvexPolytopeShapeFace
{
    uint16_t firstIndex{};  // offset 0
    uint8_t numIndices{};  // offset 2
    uint8_t minHalfAngle{};  // offset 3
};
static_assert(sizeof(hknpConvexPolytopeShapeFace) == 4,
              "Layout mismatch for hknpConvexPolytopeShapeFace");

/// Havok type "hknpConvexPolytopeShape::Connectivity::Edge"  (Python class: hknpConvexPolytopeShapeConnectivityEdge)
/// byte_size=4, alignment=2
struct hknpConvexPolytopeShapeConnectivityEdge
{
    uint16_t faceIndex{};  // offset 0
    uint8_t edgeIndex{};  // offset 2
    std::array<uint8_t, 1> padding;  // offset 3 [not serialized]
};
static_assert(sizeof(hknpConvexPolytopeShapeConnectivityEdge) == 4,
              "Layout mismatch for hknpConvexPolytopeShapeConnectivityEdge");

/// Havok type "hknpConvexPolytopeShape::Connectivity"  (Python class: hknpConvexPolytopeShapeConnectivity)
/// byte_size=56, alignment=8
struct hknpConvexPolytopeShapeConnectivity : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpConvexPolytopeShape::Connectivity";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hknpConvexPolytopeShapeConnectivityEdge> vertexEdges;  // offset 24
    std::vector<hknpConvexPolytopeShapeConnectivityEdge> faceLinks;  // offset 40
};

/// Havok type "hknpConvexPolytopeShape"
/// byte_size=80, alignment=8
struct hknpConvexPolytopeShape : hknpConvexShape
{
    static constexpr std::string_view TypeName = "hknpConvexPolytopeShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkVector4> planes;  // offset 54
    std::vector<hknpConvexPolytopeShapeFace> faces;  // offset 58
    std::vector<uint8_t> indices;  // offset 62
    std::shared_ptr<hknpConvexPolytopeShapeConnectivity> connectivity;  // offset 72
};

/// Havok type "hknpCapsuleShape"
/// byte_size=112, alignment=16
struct hknpCapsuleShape : hknpConvexPolytopeShape
{
    static constexpr std::string_view TypeName = "hknpCapsuleShape";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkVector4 a{};  // offset 80
    hkVector4 b{};  // offset 96
};

/// Havok type "hknpCollisionDispatchType::Enum"  (Python class: hknpCollisionDispatchTypeEnum)
/// byte_size=4, alignment=4
using hknpCollisionDispatchTypeEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpCollisionFilter"
/// byte_size=24, alignment=8
struct hknpCollisionFilter : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpCollisionFilter";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint8_t type{};  // offset 20
};

/// Havok type "hknpCollisionFilter::Type"  (Python class: hknpCollisionFilterType)
/// byte_size=4, alignment=4
using hknpCollisionFilterType = int32_t;  // Havok enum/alias

/// Havok type "hknpConstraintId"
struct hknpConstraintId : hkHandle
{
};

/// Havok type "hknpConstraintGroupId"
struct hknpConstraintGroupId : hkHandle
{
};

/// Havok type "hknpConstraintCinfo"
/// byte_size=40, alignment=8
struct hknpConstraintCinfo
{
    std::shared_ptr<hkpConstraintData> constraintData;  // offset 0
    hknpBodyId bodyA;  // offset 8
    hknpBodyId bodyB;  // offset 12
    uint16_t flags{};  // offset 16
    std::string name;  // offset 24
    hknpConstraintId desiredConstraintId;  // offset 32
    hknpConstraintGroupId constraintGroupId;  // offset 36
};

/// Havok type "hknpConstraint::FlagsEnum"  (Python class: hknpConstraintFlagsEnum)
/// byte_size=4, alignment=4
using hknpConstraintFlagsEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpLodManagerCinfo"
/// byte_size=24, alignment=4
struct hknpLodManagerCinfo
{
    bool registerDefaultConfig{};  // offset 0
    bool autoBuildLodOnDynamicBodyAdded{};  // offset 1
    bool autoBuildLodOnMeshBodyAdded{};  // offset 2
    float lodAccuray{};  // offset 4
    float slowToFastThreshold{};  // offset 8
    float fastToSlowThreshold{};  // offset 12
    float bodyIsBigThreshold{};  // offset 16
    float avgVelocityGain{};  // offset 20
};
static_assert(sizeof(hknpLodManagerCinfo) == 24,
              "Layout mismatch for hknpLodManagerCinfo");

/// Havok type "hknpMaterial"
/// byte_size=112, alignment=16
struct hknpMaterial : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpMaterial";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 32
    uint32_t isExclusive{};  // offset 40
    int32_t flags{};  // offset 44
    uint8_t triggerType{};  // offset 48
    hkUFloat8 triggerManifoldTolerance;  // offset 49
    uint16_t dynamicFriction{};  // offset 50
    uint16_t staticFriction{};  // offset 52
    uint16_t restitution{};  // offset 54
    uint8_t frictionCombinePolicy{};  // offset 56
    uint8_t restitutionCombinePolicy{};  // offset 57
    float weldingTolerance{};  // offset 60
    float maxContactImpulse{};  // offset 64
    float fractionOfClippedImpulseToApply{};  // offset 68
    uint8_t massChangerCategory{};  // offset 72
    uint16_t massChangerHeavyObjectFactor{};  // offset 74
    uint16_t softContactForceFactor{};  // offset 76
    uint16_t softContactDampFactor{};  // offset 78
    hkUFloat8 softContactSeparationVelocity;  // offset 80
    Ptr surfaceVelocity;  // offset 88
    uint16_t disablingCollisionsBetweenCvxCvxDynamicObjectsDistance{};  // offset 96
    uint64_t userData{};  // offset 104
};

/// Havok type "hknpMaterial::CombinePolicy"  (Python class: hknpMaterialCombinePolicy)
/// byte_size=4, alignment=4
using hknpMaterialCombinePolicy = int32_t;  // Havok enum/alias

/// Havok type "hknpMaterialLibrary"
/// byte_size=72, alignment=8
struct hknpMaterialLibrary : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpMaterialLibrary";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    Ptr materialAddedSignal;  // offset 24 [not serialized]
    Ptr materialModifiedSignal;  // offset 32 [not serialized]
    Ptr materialRemovedSignal;  // offset 40 [not serialized]
    hkFreeListArray entries;  // offset 48
};

/// Havok type "hknpMaterial::MassChangerCategory"  (Python class: hknpMaterialMassChangerCategory)
/// byte_size=4, alignment=4
using hknpMaterialMassChangerCategory = int32_t;  // Havok enum/alias

/// Havok type "hknpMaterial::TriggerType"  (Python class: hknpMaterialTriggerType)
/// byte_size=4, alignment=4
using hknpMaterialTriggerType = int32_t;  // Havok enum/alias

/// Havok type "hknpMotionProperties::DeactivationSettings"  (Python class: hknpMotionPropertiesDeactivationSettings)
/// byte_size=24, alignment=4
struct hknpMotionPropertiesDeactivationSettings
{
    float maxDistSqrd{};  // offset 0
    float maxRotSqrd{};  // offset 4
    float invBlockSize{};  // offset 8
    int16_t pathingUpperThreshold{};  // offset 12
    int16_t pathingLowerThreshold{};  // offset 14
    uint8_t numDeactivationFrequencyPasses{};  // offset 16
    uint8_t deactivationVelocityScaleSquare{};  // offset 17
    uint8_t minimumPathingVelocityScaleSquare{};  // offset 18
    uint8_t spikingVelocityScaleThresholdSquared{};  // offset 19
    uint8_t minimumSpikingVelocityScaleSquared{};  // offset 20
};
static_assert(sizeof(hknpMotionPropertiesDeactivationSettings) == 24,
              "Layout mismatch for hknpMotionPropertiesDeactivationSettings");

/// Havok type "hknpMotionProperties::FullCastSettings"  (Python class: hknpMotionPropertiesFullCastSettings)
/// byte_size=40, alignment=4
struct hknpMotionPropertiesFullCastSettings
{
    float minSeparation{};  // offset 0
    float minExtraSeparation{};  // offset 4
    float toiSeparation{};  // offset 8
    float toiExtraSeparation{};  // offset 12
    float toiAccuracy{};  // offset 16
    float relativeSafeDeltaTime{};  // offset 20
    float absoluteSafeDeltaTime{};  // offset 24
    float keepTime{};  // offset 28
    float keepDistance{};  // offset 32
    int32_t maxIterations{};  // offset 36
};
static_assert(sizeof(hknpMotionPropertiesFullCastSettings) == 40,
              "Layout mismatch for hknpMotionPropertiesFullCastSettings");

/// Havok type "hknpMotionProperties"
/// byte_size=112, alignment=16
struct hknpMotionProperties
{
    uint32_t isExclusive{};  // offset 0
    uint32_t flags{};  // offset 4
    float gravityFactor{};  // offset 8
    float timeFactor{};  // offset 12
    float maxLinearSpeed{};  // offset 16
    float maxAngularSpeed{};  // offset 20
    float linearDamping{};  // offset 24
    float angularDamping{};  // offset 28
    float solverStabilizationSpeedThreshold{};  // offset 32
    float solverStabilizationSpeedReduction{};  // offset 36
    hknpMotionPropertiesDeactivationSettings deactivationSettings;  // offset 40
    hknpMotionPropertiesFullCastSettings fullCastSettings;  // offset 64
};

/// Havok type "hknpMotionPropertiesLibrary"
/// byte_size=72, alignment=8
struct hknpMotionPropertiesLibrary : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpMotionPropertiesLibrary";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    Ptr entryAddedSignal;  // offset 24 [not serialized]
    Ptr entryModifiedSignal;  // offset 32 [not serialized]
    Ptr entryRemovedSignal;  // offset 40 [not serialized]
    hkFreeListArray entries;  // offset 48
};

/// Havok type "hknpPhysicsSceneData"
/// byte_size=48, alignment=8
struct hknpPhysicsSceneData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpPhysicsSceneData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hknpPhysicsSystemData>> systemDatas;  // offset 24
    Ptr worldCinfo;  // offset 40
};

/// Havok type "hknpPhysicsSystemData::bodyCinfoWithAttachment"  (Python class: hknpPhysicsSystemDatabodyCinfoWithAttachment)
/// byte_size=176, alignment=16
struct hknpPhysicsSystemDatabodyCinfoWithAttachment : hknpBodyCinfo
{
    int32_t attachedBody{};  // offset 164
};
static_assert(sizeof(hknpPhysicsSystemDatabodyCinfoWithAttachment) == 176,
              "Layout mismatch for hknpPhysicsSystemDatabodyCinfoWithAttachment");

/// Havok type "hknpPhysicsSystemData"
/// byte_size=104, alignment=8
struct hknpPhysicsSystemData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpPhysicsSystemData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hknpMaterial>> materials;  // offset 24
    std::vector<hknpMotionProperties> motionProperties;  // offset 40
    std::vector<hknpPhysicsSystemDatabodyCinfoWithAttachment> bodyCinfos;  // offset 56
    std::vector<hknpConstraintCinfo> constraintCinfos;  // offset 72
    std::string name;  // offset 88
    uint8_t microStepMultiplier{};  // offset 96
};

/// Havok type "hknpRagdollData"
/// byte_size=144, alignment=8
struct hknpRagdollData : hknpPhysicsSystemData
{
    static constexpr std::string_view TypeName = "hknpRagdollData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkaSkeleton> skeleton;  // offset 104
    std::vector<int32_t> boneToBodyMap;  // offset 112
    std::vector<uint32_t> bodyTags;  // offset 128
};

/// Havok type "hknpShapeTagCodec"
/// byte_size=32, alignment=8
struct hknpShapeTagCodec : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpShapeTagCodec";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint32_t hints{};  // offset 20
    uint8_t type{};  // offset 24
};

/// Havok type "hknpWeldingConfig"
/// byte_size=4, alignment=4
struct hknpWeldingConfig
{
    float relativeGhostPlaneThreshold{};  // offset 0
};
static_assert(sizeof(hknpWeldingConfig) == 4,
              "Layout mismatch for hknpWeldingConfig");

/// Havok type "hknpWorldCinfo"
/// byte_size=304, alignment=16
struct hknpWorldCinfo
{
    Ptr blockStreamAllocator;  // offset 0 [not serialized]
    int32_t bodyBufferCapacity{};  // offset 8
    Ptr userBodyBuffer;  // offset 16 [not serialized]
    int32_t motionBufferCapacity{};  // offset 24
    Ptr userMotionBuffer;  // offset 32 [not serialized]
    int32_t constraintBufferCapacity{};  // offset 40
    Ptr userConstraintBuffer;  // offset 48 [not serialized]
    int32_t constraintGroupBufferCapacity{};  // offset 56
    Ptr userConstraintGroupBuffer;  // offset 64 [not serialized]
    bool useBodyBacklinkBuffer{};  // offset 72
    std::shared_ptr<hknpMaterialLibrary> materialLibrary;  // offset 80
    std::shared_ptr<hknpMotionPropertiesLibrary> motionPropertiesLibrary;  // offset 88
    std::shared_ptr<hknpBodyQualityLibrary> qualityLibrary;  // offset 96
    uint8_t simulationType{};  // offset 104
    int32_t numSplitterCells{};  // offset 108
    hkVector4 gravity{};  // offset 112
    float airDensity{};  // offset 128
    bool enableContactCaching{};  // offset 132
    bool mergeEventsBeforeDispatch{};  // offset 133
    uint8_t broadPhaseType{};  // offset 134
    hkAabb broadPhaseAabb{};  // offset 144
    std::shared_ptr<hknpBroadPhaseConfig> broadPhaseConfig;  // offset 176
    std::shared_ptr<hknpCollisionFilter> collisionFilter;  // offset 184
    std::shared_ptr<hknpShapeTagCodec> shapeTagCodec;  // offset 192
    float collisionTolerance{};  // offset 200
    float relativeCollisionAccuracy{};  // offset 204
    float aabbMargin{};  // offset 208
    bool enableWeldingForDefaultObjects{};  // offset 212
    bool enableWeldingForCriticalObjects{};  // offset 213
    hknpWeldingConfig weldingConfig;  // offset 216
    hknpLodManagerCinfo lodManagerCinfo;  // offset 220
    bool enableSdfEdgeCollisions{};  // offset 244
    bool enableCollideWorkStealing{};  // offset 245
    int32_t particlesLandscapeQuadCacheSize{};  // offset 248
    float solverTau{};  // offset 252
    float solverDamp{};  // offset 256
    int32_t solverIterations{};  // offset 260
    int32_t solverMicrosteps{};  // offset 264
    bool enableDeactivation{};  // offset 268
    bool enablePenetrationRecovery{};  // offset 269
    float maxApproachSpeedForHighQualitySolver{};  // offset 272
    std::shared_ptr<hknpBodyIntegrator> bodyIntegrator;  // offset 280
    bool adjustSolverSettingsBasedOnTimestep{};  // offset 288
    float expectedDeltaTime{};  // offset 292
    int32_t minSolverIterations{};  // offset 296
    int32_t maxSolverIterations{};  // offset 300
};

/// Havok type "hknpRefWorldCinfo"
/// byte_size=336, alignment=16
struct hknpRefWorldCinfo : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpRefWorldCinfo";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hknpWorldCinfo info;  // offset 32
};

/// Havok type "hknpShape::FlagsEnum"  (Python class: hknpShapeFlagsEnum)
/// byte_size=4, alignment=4
using hknpShapeFlagsEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpShapeMassProperties"
/// byte_size=56, alignment=8
struct hknpShapeMassProperties : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpShapeMassProperties";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkCompressedMassProperties compressedMassProperties;  // offset 24
};

/// Havok type "hknpShapeTagCodec::Hints"  (Python class: hknpShapeTagCodecHints)
/// byte_size=4, alignment=4
using hknpShapeTagCodecHints = int32_t;  // Havok enum/alias

/// Havok type "hknpShapeTagCodec::Type"  (Python class: hknpShapeTagCodecType)
/// byte_size=4, alignment=4
using hknpShapeTagCodecType = int32_t;  // Havok enum/alias

/// Havok type "hknpShapeType::Enum"  (Python class: hknpShapeTypeEnum)
/// byte_size=4, alignment=4
using hknpShapeTypeEnum = int32_t;  // Havok enum/alias

/// Havok type "hknpSurfaceVelocity"
/// byte_size=24, alignment=8
struct hknpSurfaceVelocity : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hknpSurfaceVelocity";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};

// Registers all deserializers for this type set.
// Call after constructing TagFileUnpacker (or from TagFileUnpacker::RegisterDispatch).
class TagFileUnpacker;
void RegisterHknpDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok