// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>

namespace Firelink::Havok
{

struct _float;  // cross-folder forward declaration
struct hkMeshBoneIndexMapping;  // cross-folder forward declaration

/// Havok type "hkxAttribute"
/// byte_size=16, alignment=8
struct hkxAttribute
{
    std::string name;  // offset 0
    std::shared_ptr<hkReferencedObject> value;  // offset 8
};

/// Havok type "hkxAttributeGroup"
/// byte_size=24, alignment=8
struct hkxAttributeGroup
{
    std::string name;  // offset 0
    std::vector<hkxAttribute> attributes;  // offset 8
};

/// Havok type "hkxAttributeHolder"
/// byte_size=40, alignment=8
struct hkxAttributeHolder : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxAttributeHolder";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkxAttributeGroup> attributeGroups;  // offset 24
};

/// Havok type "hkxIndexBuffer"
/// byte_size=72, alignment=8
struct hkxIndexBuffer : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxIndexBuffer";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int8_t indexType{};  // offset 24
    std::vector<uint16_t> indices16;  // offset 32
    std::vector<uint32_t> indices32;  // offset 48
    uint32_t vertexBaseOffset{};  // offset 64
    uint32_t length{};  // offset 68
};

/// Havok type "hkxIndexBuffer::IndexType"  (Python class: hkxIndexBufferIndexType)
/// byte_size=4, alignment=4
using hkxIndexBufferIndexType = int32_t;  // Havok enum/alias

/// Havok type "hkxMaterial::TextureStage"  (Python class: hkxMaterialTextureStage)
/// byte_size=16, alignment=8
struct hkxMaterialTextureStage
{
    std::shared_ptr<hkReferencedObject> texture;  // offset 0
    int32_t usageHint{};  // offset 8
    int32_t tcoordChannel{};  // offset 12
};

/// Havok type "hkxMaterial::Property"  (Python class: hkxMaterialProperty)
/// byte_size=8, alignment=4
struct hkxMaterialProperty
{
    uint32_t key{};  // offset 0
    uint32_t value{};  // offset 4
};
static_assert(sizeof(hkxMaterialProperty) == 8,
              "Layout mismatch for hkxMaterialProperty");

/// Havok type "hkxMaterial"
/// byte_size=224, alignment=16
struct hkxMaterial : hkxAttributeHolder
{
    static constexpr std::string_view TypeName = "hkxMaterial";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 40
    std::vector<hkxMaterialTextureStage> stages;  // offset 48
    hkVector4 diffuseColor{};  // offset 64
    hkVector4 ambientColor{};  // offset 80
    hkVector4 specularColor{};  // offset 96
    hkVector4 emissiveColor{};  // offset 112
    std::vector<std::shared_ptr<DefType>> subMaterials;  // offset 128
    std::shared_ptr<hkReferencedObject> extraData;  // offset 144
    std::array<float, 2> uvMapScale;  // offset 152
    std::array<float, 2> uvMapOffset;  // offset 160
    float uvMapRotation{};  // offset 168
    uint32_t uvMapAlgorithm{};  // offset 172
    float specularMultiplier{};  // offset 176
    float specularExponent{};  // offset 180
    uint8_t transparency{};  // offset 184
    uint64_t userData{};  // offset 192
    std::vector<hkxMaterialProperty> properties;  // offset 200
};

/// Havok type "hkxMaterial::TextureType"  (Python class: hkxMaterialTextureType)
/// byte_size=4, alignment=4
using hkxMaterialTextureType = int32_t;  // Havok enum/alias

/// Havok type "hkxMaterial::Transparency"  (Python class: hkxMaterialTransparency)
/// byte_size=4, alignment=4
using hkxMaterialTransparency = int32_t;  // Havok enum/alias

/// Havok type "hkxMaterial::UVMappingAlgorithm"  (Python class: hkxMaterialUVMappingAlgorithm)
/// byte_size=4, alignment=4
using hkxMaterialUVMappingAlgorithm = int32_t;  // Havok enum/alias

/// Havok type "hkxMesh"
/// byte_size=56, alignment=8
struct hkxMesh : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxMesh";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkxMeshSection>> sections;  // offset 24
    std::vector<std::shared_ptr<hkxMeshUserChannelInfo>> userChannelInfos;  // offset 40
};

/// Havok type "hkxVertexBuffer::VertexData"  (Python class: hkxVertexBufferVertexData)
/// byte_size=104, alignment=8
struct hkxVertexBufferVertexData
{
    std::vector<uint32_t> vectorData;  // offset 0
    std::vector<uint32_t> floatData;  // offset 16
    std::vector<uint32_t> uint32Data;  // offset 32
    std::vector<uint16_t> uint16Data;  // offset 48
    std::vector<uint8_t> uint8Data;  // offset 64
    uint32_t numVerts{};  // offset 80
    uint32_t vectorStride{};  // offset 84
    uint32_t floatStride{};  // offset 88
    uint32_t uint32Stride{};  // offset 92
    uint32_t uint16Stride{};  // offset 96
    uint32_t uint8Stride{};  // offset 100
};

/// Havok type "hkxVertexDescription::ElementDecl"  (Python class: hkxVertexDescriptionElementDecl)
/// byte_size=24, alignment=8
struct hkxVertexDescriptionElementDecl
{
    uint32_t byteOffset{};  // offset 0
    uint16_t type{};  // offset 4
    uint16_t usage{};  // offset 6
    uint32_t byteStride{};  // offset 8
    uint8_t numElements{};  // offset 12
    std::string channelID;  // offset 16
};

/// Havok type "hkxVertexDescription"
/// byte_size=16, alignment=8
struct hkxVertexDescription
{
    std::vector<hkxVertexDescriptionElementDecl> decls;  // offset 0
};

/// Havok type "hkxVertexBuffer"
/// byte_size=144, alignment=8
struct hkxVertexBuffer : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxVertexBuffer";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkxVertexBufferVertexData data;  // offset 24
    hkxVertexDescription desc;  // offset 128
};

/// Havok type "hkxMeshSection"
/// byte_size=120, alignment=8
struct hkxMeshSection : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxMeshSection";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkxVertexBuffer> vertexBuffer;  // offset 24
    std::vector<std::shared_ptr<std::shared_ptr<hkxIndexBuffer>>> indexBuffers;  // offset 32
    std::shared_ptr<hkxMaterial> material;  // offset 48
    std::vector<std::shared_ptr<hkReferencedObject>> userChannels;  // offset 56
    std::vector<std::shared_ptr<hkxVertexAnimation>> vertexAnimations;  // offset 72
    std::vector<_float> linearKeyFrameHints;  // offset 88
    std::vector<hkMeshBoneIndexMapping> boneMatrixMap;  // offset 104
};

/// Havok type "hkxMesh::UserChannelInfo"  (Python class: hkxMeshUserChannelInfo)
/// byte_size=56, alignment=8
struct hkxMeshUserChannelInfo : hkxAttributeHolder
{
    static constexpr std::string_view TypeName = "hkxMesh::UserChannelInfo";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 40
    std::string className;  // offset 48
};

/// Havok type "hkxVertexAnimation::UsageMap"  (Python class: hkxVertexAnimationUsageMap)
/// byte_size=4, alignment=2
struct hkxVertexAnimationUsageMap
{
    uint16_t use{};  // offset 0
    uint8_t useIndexOrig{};  // offset 2
    uint8_t useIndexLocal{};  // offset 3
};
static_assert(sizeof(hkxVertexAnimationUsageMap) == 4,
              "Layout mismatch for hkxVertexAnimationUsageMap");

/// Havok type "hkxVertexAnimation"
/// byte_size=208, alignment=8
struct hkxVertexAnimation : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkxVertexAnimation";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    float time{};  // offset 24
    hkxVertexBuffer vertData;  // offset 32
    std::vector<int32_t> vertexIndexMap;  // offset 176
    std::vector<hkxVertexAnimationUsageMap> componentMap;  // offset 192
};

/// Havok type "hkxVertexDescription::DataType"  (Python class: hkxVertexDescriptionDataType)
/// byte_size=4, alignment=4
using hkxVertexDescriptionDataType = int32_t;  // Havok enum/alias

/// Havok type "hkxVertexDescription::DataUsage"  (Python class: hkxVertexDescriptionDataUsage)
/// byte_size=4, alignment=4
using hkxVertexDescriptionDataUsage = int32_t;  // Havok enum/alias

// Registers all deserializers for this type set.
// Call after constructing TagFileUnpacker (or from TagFileUnpacker::RegisterDispatch).
class TagFileUnpacker;
void RegisterHkxDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok