// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

struct DefType;  // cross-folder forward declaration
struct hkHashMap;  // cross-folder forward declaration

/// Havok type "hkAssetRefPtr"
/// byte_size=8, alignment=8, is_pod=False
struct hkAssetRefPtr
{
    std::shared_ptr<DefType> ptr;  // offset 0
};

/// Havok type "hkBitFieldStorage"
/// byte_size=24, alignment=8, is_pod=False
struct hkBitFieldStorage
{
    std::vector<uint32_t> words;  // offset 0
    int32_t numBits{};  // offset 16
};

/// Havok type "hkBitFieldBase"
/// byte_size=24, alignment=8, is_pod=False
struct hkBitFieldBase
{
    hkBitFieldStorage storage;  // offset 0
};

/// Havok type "hkBitField"
/// byte_size=24, alignment=8, is_pod=False
struct hkBitField : hkBitFieldBase
{
};

/// Havok type "hkPackedVector3"
/// byte_size=8, alignment=8, is_pod=True
struct hkPackedVector3
{
    std::array<int16_t, 4> values;  // offset 0
};
static_assert(sizeof(hkPackedVector3) == 8,
              "Layout mismatch for hkPackedVector3");

/// Havok type "hkCompressedMassProperties"
/// byte_size=32, alignment=12296, is_pod=False
struct hkCompressedMassProperties
{
    hkPackedVector3 centerOfMass;  // offset 0
    hkPackedVector3 inertia;  // offset 8
    std::array<int16_t, 4> majorAxisSpace;  // offset 16
    float mass{};  // offset 24
    float volume{};  // offset 28
};

/// Havok type "hkDefaultPropertyBag"
/// byte_size=72, alignment=8, is_pod=False
struct hkDefaultPropertyBag
{
    hkHashMap propertyMap;  // offset 0
    hkHashMap transientPropertyMap;  // offset 32 [not serialized (null)]
    bool locked{};  // offset 64 [not serialized (null)]
};

/// Havok type "hkHandle"
/// byte_size=4, alignment=4, is_pod=True
struct hkHandle
{
    uint32_t value{};  // offset 0
};
static_assert(sizeof(hkHandle) == 4,
              "Layout mismatch for hkHandle");

/// Havok type "hkLocalFrame"
/// byte_size=24, alignment=8, is_pod=True
struct hkLocalFrame : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkLocalFrame";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};
static_assert(sizeof(hkLocalFrame) == 24,
              "Layout mismatch for hkLocalFrame");

/// Havok type "hkMeshBoneIndexMapping"
/// byte_size=16, alignment=8, is_pod=False
struct hkMeshBoneIndexMapping
{
    std::vector<int16_t> mapping;  // offset 0
};

/// Havok type "hkPropertyFlags::Enum"  (Python class: hkPropertyFlagsEnum)
/// byte_size=4, alignment=4, is_pod=True
using hkPropertyFlagsEnum = ERROR;  // Havok enum/alias

/// Havok type "hkRefCountedProperties::Entry"  (Python class: hkRefCountedPropertiesEntry)
/// byte_size=16, alignment=8, is_pod=False
struct hkRefCountedPropertiesEntry
{
    std::shared_ptr<hkReferencedObject> object;  // offset 0
    uint16_t key{};  // offset 8
    uint16_t flags{};  // offset 10
};

/// Havok type "hkRefCountedProperties"
/// byte_size=40, alignment=8, is_pod=False
struct hkRefCountedProperties : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkRefCountedProperties";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkRefCountedPropertiesEntry> entries;  // offset 24
};

/// Havok type "hkRootLevelContainer::NamedVariant"  (Python class: hkRootLevelContainerNamedVariant)
/// byte_size=24, alignment=8, is_pod=False
struct hkRootLevelContainerNamedVariant
{
    std::string name;  // offset 0
    std::string className;  // offset 8
    std::shared_ptr<hkReferencedObject> variant;  // offset 16
};

/// Havok type "hkRootLevelContainer"
/// byte_size=16, alignment=8, is_pod=False
struct hkRootLevelContainer
{
    std::vector<hkRootLevelContainerNamedVariant> namedVariants;  // offset 0
};

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterBaseDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing