// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

/// Havok type "hkReflect::QualifiedType"  (Python class: hkReflectQualifiedType)
/// byte_size=8, alignment=8, is_pod=False
struct hkReflectQualifiedType
{
    std::shared_ptr<void> type;  // offset 0
};

/// Havok type "hkPropertyDesc"
/// byte_size=24, alignment=8, is_pod=False
struct hkPropertyDesc
{
    std::shared_ptr<void> type;  // offset 0
    std::string name{};  // offset 8
    uint32_t flags{};  // offset 16
};

/// Havok type "hkPtrAndInt"
/// byte_size=8, alignment=8, is_pod=False
struct hkPtrAndInt
{
    std::shared_ptr<hkPropertyDesc> ptrAndInt;  // offset 0
};

/// Havok type "hkReflect::Any"  (Python class: hkReflectAny)
/// byte_size=32, alignment=16, is_pod=False
struct hkReflectAny
{
    hkReflectQualifiedType type;  // offset 0
    uint8_t status{};  // offset 8
    std::array<uint32_t, 4> buf;  // offset 16
};

/// Havok type "hkPropertyId"
/// byte_size=8, alignment=8, is_pod=False
struct hkPropertyId
{
    hkPtrAndInt desc;  // offset 0 [not serialized (null)]
};

/// Havok type "hkTuple"
/// byte_size=48, alignment=16, is_pod=False
struct hkTuple
{
    hkPropertyId _0;  // offset 0
    hkReflectAny _1;  // offset 16
};

/// Havok type "hkHashMapDetail::Index"  (Python class: hkHashMapDetailIndex)
/// byte_size=16, alignment=8, is_pod=False
struct hkHashMapDetailIndex
{
    std::shared_ptr<void> entries;  // offset 0
    int32_t hashMod{};  // offset 8
};

/// Havok type "hkHashMapDetail::MapTuple"  (Python class: hkHashMapDetailMapTuple)
/// byte_size=48, alignment=16, is_pod=False
struct hkHashMapDetailMapTuple : hkTuple
{
};

/// Havok type "hkHashBase"
/// byte_size=32, alignment=8, is_pod=False
struct hkHashBase
{
    std::vector<hkHashMapDetailMapTuple> items;  // offset 0
    hkHashMapDetailIndex index;  // offset 16 [not serialized (null)]
};

/// Havok type "hkHashMap"
/// byte_size=32, alignment=8, is_pod=False
struct hkHashMap : hkHashBase
{
};

/// Havok type "hkDefaultPropertyBag"
/// byte_size=72, alignment=8, is_pod=False
struct hkDefaultPropertyBag
{
    hkHashMap propertyMap;  // offset 0
    hkHashMap transientPropertyMap;  // offset 32 [not serialized (null)]
    bool locked{};  // offset 64 [not serialized (null)]
};

/// Havok type "hkPropertyBag"
/// byte_size=8, alignment=8, is_pod=False
struct hkPropertyBag
{
    std::shared_ptr<hkDefaultPropertyBag> bag;  // offset 0 [not serialized (null)]
};

/// Havok type "hkReferencedObject"
/// byte_size=24, alignment=8, is_pod=False
struct hkReferencedObject
{
    hkPropertyBag propertyBag;  // offset 8
    uint16_t memSizeAndFlags{};  // offset 16 [not serialized (null)]
    uint16_t refCount{};  // offset 18 [not serialized (null)]
};

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterCoreDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing