// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

struct hkbBlendingTransitionEffect;  // cross-folder forward declaration
struct hkbCustomIdSelector;  // cross-folder forward declaration
struct hkbEvent;  // cross-folder forward declaration
struct hkbGenerator;  // cross-folder forward declaration
struct hkbModifier;  // cross-folder forward declaration
struct hkbTransitionEffect;  // cross-folder forward declaration

/// Havok type "CustomLookAtTwistModifier::TwistParam"  (Python class: CustomLookAtTwistModifierTwistParam)
/// byte_size=24, alignment=4, is_pod=True
struct CustomLookAtTwistModifierTwistParam
{
    int16_t startBoneIndex{};  // offset 0
    int16_t endBoneIndex{};  // offset 2
    float targetRotationRate{};  // offset 4
    float newTargetGain{};  // offset 8
    float onGain{};  // offset 12
    float offGain{};  // offset 16
    int8_t gainStateX{};  // offset 20 [not serialized (null)]
    int8_t gainStateY{};  // offset 21 [not serialized (null)]
};
static_assert(sizeof(CustomLookAtTwistModifierTwistParam) == 24,
              "Layout mismatch for CustomLookAtTwistModifierTwistParam");

/// Havok type "CustomLookAtTwistModifier"
/// byte_size=208, alignment=8, is_pod=False
struct CustomLookAtTwistModifier : hkbModifier
{
    int32_t ModifierID{};  // offset 104
    int8_t rotationAxisType{};  // offset 108
    int32_t SensingDummyPoly{};  // offset 112
    std::vector<CustomLookAtTwistModifierTwistParam> twistParam;  // offset 120
    float UpLimitAngle{};  // offset 136
    float DownLimitAngle{};  // offset 140
    float RightLimitAngle{};  // offset 144
    float LeftLimitAngle{};  // offset 148
    float UpMinimumAngle{};  // offset 152
    float DownMinimumAngle{};  // offset 156
    float RightMinimumAngle{};  // offset 160
    float LeftMinimumAngle{};  // offset 164
    int16_t SensingAngle{};  // offset 168
    int8_t setAngleMethod{};  // offset 170
    bool isAdditive{};  // offset 171
    std::vector<void*> twistModifierXArray;  // offset 176 [not serialized (null)]
    std::vector<void*> twistModifierYArray;  // offset 192 [not serialized (null)]
};

/// Havok type "CustomLookAtTwistModifier::GainState"  (Python class: CustomLookAtTwistModifierGainState)
/// byte_size=4, alignment=4, is_pod=True
using CustomLookAtTwistModifierGainState = ERROR;  // Havok enum/alias

/// Havok type "CustomLookAtTwistModifier::MultiRotationAxisType"  (Python class: CustomLookAtTwistModifierMultiRotationAxisType)
/// byte_size=4, alignment=4, is_pod=True
using CustomLookAtTwistModifierMultiRotationAxisType = ERROR;  // Havok enum/alias

/// Havok type "CustomLookAtTwistModifier::SetAngleMethod"  (Python class: CustomLookAtTwistModifierSetAngleMethod)
/// byte_size=4, alignment=4, is_pod=True
using CustomLookAtTwistModifierSetAngleMethod = ERROR;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator"
/// byte_size=280, alignment=8, is_pod=False
struct CustomManualSelectorGenerator : hkbGenerator
{
    std::vector<std::shared_ptr<hkbGenerator>> generators;  // offset 152
    int32_t offsetType{};  // offset 168
    int32_t animId{};  // offset 172
    int32_t animeEndEventType{};  // offset 176
    bool enableScript{};  // offset 180
    bool enableTae{};  // offset 181
    uint8_t changeTypeOfSelectedIndexAfterActivate{};  // offset 182
    std::shared_ptr<hkbTransitionEffect> generatorChangedTransitionEffect;  // offset 184
    int32_t checkAnimEndSlotNo{};  // offset 192
    uint8_t replanningAI{};  // offset 196
    uint8_t rideSync{};  // offset 197
    hkbEvent endEvent;  // offset 200 [not serialized (null)]
    float preLocalTime{};  // offset 224 [not serialized (null)]
    float localTime{};  // offset 228 [not serialized (null)]
    float animeDuration{};  // offset 232 [not serialized (null)]
    int32_t argTaeId{};  // offset 236 [not serialized (null)]
    std::shared_ptr<void*> scriptGenerator;  // offset 240 [not serialized (null)]
    int32_t stateId{};  // offset 248 [not serialized (null)]
    bool isFirstUpdate{};  // offset 252 [not serialized (null)]
    bool isAnimTest{};  // offset 253 [not serialized (null)]
    bool isSelfTransition{};  // offset 254 [not serialized (null)]
    int16_t currentGeneratorIndex{};  // offset 256 [not serialized (null)]
    int16_t generatorIndexAtActivate{};  // offset 258 [not serialized (null)]
    std::vector<void*> activeTransitions;  // offset 264 [not serialized (null)]
};

/// Havok type "CustomManualSelectorGenerator::AnimeEndEventType"  (Python class: CustomManualSelectorGeneratorAnimeEndEventType)
/// byte_size=4, alignment=4, is_pod=True
using CustomManualSelectorGeneratorAnimeEndEventType = ERROR;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::ChangeTypeOfSelectedIndexAfterActivate"  (Python class: CustomManualSelectorGeneratorChangeTypeOfSelectedIndexAfterActivate)
/// byte_size=4, alignment=4, is_pod=True
using CustomManualSelectorGeneratorChangeTypeOfSelectedIndexAfterActivate = ERROR;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::OffsetType"  (Python class: CustomManualSelectorGeneratorOffsetType)
/// byte_size=4, alignment=4, is_pod=True
using CustomManualSelectorGeneratorOffsetType = ERROR;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::ReplanningAI"  (Python class: CustomManualSelectorGeneratorReplanningAI)
/// byte_size=4, alignment=4, is_pod=True
using CustomManualSelectorGeneratorReplanningAI = ERROR;  // Havok enum/alias

/// Havok type "CustomManualSelectorGenerator::RideSync"  (Python class: CustomManualSelectorGeneratorRideSync)
/// byte_size=4, alignment=4, is_pod=True
using CustomManualSelectorGeneratorRideSync = ERROR;  // Havok enum/alias

/// Havok type "CustomPreDeleteIndexSelector"
/// byte_size=24, alignment=8, is_pod=True
struct CustomPreDeleteIndexSelector : hkbCustomIdSelector
{
};
static_assert(sizeof(CustomPreDeleteIndexSelector) == 24,
              "Layout mismatch for CustomPreDeleteIndexSelector");

/// Havok type "CustomTransitionEffect"
/// byte_size=368, alignment=16, is_pod=True
struct CustomTransitionEffect : hkbBlendingTransitionEffect
{
    float durationBackup{};  // offset 352 [not serialized (null)]
    bool calcDuration{};  // offset 356 [not serialized (null)]
};
static_assert(sizeof(CustomTransitionEffect) == 368,
              "Layout mismatch for CustomTransitionEffect");

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterCustomDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing