// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

struct hkLocalFrame;  // cross-folder forward declaration
struct hkxMesh;  // cross-folder forward declaration

/// Havok type "hkaAnimatedReferenceFrame"
/// byte_size=32, alignment=8, is_pod=True
struct hkaAnimatedReferenceFrame : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaAnimatedReferenceFrame";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int8_t frameType{};  // offset 24 [not serialized (null)]
};
static_assert(sizeof(hkaAnimatedReferenceFrame) == 32,
              "Layout mismatch for hkaAnimatedReferenceFrame");

/// Havok type "hkaAnimatedReferenceFrame::hkaReferenceFrameTypeEnum"  (Python class: hkaAnimatedReferenceFramehkaReferenceFrameTypeEnum)
/// byte_size=4, alignment=4, is_pod=True
using hkaAnimatedReferenceFramehkaReferenceFrameTypeEnum = ERROR;  // Havok enum/alias

/// Havok type "hkaAnnotationTrack::Annotation"  (Python class: hkaAnnotationTrackAnnotation)
/// byte_size=16, alignment=8, is_pod=False
struct hkaAnnotationTrackAnnotation
{
    float time{};  // offset 0
    std::string text;  // offset 8
};

/// Havok type "hkaAnnotationTrack"
/// byte_size=24, alignment=8, is_pod=False
struct hkaAnnotationTrack
{
    std::string trackName;  // offset 0
    std::vector<hkaAnnotationTrackAnnotation> annotations;  // offset 8
};

/// Havok type "hkaAnimation"
/// byte_size=64, alignment=8, is_pod=False
struct hkaAnimation : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaAnimation";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int32_t type{};  // offset 24
    float duration{};  // offset 28
    int32_t numberOfTransformTracks{};  // offset 32
    int32_t numberOfFloatTracks{};  // offset 36
    std::shared_ptr<hkaAnimatedReferenceFrame> extractedMotion;  // offset 40
    std::vector<hkaAnnotationTrack> annotationTracks;  // offset 48
};

/// Havok type "hkaAnimation::AnimationType"  (Python class: hkaAnimationAnimationType)
/// byte_size=4, alignment=4, is_pod=True
using hkaAnimationAnimationType = ERROR;  // Havok enum/alias

/// Havok type "hkaAnimationBinding"
/// byte_size=96, alignment=8, is_pod=False
struct hkaAnimationBinding : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaAnimationBinding";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string originalSkeletonName;  // offset 24
    std::shared_ptr<hkaAnimation> animation;  // offset 32
    std::vector<int16_t> transformTrackToBoneIndices;  // offset 40
    std::vector<int16_t> floatTrackToFloatSlotIndices;  // offset 56
    std::vector<int16_t> partitionIndices;  // offset 72
    int8_t blendHint{};  // offset 88
};

/// Havok type "hkaAnimationBinding::BlendHint"  (Python class: hkaAnimationBindingBlendHint)
/// byte_size=4, alignment=4, is_pod=True
using hkaAnimationBindingBlendHint = ERROR;  // Havok enum/alias

/// Havok type "hkaBone"
/// byte_size=16, alignment=8, is_pod=False
struct hkaBone
{
    std::string name;  // offset 0
    bool lockTranslation{};  // offset 8
};

/// Havok type "hkaSkeleton::LocalFrameOnBone"  (Python class: hkaSkeletonLocalFrameOnBone)
/// byte_size=16, alignment=8, is_pod=False
struct hkaSkeletonLocalFrameOnBone
{
    std::shared_ptr<hkLocalFrame> localFrame;  // offset 0
    int16_t boneIndex{};  // offset 8
};

/// Havok type "hkaSkeleton::Partition"  (Python class: hkaSkeletonPartition)
/// byte_size=16, alignment=8, is_pod=False
struct hkaSkeletonPartition
{
    std::string name;  // offset 0
    int16_t startBoneIndex{};  // offset 8
    int16_t numBones{};  // offset 10
};

/// Havok type "hkaSkeleton"
/// byte_size=144, alignment=8, is_pod=False
struct hkaSkeleton : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaSkeleton";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string name;  // offset 24
    std::vector<int16_t> parentIndices;  // offset 32
    std::vector<hkaBone> bones;  // offset 48
    std::vector<hkQsTransform> referencePose;  // offset 64
    std::vector<float> referenceFloats;  // offset 80
    std::vector<std::string> floatSlots;  // offset 96
    std::vector<hkaSkeletonLocalFrameOnBone> localFrames;  // offset 112
    std::vector<hkaSkeletonPartition> partitions;  // offset 128
};

/// Havok type "hkaBoneAttachment"
/// byte_size=128, alignment=16, is_pod=False
struct hkaBoneAttachment : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaBoneAttachment";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string originalSkeletonName;  // offset 24
    hkMatrix4 boneFromAttachment{};  // offset 32
    std::shared_ptr<hkReferencedObject> attachment;  // offset 96
    std::string name;  // offset 104
    int16_t boneIndex{};  // offset 112
};

/// Havok type "hkaMeshBinding::Mapping"  (Python class: hkaMeshBindingMapping)
/// byte_size=16, alignment=8, is_pod=False
struct hkaMeshBindingMapping
{
    std::vector<int16_t> mapping;  // offset 0
};

/// Havok type "hkaMeshBinding"
/// byte_size=88, alignment=8, is_pod=False
struct hkaMeshBinding : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaMeshBinding";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkxMesh> mesh;  // offset 24
    std::string originalSkeletonName;  // offset 32
    std::string name;  // offset 40
    std::shared_ptr<hkaSkeleton> skeleton;  // offset 48
    std::vector<hkaMeshBindingMapping> mappings;  // offset 56
    std::vector<hkTransform> boneFromSkinMeshTransforms;  // offset 72
};

/// Havok type "hkaAnimationContainer"
/// byte_size=104, alignment=8, is_pod=False
struct hkaAnimationContainer : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaAnimationContainer";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkaSkeleton>> skeletons;  // offset 24
    std::vector<std::shared_ptr<hkaAnimation>> animations;  // offset 40
    std::vector<std::shared_ptr<hkaAnimationBinding>> bindings;  // offset 56
    std::vector<std::shared_ptr<hkaBoneAttachment>> attachments;  // offset 72
    std::vector<std::shared_ptr<hkaMeshBinding>> skins;  // offset 88
};

/// Havok type "hkaDefaultAnimatedReferenceFrame"
/// byte_size=96, alignment=16, is_pod=False
struct hkaDefaultAnimatedReferenceFrame : hkaAnimatedReferenceFrame
{
    static constexpr std::string_view TypeName = "hkaDefaultAnimatedReferenceFrame";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkVector4 up{};  // offset 32
    hkVector4 forward{};  // offset 48
    float duration{};  // offset 64
    std::vector<hkVector4> referenceFrameSamples;  // offset 72
};

/// Havok type "hkaInterleavedUncompressedAnimation"
/// byte_size=88, alignment=8, is_pod=False
struct hkaInterleavedUncompressedAnimation : hkaAnimation
{
    static constexpr std::string_view TypeName = "hkaInterleavedUncompressedAnimation";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkQsTransform> transforms;  // offset 56
    std::vector<float> floats;  // offset 72
};

/// Havok type "hkaSkeletonMapperData::PartitionMappingRange"  (Python class: hkaSkeletonMapperDataPartitionMappingRange)
/// byte_size=8, alignment=4, is_pod=True
struct hkaSkeletonMapperDataPartitionMappingRange
{
    int32_t startMappingIndex{};  // offset 0
    int32_t numMappings{};  // offset 4
};
static_assert(sizeof(hkaSkeletonMapperDataPartitionMappingRange) == 8,
              "Layout mismatch for hkaSkeletonMapperDataPartitionMappingRange");

/// Havok type "hkaSkeletonMapperData::SimpleMapping"  (Python class: hkaSkeletonMapperDataSimpleMapping)
/// byte_size=64, alignment=16, is_pod=True
struct hkaSkeletonMapperDataSimpleMapping
{
    int16_t boneA{};  // offset 0
    int16_t boneB{};  // offset 2
    hkQsTransform aFromBTransform{};  // offset 16
};
static_assert(sizeof(hkaSkeletonMapperDataSimpleMapping) == 64,
              "Layout mismatch for hkaSkeletonMapperDataSimpleMapping");

/// Havok type "hkaSkeletonMapperData::ChainMapping"  (Python class: hkaSkeletonMapperDataChainMapping)
/// byte_size=112, alignment=16, is_pod=True
struct hkaSkeletonMapperDataChainMapping
{
    int16_t startBoneA{};  // offset 0
    int16_t endBoneA{};  // offset 2
    int16_t startBoneB{};  // offset 4
    int16_t endBoneB{};  // offset 6
    hkQsTransform startAFromBTransform{};  // offset 16
    hkQsTransform endAFromBTransform{};  // offset 64
};
static_assert(sizeof(hkaSkeletonMapperDataChainMapping) == 112,
              "Layout mismatch for hkaSkeletonMapperDataChainMapping");

/// Havok type "hkaSkeletonMapperData"
/// byte_size=176, alignment=16, is_pod=False
struct hkaSkeletonMapperData
{
    std::shared_ptr<hkaSkeleton> skeletonA;  // offset 0
    std::shared_ptr<hkaSkeleton> skeletonB;  // offset 8
    std::vector<int16_t> partitionMap;  // offset 16
    std::vector<hkaSkeletonMapperDataPartitionMappingRange> simpleMappingPartitionRanges;  // offset 32
    std::vector<hkaSkeletonMapperDataPartitionMappingRange> chainMappingPartitionRanges;  // offset 48
    std::vector<hkaSkeletonMapperDataSimpleMapping> simpleMappings;  // offset 64
    std::vector<hkaSkeletonMapperDataChainMapping> chainMappings;  // offset 80
    std::vector<int16_t> unmappedBones;  // offset 96
    hkQsTransform extractedMotionMapping{};  // offset 112
    bool keepUnmappedLocal{};  // offset 160
    int32_t mappingType{};  // offset 164
};

/// Havok type "hkaSkeletonMapper"
/// byte_size=208, alignment=16, is_pod=False
struct hkaSkeletonMapper : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkaSkeletonMapper";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkaSkeletonMapperData mapping;  // offset 32
};

/// Havok type "hkaSkeletonMapperData::MappingType"  (Python class: hkaSkeletonMapperDataMappingType)
/// byte_size=4, alignment=4, is_pod=True
using hkaSkeletonMapperDataMappingType = ERROR;  // Havok enum/alias

/// Havok type "hkaSplineCompressedAnimation"
/// byte_size=184, alignment=8, is_pod=False
struct hkaSplineCompressedAnimation : hkaAnimation
{
    static constexpr std::string_view TypeName = "hkaSplineCompressedAnimation";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int32_t numFrames{};  // offset 64
    int32_t numBlocks{};  // offset 68
    int32_t maxFramesPerBlock{};  // offset 72
    int32_t maskAndQuantizationSize{};  // offset 76
    float blockDuration{};  // offset 80
    float blockInverseDuration{};  // offset 84
    float frameDuration{};  // offset 88
    std::vector<uint32_t> blockOffsets;  // offset 96
    std::vector<uint32_t> floatBlockOffsets;  // offset 112
    std::vector<uint32_t> transformOffsets;  // offset 128
    std::vector<uint32_t> floatOffsets;  // offset 144
    std::vector<uint8_t> data;  // offset 160
    int32_t endian{};  // offset 176
};

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterHkaDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing