// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

struct hkAssetRefPtr;  // cross-folder forward declaration

/// Havok type "hkbVariableBindingSet::Binding"  (Python class: hkbVariableBindingSetBinding)
/// byte_size=40, alignment=8, is_pod=False
struct hkbVariableBindingSetBinding
{
    std::string memberPath;  // offset 0
    std::shared_ptr<void*> memberType;  // offset 8 [not serialized (null)]
    int32_t offsetInObjectPlusOne{};  // offset 16 [not serialized (null)]
    int32_t offsetInArrayPlusOne{};  // offset 20 [not serialized (null)]
    int32_t rootVariableIndex{};  // offset 24 [not serialized (null)]
    int32_t variableIndex{};  // offset 28
    int8_t bitIndex{};  // offset 32
    int8_t bindingType{};  // offset 33
    int8_t variableType{};  // offset 34 [not serialized (null)]
    int8_t flags{};  // offset 35 [not serialized (null)]
};

/// Havok type "hkbVariableBindingSet"
/// byte_size=48, alignment=8, is_pod=False
struct hkbVariableBindingSet : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbVariableBindingSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbVariableBindingSetBinding> bindings;  // offset 24
    int32_t indexOfBindingToEnable{};  // offset 40
    bool hasOutputBinding{};  // offset 44 [not serialized (null)]
    bool initializedOffsets{};  // offset 45 [not serialized (null)]
};

/// Havok type "hkbBindable"
/// byte_size=56, alignment=8, is_pod=False
struct hkbBindable : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbBindable";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkbVariableBindingSet> variableBindingSet;  // offset 24
    std::vector<void*> cachedBindables;  // offset 32 [not serialized (null)]
    bool areBindablesCached{};  // offset 48 [not serialized (null)]
    bool hasEnableChanged{};  // offset 49 [not serialized (null)]
};

/// Havok type "hkbNode"
/// byte_size=96, alignment=8, is_pod=False
struct hkbNode : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbNode";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint64_t userData{};  // offset 64
    std::string name;  // offset 72
    uint16_t id{};  // offset 80 [not serialized (null)]
    int8_t cloneState{};  // offset 82 [not serialized (null)]
    uint8_t type{};  // offset 83 [not serialized (null)]
    std::shared_ptr<void*> nodeInfo;  // offset 88 [not serialized (null)]
};

/// Havok type "hkbGeneratorPartitionInfo"
/// byte_size=40, alignment=4, is_pod=True
struct hkbGeneratorPartitionInfo
{
    std::array<uint32_t, 8> boneMask;  // offset 0
    std::array<uint32_t, 1> partitionMask;  // offset 32
    int16_t numBones{};  // offset 36
    int16_t numMaxPartitions{};  // offset 38
};
static_assert(sizeof(hkbGeneratorPartitionInfo) == 40,
              "Layout mismatch for hkbGeneratorPartitionInfo");

/// Havok type "hkbGenerator"
/// byte_size=152, alignment=8, is_pod=False
struct hkbGenerator : hkbNode
{
    static constexpr std::string_view TypeName = "hkbGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkbGeneratorPartitionInfo partitionInfo;  // offset 96 [not serialized (null)]
    std::shared_ptr<void*> syncInfo;  // offset 136 [not serialized (null)]
    std::array<int8_t, 4> pad;  // offset 144 [not serialized (null)]
};

/// Havok type "hkbRoleAttribute"
/// byte_size=4, alignment=2, is_pod=True
struct hkbRoleAttribute
{
    int16_t role{};  // offset 0
    int16_t flags{};  // offset 2
};
static_assert(sizeof(hkbRoleAttribute) == 4,
              "Layout mismatch for hkbRoleAttribute");

/// Havok type "hkbVariableInfo"
/// byte_size=6, alignment=2, is_pod=True
struct hkbVariableInfo
{
    hkbRoleAttribute role;  // offset 0
    int8_t type{};  // offset 4
};
static_assert(sizeof(hkbVariableInfo) == 6,
              "Layout mismatch for hkbVariableInfo");

/// Havok type "hkbEventInfo"
/// byte_size=4, alignment=4, is_pod=True
struct hkbEventInfo
{
    uint32_t flags{};  // offset 0
};
static_assert(sizeof(hkbEventInfo) == 4,
              "Layout mismatch for hkbEventInfo");

/// Havok type "hkbVariableValue"
/// byte_size=4, alignment=4, is_pod=True
struct hkbVariableValue
{
    int32_t value{};  // offset 0
};
static_assert(sizeof(hkbVariableValue) == 4,
              "Layout mismatch for hkbVariableValue");

/// Havok type "hkbVariableBounds"
/// byte_size=8, alignment=4, is_pod=False
struct hkbVariableBounds
{
    hkbVariableValue min;  // offset 0
    hkbVariableValue max;  // offset 4
};

/// Havok type "hkbVariableValueSet"
/// byte_size=72, alignment=8, is_pod=False
struct hkbVariableValueSet : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbVariableValueSet";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbVariableValue> wordVariableValues;  // offset 24
    std::vector<hkVector4> quadVariableValues;  // offset 40
    std::vector<std::shared_ptr<hkReferencedObject>> variantVariableValues;  // offset 56
};

/// Havok type "hkbBehaviorGraphStringData"
/// byte_size=104, alignment=8, is_pod=False
struct hkbBehaviorGraphStringData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbBehaviorGraphStringData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::string> eventNames;  // offset 24
    std::vector<std::string> attributeNames;  // offset 40
    std::vector<std::string> variableNames;  // offset 56
    std::vector<std::string> characterPropertyNames;  // offset 72
    std::vector<std::string> animationNames;  // offset 88
};

/// Havok type "hkbBehaviorGraphData"
/// byte_size=120, alignment=8, is_pod=False
struct hkbBehaviorGraphData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbBehaviorGraphData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<float> attributeDefaults;  // offset 24
    std::vector<hkbVariableInfo> variableInfos;  // offset 40
    std::vector<hkbVariableInfo> characterPropertyInfos;  // offset 56
    std::vector<hkbEventInfo> eventInfos;  // offset 72
    std::vector<hkbVariableBounds> variableBounds;  // offset 88
    std::shared_ptr<hkbVariableValueSet> variableInitialValues;  // offset 104
    std::shared_ptr<hkbBehaviorGraphStringData> stringData;  // offset 112
};

/// Havok type "hkbBehaviorGraph"
/// byte_size=440, alignment=8, is_pod=False
struct hkbBehaviorGraph : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbBehaviorGraph";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int8_t variableMode{};  // offset 152
    std::vector<void*> uniqueIdPool;  // offset 160 [not serialized (null)]
    std::shared_ptr<void*> idToStateMachineTemplateMap;  // offset 176 [not serialized (null)]
    std::shared_ptr<void*> mirroredExternalIdMap;  // offset 184 [not serialized (null)]
    std::shared_ptr<void*> pseudoRandomGenerator;  // offset 192 [not serialized (null)]
    std::shared_ptr<hkbGenerator> rootGenerator;  // offset 200
    std::shared_ptr<hkbBehaviorGraphData> data;  // offset 208
    hkAssetRefPtr template;  // offset 216 [not serialized (null)]
    std::shared_ptr<void*> activeNodes;  // offset 224 [not serialized (null)]
    std::shared_ptr<void*> globalTransitionData;  // offset 232 [not serialized (null)]
    std::shared_ptr<void*> eventIdMap;  // offset 240 [not serialized (null)]
    std::shared_ptr<void*> attributeIdMap;  // offset 248 [not serialized (null)]
    std::shared_ptr<void*> variableIdMap;  // offset 256 [not serialized (null)]
    std::shared_ptr<void*> characterPropertyIdMap;  // offset 264 [not serialized (null)]
    std::shared_ptr<void*> animationIdMap;  // offset 272 [not serialized (null)]
    std::shared_ptr<void*> variableValueSet;  // offset 280 [not serialized (null)]
    std::shared_ptr<void*> nodeTemplateToCloneMap;  // offset 288 [not serialized (null)]
    std::shared_ptr<void*> stateListenerTemplateToCloneMap;  // offset 296 [not serialized (null)]
    std::vector<void*> recentlyCreatedClones;  // offset 304 [not serialized (null)]
    std::shared_ptr<void*> nodePartitionInfo;  // offset 320 [not serialized (null)]
    int32_t numIntermediateOutputs{};  // offset 328 [not serialized (null)]
    std::vector<void*> intermediateOutputSizes;  // offset 336 [not serialized (null)]
    std::vector<void*> jobs;  // offset 352 [not serialized (null)]
    std::vector<void*> allPartitionMemory;  // offset 368 [not serialized (null)]
    std::vector<void*> internalToRootVariableIdMap;  // offset 384 [not serialized (null)]
    std::vector<void*> internalToCharacterCharacterPropertyIdMap;  // offset 400 [not serialized (null)]
    std::vector<void*> internalToRootAttributeIdMap;  // offset 416 [not serialized (null)]
    uint16_t nextUniqueId{};  // offset 432 [not serialized (null)]
    bool isActive{};  // offset 434 [not serialized (null)]
    bool isLinked{};  // offset 435 [not serialized (null)]
    bool updateActiveNodes{};  // offset 436 [not serialized (null)]
    bool updateActiveNodesForEnable{};  // offset 437 [not serialized (null)]
    bool checkNodeValidity{};  // offset 438 [not serialized (null)]
    bool stateOrTransitionChanged{};  // offset 439 [not serialized (null)]
};

/// Havok type "hkbBehaviorGraph::VariableMode"  (Python class: hkbBehaviorGraphVariableMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbBehaviorGraphVariableMode = ERROR;  // Havok enum/alias

/// Havok type "hkbBlendCurveUtils::BlendCurve"  (Python class: hkbBlendCurveUtilsBlendCurve)
/// byte_size=4, alignment=4, is_pod=True
using hkbBlendCurveUtilsBlendCurve = ERROR;  // Havok enum/alias

/// Havok type "hkbBoneWeightArray"
/// byte_size=72, alignment=8, is_pod=False
struct hkbBoneWeightArray : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbBoneWeightArray";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<float> boneWeights;  // offset 56
};

/// Havok type "hkbBlenderGeneratorChild"
/// byte_size=96, alignment=16, is_pod=False
struct hkbBlenderGeneratorChild : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbBlenderGeneratorChild";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkbGenerator> generator;  // offset 64
    std::shared_ptr<hkbBoneWeightArray> boneWeights;  // offset 72
    float weight{};  // offset 80
    float worldFromModelWeight{};  // offset 84
};

/// Havok type "hkbBlenderGenerator"
/// byte_size=240, alignment=8, is_pod=False
struct hkbBlenderGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbBlenderGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    float referencePoseWeightThreshold{};  // offset 152
    float blendParameter{};  // offset 156
    float minCyclicBlendParameter{};  // offset 160
    float maxCyclicBlendParameter{};  // offset 164
    int16_t indexOfSyncMasterChild{};  // offset 168
    int16_t flags{};  // offset 170
    bool subtractLastChild{};  // offset 172
    std::vector<std::shared_ptr<hkbBlenderGeneratorChild>> children;  // offset 176
    std::vector<void*> childrenInternalStates;  // offset 192 [not serialized (null)]
    std::vector<void*> sortedChildren;  // offset 208 [not serialized (null)]
    float endIntervalWeight{};  // offset 224 [not serialized (null)]
    int32_t numActiveChildren{};  // offset 228 [not serialized (null)]
    int16_t beginIntervalIndex{};  // offset 232 [not serialized (null)]
    int16_t endIntervalIndex{};  // offset 234 [not serialized (null)]
    bool initSync{};  // offset 236 [not serialized (null)]
    bool doSubtractiveBlend{};  // offset 237 [not serialized (null)]
};

/// Havok type "hkbTransitionEffect"
/// byte_size=184, alignment=8, is_pod=False
struct hkbTransitionEffect : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbTransitionEffect";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int8_t selfTransitionMode{};  // offset 152
    int8_t eventMode{};  // offset 153
    int8_t defaultEventMode{};  // offset 154 [not serialized (null)]
    std::shared_ptr<void*> patchedBindingInfo;  // offset 160 [not serialized (null)]
    std::shared_ptr<void*> fromGenerator;  // offset 168 [not serialized (null)]
    std::shared_ptr<void*> toGenerator;  // offset 176 [not serialized (null)]
};

/// Havok type "hkbBlendingTransitionEffect"
/// byte_size=352, alignment=16, is_pod=False
struct hkbBlendingTransitionEffect : hkbTransitionEffect
{
    static constexpr std::string_view TypeName = "hkbBlendingTransitionEffect";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    float duration{};  // offset 184
    float toGeneratorStartTimeFraction{};  // offset 188
    uint16_t flags{};  // offset 192
    int8_t endMode{};  // offset 194
    int8_t blendCurve{};  // offset 195
    int16_t alignmentBone{};  // offset 196
    hkVector4 fromPos{};  // offset 208 [not serialized (null)]
    hkQuaternion fromRot{};  // offset 224 [not serialized (null)]
    hkVector4 toPos{};  // offset 240 [not serialized (null)]
    hkQuaternion toRot{};  // offset 256 [not serialized (null)]
    hkVector4 lastPos{};  // offset 272 [not serialized (null)]
    hkQuaternion lastRot{};  // offset 288 [not serialized (null)]
    std::vector<void*> characterPoseAtBeginningOfTransition;  // offset 304 [not serialized (null)]
    float timeRemaining{};  // offset 320 [not serialized (null)]
    float timeInTransition{};  // offset 324 [not serialized (null)]
    int8_t toGeneratorSelfTranstitionMode{};  // offset 328 [not serialized (null)]
    bool initializeCharacterPose{};  // offset 329 [not serialized (null)]
    bool alignThisFrame{};  // offset 330 [not serialized (null)]
    bool alignmentFinished{};  // offset 331 [not serialized (null)]
    std::shared_ptr<void*> parentStateMachine;  // offset 336 [not serialized (null)]
    bool toGeneratorIsCurrentState{};  // offset 344 [not serialized (null)]
};

/// Havok type "hkbBlendingTransitionEffect::EndMode"  (Python class: hkbBlendingTransitionEffectEndMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbBlendingTransitionEffectEndMode = ERROR;  // Havok enum/alias

/// Havok type "hkbBlendingTransitionEffect::FlagBits"  (Python class: hkbBlendingTransitionEffectFlagBits)
/// byte_size=4, alignment=4, is_pod=True
using hkbBlendingTransitionEffectFlagBits = ERROR;  // Havok enum/alias

/// Havok type "hkbBoneIndexArray"
/// byte_size=72, alignment=8, is_pod=False
struct hkbBoneIndexArray : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbBoneIndexArray";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<int16_t> boneIndices;  // offset 56
};

/// Havok type "hkbEventPayload"
/// byte_size=24, alignment=8, is_pod=True
struct hkbEventPayload : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbEventPayload";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};
static_assert(sizeof(hkbEventPayload) == 24,
              "Layout mismatch for hkbEventPayload");

/// Havok type "hkbEventBase"
/// byte_size=16, alignment=8, is_pod=False
struct hkbEventBase
{
    int32_t id{};  // offset 0
    std::shared_ptr<hkbEventPayload> payload;  // offset 8
};

/// Havok type "hkbEventProperty"
/// byte_size=16, alignment=8, is_pod=False
struct hkbEventProperty : hkbEventBase
{
};

/// Havok type "hkbClipTrigger"
/// byte_size=32, alignment=8, is_pod=False
struct hkbClipTrigger
{
    float localTime{};  // offset 0
    hkbEventProperty event;  // offset 8
    bool relativeToEndOfClip{};  // offset 24
    bool acyclic{};  // offset 25
    bool isAnnotation{};  // offset 26
};

/// Havok type "hkbClipTriggerArray"
/// byte_size=40, alignment=8, is_pod=False
struct hkbClipTriggerArray : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbClipTriggerArray";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbClipTrigger> triggers;  // offset 24
};

/// Havok type "hkbClipGenerator"
/// byte_size=352, alignment=16, is_pod=False
struct hkbClipGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbClipGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::string animationName;  // offset 152
    std::shared_ptr<hkbClipTriggerArray> triggers;  // offset 160
    uint32_t userPartitionMask{};  // offset 168
    float cropStartAmountLocalTime{};  // offset 172
    float cropEndAmountLocalTime{};  // offset 176
    float startTime{};  // offset 180
    float playbackSpeed{};  // offset 184
    float enforcedDuration{};  // offset 188
    float userControlledTimeFraction{};  // offset 192
    int8_t mode{};  // offset 196
    int8_t flags{};  // offset 197
    int16_t animationInternalId{};  // offset 198
    std::vector<void*> animDatas;  // offset 200 [not serialized (null)]
    std::shared_ptr<void*> animationControl;  // offset 216 [not serialized (null)]
    std::shared_ptr<void*> originalTriggers;  // offset 224 [not serialized (null)]
    std::shared_ptr<void*> mapperData;  // offset 232 [not serialized (null)]
    std::shared_ptr<void*> binding;  // offset 240 [not serialized (null)]
    int32_t numAnimationTracks{};  // offset 248 [not serialized (null)]
    hkQsTransform extractedMotion{};  // offset 256 [not serialized (null)]
    std::vector<void*> echos;  // offset 304 [not serialized (null)]
    float localTime{};  // offset 320 [not serialized (null)]
    float time{};  // offset 324 [not serialized (null)]
    float previousUserControlledTimeFraction{};  // offset 328 [not serialized (null)]
    int32_t bufferSize{};  // offset 332 [not serialized (null)]
    bool atEnd{};  // offset 336 [not serialized (null)]
    bool ignoreStartTime{};  // offset 337 [not serialized (null)]
    bool pingPongBackward{};  // offset 338 [not serialized (null)]
};

/// Havok type "hkbClipGenerator::PlaybackMode"  (Python class: hkbClipGeneratorPlaybackMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbClipGeneratorPlaybackMode = ERROR;  // Havok enum/alias

/// Havok type "hkbCondition"
/// byte_size=24, alignment=8, is_pod=True
struct hkbCondition : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbCondition";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};
static_assert(sizeof(hkbCondition) == 24,
              "Layout mismatch for hkbCondition");

/// Havok type "hkbCustomIdSelector"
/// byte_size=24, alignment=8, is_pod=True
struct hkbCustomIdSelector : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbCustomIdSelector";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};
static_assert(sizeof(hkbCustomIdSelector) == 24,
              "Layout mismatch for hkbCustomIdSelector");

/// Havok type "hkbEvent"
/// byte_size=24, alignment=8, is_pod=False
struct hkbEvent : hkbEventBase
{
    std::shared_ptr<void*> sender;  // offset 16 [not serialized (null)]
};

/// Havok type "hkbEventDrivenBlendingObject::InternalState"  (Python class: hkbEventDrivenBlendingObjectInternalState)
/// byte_size=20, alignment=4, is_pod=True
struct hkbEventDrivenBlendingObjectInternalState
{
    float weight{};  // offset 0
    float timeElapsed{};  // offset 4
    float onFraction{};  // offset 8
    float onFractionOffset{};  // offset 12
    int8_t fadingState{};  // offset 16
};
static_assert(sizeof(hkbEventDrivenBlendingObjectInternalState) == 20,
              "Layout mismatch for hkbEventDrivenBlendingObjectInternalState");

/// Havok type "hkbEventDrivenBlendingObject"
/// byte_size=44, alignment=4, is_pod=False
struct hkbEventDrivenBlendingObject
{
    float weight{};  // offset 0
    float fadeInDuration{};  // offset 4
    float fadeOutDuration{};  // offset 8
    int32_t onEventId{};  // offset 12
    int32_t offEventId{};  // offset 16
    bool onByDefault{};  // offset 20
    bool forceFullFadeDurations{};  // offset 21
    int8_t fadeInOutCurve{};  // offset 22
    hkbEventDrivenBlendingObjectInternalState internalState;  // offset 24 [not serialized (null)]
};

/// Havok type "hkbEventDrivenBlendingObject::InternalState::FadingState"  (Python class: hkbEventDrivenBlendingObjectInternalStateFadingState)
/// byte_size=4, alignment=4, is_pod=True
using hkbEventDrivenBlendingObjectInternalStateFadingState = ERROR;  // Havok enum/alias

/// Havok type "hkbEventInfo::Flags"  (Python class: hkbEventInfoFlags)
/// byte_size=4, alignment=4, is_pod=True
using hkbEventInfoFlags = ERROR;  // Havok enum/alias

/// Havok type "hkbHoldFromBlendingTransitionEffect"
/// byte_size=432, alignment=16, is_pod=False
struct hkbHoldFromBlendingTransitionEffect : hkbBlendingTransitionEffect
{
    static constexpr std::string_view TypeName = "hkbHoldFromBlendingTransitionEffect";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<void*> heldFromPose;  // offset 352 [not serialized (null)]
    int32_t heldFromPoseSize{};  // offset 360 [not serialized (null)]
    hkQsTransform heldWorldFromModel{};  // offset 368 [not serialized (null)]
    std::shared_ptr<void*> heldFromSkeleton;  // offset 416 [not serialized (null)]
    int8_t additiveFlag{};  // offset 424 [not serialized (null)]
};

/// Havok type "hkbModifier"
/// byte_size=104, alignment=8, is_pod=False
struct hkbModifier : hkbNode
{
    static constexpr std::string_view TypeName = "hkbModifier";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    bool enable{};  // offset 96
    std::array<bool, 3> padModifier;  // offset 97 [not serialized (null)]
};

/// Havok type "hkbKeyframeBonesModifier::KeyframeInfo"  (Python class: hkbKeyframeBonesModifierKeyframeInfo)
/// byte_size=48, alignment=16, is_pod=True
struct hkbKeyframeBonesModifierKeyframeInfo
{
    hkVector4 keyframedPosition{};  // offset 0
    hkQuaternion keyframedRotation{};  // offset 16
    int16_t boneIndex{};  // offset 32
    bool isValid{};  // offset 34
};
static_assert(sizeof(hkbKeyframeBonesModifierKeyframeInfo) == 48,
              "Layout mismatch for hkbKeyframeBonesModifierKeyframeInfo");

/// Havok type "hkbKeyframeBonesModifier"
/// byte_size=128, alignment=8, is_pod=False
struct hkbKeyframeBonesModifier : hkbModifier
{
    static constexpr std::string_view TypeName = "hkbKeyframeBonesModifier";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbKeyframeBonesModifierKeyframeInfo> keyframeInfo;  // offset 104
    std::shared_ptr<hkbBoneIndexArray> keyframedBonesList;  // offset 120
};

/// Havok type "hkbLayer"
/// byte_size=128, alignment=16, is_pod=False
struct hkbLayer : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbLayer";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkbGenerator> generator;  // offset 64
    std::shared_ptr<hkbBoneWeightArray> boneWeights;  // offset 72
    bool useMotion{};  // offset 80
    hkbEventDrivenBlendingObject blendingControlData;  // offset 84
};

/// Havok type "hkbLayerGenerator"
/// byte_size=200, alignment=8, is_pod=False
struct hkbLayerGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbLayerGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkbLayer>> layers;  // offset 152
    int16_t indexOfSyncMasterChild{};  // offset 168
    uint16_t flags{};  // offset 170
    int32_t numActiveLayers{};  // offset 172 [not serialized (null)]
    std::vector<void*> layerInternalStates;  // offset 176 [not serialized (null)]
    bool initSync{};  // offset 192 [not serialized (null)]
};

/// Havok type "hkbLayerGenerator::LayerFlagBits"  (Python class: hkbLayerGeneratorLayerFlagBits)
/// byte_size=4, alignment=4, is_pod=True
using hkbLayerGeneratorLayerFlagBits = ERROR;  // Havok enum/alias

/// Havok type "hkbManualSelectorGenerator"
/// byte_size=264, alignment=8, is_pod=False
struct hkbManualSelectorGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbManualSelectorGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkbGenerator>> generators;  // offset 152
    int16_t selectedGeneratorIndex{};  // offset 168
    std::shared_ptr<hkbCustomIdSelector> indexSelector;  // offset 176
    bool selectedIndexCanChangeAfterActivate{};  // offset 184
    std::shared_ptr<hkbTransitionEffect> generatorChangedTransitionEffect;  // offset 192
    hkbEventProperty sentOnClipEnd;  // offset 200
    std::vector<int16_t> generatorPreDeleteIndex;  // offset 216
    int16_t currentGeneratorIndex{};  // offset 232 [not serialized (null)]
    int16_t generatorIndexAtActivate{};  // offset 234 [not serialized (null)]
    std::vector<void*> activeTransitions;  // offset 240 [not serialized (null)]
    int32_t endOfClipEventId{};  // offset 256
};

/// Havok type "hkbModifierGenerator"
/// byte_size=168, alignment=8, is_pod=False
struct hkbModifierGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbModifierGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkbModifier> modifier;  // offset 152
    std::shared_ptr<hkbGenerator> generator;  // offset 160
};

/// Havok type "hkbModifierList"
/// byte_size=120, alignment=8, is_pod=False
struct hkbModifierList : hkbModifier
{
    static constexpr std::string_view TypeName = "hkbModifierList";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkbModifier>> modifiers;  // offset 104
};

/// Havok type "hkbNode::CloneState"  (Python class: hkbNodeCloneState)
/// byte_size=4, alignment=4, is_pod=True
using hkbNodeCloneState = ERROR;  // Havok enum/alias

/// Havok type "hkbNodeType"
/// byte_size=4, alignment=4, is_pod=True
using hkbNodeType = ERROR;  // Havok enum/alias

/// Havok type "hkbProjectStringData"
/// byte_size=120, alignment=8, is_pod=False
struct hkbProjectStringData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbProjectStringData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::string> behaviorFilenames;  // offset 24
    std::vector<std::string> characterFilenames;  // offset 40
    std::vector<std::string> eventNames;  // offset 56
    std::string animationPath;  // offset 72
    std::string behaviorPath;  // offset 80
    std::string characterPath;  // offset 88
    std::string scriptsPath;  // offset 96
    std::string fullPathToSource;  // offset 104
    std::string rootPath;  // offset 112 [not serialized (null)]
};

/// Havok type "hkbProjectData"
/// byte_size=64, alignment=16, is_pod=False
struct hkbProjectData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbProjectData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkVector4 worldUpWS{};  // offset 32
    std::shared_ptr<hkbProjectStringData> stringData;  // offset 48
    int8_t defaultEventMode{};  // offset 56
};

/// Havok type "hkbReferencePoseGenerator"
/// byte_size=160, alignment=8, is_pod=False
struct hkbReferencePoseGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbReferencePoseGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<void*> skeleton;  // offset 152 [not serialized (null)]
};

/// Havok type "hkbRoleAttribute::Role"  (Python class: hkbRoleAttributeRole)
/// byte_size=4, alignment=4, is_pod=True
using hkbRoleAttributeRole = ERROR;  // Havok enum/alias

/// Havok type "hkbRoleAttribute::RoleFlags"  (Python class: hkbRoleAttributeRoleFlags)
/// byte_size=4, alignment=4, is_pod=True
using hkbRoleAttributeRoleFlags = ERROR;  // Havok enum/alias

/// Havok type "hkbScriptGenerator"
/// byte_size=224, alignment=8, is_pod=False
struct hkbScriptGenerator : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbScriptGenerator";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkbGenerator> child;  // offset 152
    std::string onActivateScript;  // offset 160
    std::string onPreUpdateScript;  // offset 168
    std::string onGenerateScript;  // offset 176
    std::string onHandleEventScript;  // offset 184
    std::string onDeactivateScript;  // offset 192
    int32_t refOnActivate{};  // offset 200 [not serialized (null)]
    int32_t refOnPreUpdate{};  // offset 204 [not serialized (null)]
    int32_t refOnGenerate{};  // offset 208 [not serialized (null)]
    int32_t refOnHandleEvent{};  // offset 212 [not serialized (null)]
    int32_t refOnDeactivate{};  // offset 216 [not serialized (null)]
    float timeStep{};  // offset 220 [not serialized (null)]
};

/// Havok type "hkbStateListener"
/// byte_size=24, alignment=8, is_pod=True
struct hkbStateListener : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbStateListener";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

};
static_assert(sizeof(hkbStateListener) == 24,
              "Layout mismatch for hkbStateListener");

/// Havok type "hkbStateMachine::EventPropertyArray"  (Python class: hkbStateMachineEventPropertyArray)
/// byte_size=40, alignment=8, is_pod=False
struct hkbStateMachineEventPropertyArray : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbStateMachine::EventPropertyArray";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbEventProperty> events;  // offset 24
};

/// Havok type "hkbStateMachine::TimeInterval"  (Python class: hkbStateMachineTimeInterval)
/// byte_size=16, alignment=4, is_pod=True
struct hkbStateMachineTimeInterval
{
    int32_t enterEventId{};  // offset 0
    int32_t exitEventId{};  // offset 4
    float enterTime{};  // offset 8
    float exitTime{};  // offset 12
};
static_assert(sizeof(hkbStateMachineTimeInterval) == 16,
              "Layout mismatch for hkbStateMachineTimeInterval");

/// Havok type "hkbStateMachine::TransitionInfo"  (Python class: hkbStateMachineTransitionInfo)
/// byte_size=72, alignment=8, is_pod=False
struct hkbStateMachineTransitionInfo
{
    hkbStateMachineTimeInterval triggerInterval;  // offset 0
    hkbStateMachineTimeInterval initiateInterval;  // offset 16
    std::shared_ptr<hkbTransitionEffect> transition;  // offset 32
    std::shared_ptr<hkbCondition> condition;  // offset 40
    int32_t eventId{};  // offset 48
    int32_t toStateId{};  // offset 52
    int32_t fromNestedStateId{};  // offset 56
    int32_t toNestedStateId{};  // offset 60
    int16_t priority{};  // offset 64
    int16_t flags{};  // offset 66
};

/// Havok type "hkbStateMachine::TransitionInfoArray"  (Python class: hkbStateMachineTransitionInfoArray)
/// byte_size=48, alignment=8, is_pod=False
struct hkbStateMachineTransitionInfoArray : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkbStateMachine::TransitionInfoArray";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<hkbStateMachineTransitionInfo> transitions;  // offset 24
    bool hasEventlessTransitions{};  // offset 40 [not serialized (null)]
    bool hasTimeBoundedTransitions{};  // offset 41 [not serialized (null)]
};

/// Havok type "hkbStateMachine::StateInfo"  (Python class: hkbStateMachineStateInfo)
/// byte_size=128, alignment=8, is_pod=False
struct hkbStateMachineStateInfo : hkbBindable
{
    static constexpr std::string_view TypeName = "hkbStateMachine::StateInfo";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::vector<std::shared_ptr<hkbStateListener>> listeners;  // offset 56
    std::shared_ptr<hkbStateMachineEventPropertyArray> enterNotifyEvents;  // offset 72
    std::shared_ptr<hkbStateMachineEventPropertyArray> exitNotifyEvents;  // offset 80
    std::shared_ptr<hkbStateMachineTransitionInfoArray> transitions;  // offset 88
    std::shared_ptr<hkbGenerator> generator;  // offset 96
    std::string name;  // offset 104
    int32_t stateId{};  // offset 112
    float probability{};  // offset 116
    bool enable{};  // offset 120
    bool hasEventlessTransitions{};  // offset 121 [not serialized (null)]
};

/// Havok type "hkbStateMachine"
/// byte_size=352, alignment=8, is_pod=False
struct hkbStateMachine : hkbGenerator
{
    static constexpr std::string_view TypeName = "hkbStateMachine";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkbEvent eventToSendWhenStateOrTransitionChanges;  // offset 152
    std::shared_ptr<hkbCustomIdSelector> startStateIdSelector;  // offset 176
    int32_t startStateId{};  // offset 184
    int32_t returnToPreviousStateEventId{};  // offset 188
    int32_t randomTransitionEventId{};  // offset 192
    int32_t transitionToNextHigherStateEventId{};  // offset 196
    int32_t transitionToNextLowerStateEventId{};  // offset 200
    int32_t syncVariableIndex{};  // offset 204
    int32_t currentStateId{};  // offset 208 [not serialized (null)]
    bool wrapAroundStateId{};  // offset 212
    int8_t maxSimultaneousTransitions{};  // offset 213
    int8_t startStateMode{};  // offset 214
    int8_t selfTransitionMode{};  // offset 215
    bool isActive{};  // offset 216 [not serialized (null)]
    std::vector<std::shared_ptr<hkbStateMachineStateInfo>> states;  // offset 224
    std::shared_ptr<hkbStateMachineTransitionInfoArray> wildcardTransitions;  // offset 240
    std::shared_ptr<void*> stateIdToIndexMap;  // offset 248 [not serialized (null)]
    std::vector<void*> activeTransitions;  // offset 256 [not serialized (null)]
    std::vector<void*> transitionFlags;  // offset 272 [not serialized (null)]
    std::vector<void*> wildcardTransitionFlags;  // offset 288 [not serialized (null)]
    std::vector<void*> delayedTransitions;  // offset 304 [not serialized (null)]
    float timeInState{};  // offset 320 [not serialized (null)]
    float lastLocalTime{};  // offset 324 [not serialized (null)]
    int32_t previousStateId{};  // offset 328 [not serialized (null)]
    int32_t nextStartStateIndexOverride{};  // offset 332 [not serialized (null)]
    bool stateOrTransitionChanged{};  // offset 336 [not serialized (null)]
    bool echoNextUpdate{};  // offset 337 [not serialized (null)]
    bool hasEventlessWildcardTransitions{};  // offset 338 [not serialized (null)]
    std::shared_ptr<void*> eventIdToTransitionInfoIndicesMap;  // offset 344 [not serialized (null)]
};

/// Havok type "hkbStateMachine::StartStateMode"  (Python class: hkbStateMachineStartStateMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbStateMachineStartStateMode = ERROR;  // Havok enum/alias

/// Havok type "hkbStateMachine::StateMachineSelfTransitionMode"  (Python class: hkbStateMachineStateMachineSelfTransitionMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbStateMachineStateMachineSelfTransitionMode = ERROR;  // Havok enum/alias

/// Havok type "hkbStateMachine::TransitionInfo::TransitionFlags"  (Python class: hkbStateMachineTransitionInfoTransitionFlags)
/// byte_size=4, alignment=4, is_pod=True
using hkbStateMachineTransitionInfoTransitionFlags = ERROR;  // Havok enum/alias

/// Havok type "hkbTransitionEffect::EventMode"  (Python class: hkbTransitionEffectEventMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbTransitionEffectEventMode = ERROR;  // Havok enum/alias

/// Havok type "hkbTransitionEffect::SelfTransitionMode"  (Python class: hkbTransitionEffectSelfTransitionMode)
/// byte_size=4, alignment=4, is_pod=True
using hkbTransitionEffectSelfTransitionMode = ERROR;  // Havok enum/alias

/// Havok type "hkbVariableBindingSet::Binding::BindingType"  (Python class: hkbVariableBindingSetBindingBindingType)
/// byte_size=4, alignment=4, is_pod=True
using hkbVariableBindingSetBindingBindingType = ERROR;  // Havok enum/alias

/// Havok type "hkbVariableBindingSet::Binding::InternalBindingFlags"  (Python class: hkbVariableBindingSetBindingInternalBindingFlags)
/// byte_size=4, alignment=4, is_pod=True
using hkbVariableBindingSetBindingInternalBindingFlags = ERROR;  // Havok enum/alias

/// Havok type "hkbVariableInfo::VariableType"  (Python class: hkbVariableInfoVariableType)
/// byte_size=4, alignment=4, is_pod=True
using hkbVariableInfoVariableType = ERROR;  // Havok enum/alias

/// Havok type "hkbVerifiable"
/// byte_size=8, alignment=8, is_pod=True
using hkbVerifiable = ERROR;

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterHkbDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing