// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

/// Havok type "hkcdCompressedAabbCodecs::AabbCodecBase"  (Python class: hkcdCompressedAabbCodecsAabbCodecBase)
/// byte_size=1, alignment=1, is_pod=True
struct hkcdCompressedAabbCodecsAabbCodecBase {};  // empty base (Havok alias/enum used as base class)

/// Havok type "hkcdCompressedAabbCodecs::CompressedAabbCodec"  (Python class: hkcdCompressedAabbCodecsCompressedAabbCodec)
/// byte_size=3, alignment=1, is_pod=True
struct hkcdCompressedAabbCodecsCompressedAabbCodec : hkcdCompressedAabbCodecsAabbCodecBase
{
    std::array<uint8_t, 3> xyz;  // offset 0
};
static_assert(sizeof(hkcdCompressedAabbCodecsCompressedAabbCodec) == 3,
              "Layout mismatch for hkcdCompressedAabbCodecsCompressedAabbCodec");

/// Havok type "hkcdCompressedAabbCodecs::Aabb6BytesCodec"  (Python class: hkcdCompressedAabbCodecsAabb6BytesCodec)
/// byte_size=6, alignment=2, is_pod=True
struct hkcdCompressedAabbCodecsAabb6BytesCodec : hkcdCompressedAabbCodecsCompressedAabbCodec
{
    uint8_t hiData{};  // offset 3
    uint16_t loData{};  // offset 4
};
static_assert(sizeof(hkcdCompressedAabbCodecsAabb6BytesCodec) == 6,
              "Layout mismatch for hkcdCompressedAabbCodecsAabb6BytesCodec");

/// Havok type "hkcdStaticTree::AabbTreeBase"  (Python class: hkcdStaticTreeAabbTreeBase)
/// byte_size=1, alignment=1, is_pod=True
struct hkcdStaticTreeAabbTreeBase {};  // empty base (Havok alias/enum used as base class)

/// Havok type "hkcdStaticTree::AabbTree"  (Python class: hkcdStaticTreeAabbTree)
/// byte_size=48, alignment=16, is_pod=False
struct hkcdStaticTreeAabbTree : hkcdStaticTreeAabbTreeBase
{
    std::vector<hkcdCompressedAabbCodecsAabb6BytesCodec> nodes;  // offset 0
    hkAabb domain{};  // offset 16
};

/// Havok type "hkcdStaticTree::Aabb6BytesTree"  (Python class: hkcdStaticTreeAabb6BytesTree)
struct hkcdStaticTreeAabb6BytesTree : hkcdStaticTreeAabbTree
{
};

/// Havok type "hkcdStaticAabbTree::Impl"  (Python class: hkcdStaticAabbTreeImpl)
/// byte_size=80, alignment=16, is_pod=False
struct hkcdStaticAabbTreeImpl : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkcdStaticAabbTree::Impl";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkcdStaticTreeAabb6BytesTree tree;  // offset 32
};

/// Havok type "hkcdStaticAabbTree"
/// byte_size=32, alignment=8, is_pod=False
struct hkcdStaticAabbTree : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkcdStaticAabbTree";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    std::shared_ptr<hkcdStaticAabbTreeImpl> treePtr;  // offset 24
};

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterHkcdDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing