// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#pragma once

#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>
#include <FirelinkCore/Havok/Types.h>
#include <FirelinkCore/Havok/TagfileUnpacker.h>

namespace Firelink::Havok::EldenRing
{

/// Havok type "hkpConstraintAtom"
/// byte_size=16, alignment=61456, is_pod=True
struct hkpConstraintAtom
{
    uint16_t type{};  // offset 0
};
static_assert(sizeof(hkpConstraintAtom) == 16,
              "Layout mismatch for hkpConstraintAtom");

/// Havok type "hkp2dAngConstraintAtom"
/// byte_size=16, alignment=16, is_pod=True
struct hkp2dAngConstraintAtom : hkpConstraintAtom
{
    uint8_t freeRotationAxis{};  // offset 2
};
static_assert(sizeof(hkp2dAngConstraintAtom) == 16,
              "Layout mismatch for hkp2dAngConstraintAtom");

/// Havok type "hkpAngFrictionConstraintAtom"
/// byte_size=16, alignment=16, is_pod=True
struct hkpAngFrictionConstraintAtom : hkpConstraintAtom
{
    uint8_t isEnabled{};  // offset 2
    uint8_t firstFrictionAxis{};  // offset 3
    uint8_t numFrictionAxes{};  // offset 4
    float maxFrictionTorque{};  // offset 8
};
static_assert(sizeof(hkpAngFrictionConstraintAtom) == 16,
              "Layout mismatch for hkpAngFrictionConstraintAtom");

/// Havok type "hkpAngLimitConstraintAtom"
/// byte_size=32, alignment=16, is_pod=True
struct hkpAngLimitConstraintAtom : hkpConstraintAtom
{
    uint8_t isEnabled{};  // offset 2
    uint8_t limitAxis{};  // offset 3
    uint8_t cosineAxis{};  // offset 4
    float minAngle{};  // offset 8
    float maxAngle{};  // offset 12
    float angularLimitsTauFactor{};  // offset 16
    float angularLimitsDampFactor{};  // offset 20
};
static_assert(sizeof(hkpAngLimitConstraintAtom) == 32,
              "Layout mismatch for hkpAngLimitConstraintAtom");

/// Havok type "hkpConstraintMotor"
/// byte_size=24, alignment=8, is_pod=True
struct hkpConstraintMotor : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkpConstraintMotor";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    int8_t type{};  // offset 20
};
static_assert(sizeof(hkpConstraintMotor) == 24,
              "Layout mismatch for hkpConstraintMotor");

/// Havok type "hkpAngMotorConstraintAtom"
/// byte_size=32, alignment=16, is_pod=False
struct hkpAngMotorConstraintAtom : hkpConstraintAtom
{
    bool isEnabled{};  // offset 2
    uint8_t motorAxis{};  // offset 3
    int16_t initializedOffset{};  // offset 4 [not serialized (null)]
    int16_t previousTargetAngleOffset{};  // offset 6 [not serialized (null)]
    std::shared_ptr<hkpConstraintMotor> motor;  // offset 8
    float targetAngle{};  // offset 16
    int16_t correspondingAngLimitSolverResultOffset{};  // offset 20 [not serialized (null)]
};

/// Havok type "hkpBallSocketConstraintAtom"
/// byte_size=16, alignment=16, is_pod=True
struct hkpBallSocketConstraintAtom : hkpConstraintAtom
{
    uint8_t solvingMethod{};  // offset 2
    uint8_t bodiesToNotify{};  // offset 3
    uint8_t velocityStabilizationFactor{};  // offset 4
    bool enableLinearImpulseLimit{};  // offset 5
    float breachImpulse{};  // offset 8
    float inertiaStabilizationFactor{};  // offset 12
};
static_assert(sizeof(hkpBallSocketConstraintAtom) == 16,
              "Layout mismatch for hkpBallSocketConstraintAtom");

/// Havok type "hkpConeLimitConstraintAtom"
/// byte_size=32, alignment=16, is_pod=True
struct hkpConeLimitConstraintAtom : hkpConstraintAtom
{
    uint8_t isEnabled{};  // offset 2
    uint8_t twistAxisInA{};  // offset 3
    uint8_t refAxisInB{};  // offset 4
    uint8_t angleMeasurementMode{};  // offset 5
    uint16_t memOffsetToAngleOffset{};  // offset 6
    float minAngle{};  // offset 8
    float maxAngle{};  // offset 12
    float angularLimitsTauFactor{};  // offset 16
    float angularLimitsDampFactor{};  // offset 20
};
static_assert(sizeof(hkpConeLimitConstraintAtom) == 32,
              "Layout mismatch for hkpConeLimitConstraintAtom");

/// Havok type "hkpConeLimitConstraintAtom::MeasurementMode"  (Python class: hkpConeLimitConstraintAtomMeasurementMode)
/// byte_size=4, alignment=4, is_pod=True
using hkpConeLimitConstraintAtomMeasurementMode = ERROR;  // Havok enum/alias

/// Havok type "hkpConstraintAtom::AtomType"  (Python class: hkpConstraintAtomAtomType)
/// byte_size=4, alignment=4, is_pod=True
using hkpConstraintAtomAtomType = ERROR;  // Havok enum/alias

/// Havok type "hkpConstraintAtom::SolvingMethod"  (Python class: hkpConstraintAtomSolvingMethod)
/// byte_size=4, alignment=4, is_pod=True
using hkpConstraintAtomSolvingMethod = ERROR;  // Havok enum/alias

/// Havok type "hkpConstraintData"
/// byte_size=32, alignment=8, is_pod=True
struct hkpConstraintData : HkReferencedObject
{
    static constexpr std::string_view TypeName = "hkpConstraintData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    uint64_t userData{};  // offset 24
};
static_assert(sizeof(hkpConstraintData) == 32,
              "Layout mismatch for hkpConstraintData");

/// Havok type "hkpConstraintMotor::MotorType"  (Python class: hkpConstraintMotorMotorType)
/// byte_size=4, alignment=4, is_pod=True
using hkpConstraintMotorMotorType = ERROR;  // Havok enum/alias

/// Havok type "hkpLimitedForceConstraintMotor"
/// byte_size=32, alignment=8, is_pod=True
struct hkpLimitedForceConstraintMotor : hkpConstraintMotor
{
    static constexpr std::string_view TypeName = "hkpLimitedForceConstraintMotor";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    float minForce{};  // offset 24
    float maxForce{};  // offset 28
};
static_assert(sizeof(hkpLimitedForceConstraintMotor) == 32,
              "Layout mismatch for hkpLimitedForceConstraintMotor");

/// Havok type "hkpSetLocalTransformsConstraintAtom"
/// byte_size=144, alignment=16, is_pod=True
struct hkpSetLocalTransformsConstraintAtom : hkpConstraintAtom
{
    hkTransform transformA{};  // offset 16
    hkTransform transformB{};  // offset 80
};
static_assert(sizeof(hkpSetLocalTransformsConstraintAtom) == 144,
              "Layout mismatch for hkpSetLocalTransformsConstraintAtom");

/// Havok type "hkpSetupStabilizationAtom"
/// byte_size=16, alignment=16, is_pod=True
struct hkpSetupStabilizationAtom : hkpConstraintAtom
{
    bool enabled{};  // offset 2
    float maxLinImpulse{};  // offset 4
    float maxAngImpulse{};  // offset 8
    float maxAngle{};  // offset 12
};
static_assert(sizeof(hkpSetupStabilizationAtom) == 16,
              "Layout mismatch for hkpSetupStabilizationAtom");

/// Havok type "hkpLimitedHingeConstraintData::Atoms"  (Python class: hkpLimitedHingeConstraintDataAtoms)
/// byte_size=272, alignment=16, is_pod=False
struct hkpLimitedHingeConstraintDataAtoms
{
    hkpSetLocalTransformsConstraintAtom transforms;  // offset 0
    hkpSetupStabilizationAtom setupStabilization;  // offset 144
    hkpAngMotorConstraintAtom angMotor;  // offset 160
    hkpAngFrictionConstraintAtom angFriction;  // offset 192
    hkpAngLimitConstraintAtom angLimit;  // offset 208
    hkp2dAngConstraintAtom _2dAng;  // offset 240
    hkpBallSocketConstraintAtom ballSocket;  // offset 256
};

/// Havok type "hkpLimitedHingeConstraintData"
/// byte_size=304, alignment=16, is_pod=False
struct hkpLimitedHingeConstraintData : hkpConstraintData
{
    static constexpr std::string_view TypeName = "hkpLimitedHingeConstraintData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkpLimitedHingeConstraintDataAtoms atoms;  // offset 32
};

/// Havok type "hkpPositionConstraintMotor"
/// byte_size=48, alignment=8, is_pod=True
struct hkpPositionConstraintMotor : hkpLimitedForceConstraintMotor
{
    static constexpr std::string_view TypeName = "hkpPositionConstraintMotor";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    float tau{};  // offset 32
    float damping{};  // offset 36
    float proportionalRecoveryVelocity{};  // offset 40
    float constantRecoveryVelocity{};  // offset 44
};
static_assert(sizeof(hkpPositionConstraintMotor) == 48,
              "Layout mismatch for hkpPositionConstraintMotor");

/// Havok type "hkpRagdollMotorConstraintAtom"
/// byte_size=96, alignment=16, is_pod=True
struct hkpRagdollMotorConstraintAtom : hkpConstraintAtom
{
    bool isEnabled{};  // offset 2
    int16_t initializedOffset{};  // offset 4 [not serialized (null)]
    int16_t previousTargetAnglesOffset{};  // offset 6 [not serialized (null)]
    hkMatrix3 target_bRca{};  // offset 16
    std::array<std::shared_ptr<hkpConstraintMotor>, 3> motors;  // offset 64
};
static_assert(sizeof(hkpRagdollMotorConstraintAtom) == 96,
              "Layout mismatch for hkpRagdollMotorConstraintAtom");

/// Havok type "hkpTwistLimitConstraintAtom"
/// byte_size=32, alignment=16, is_pod=True
struct hkpTwistLimitConstraintAtom : hkpConstraintAtom
{
    uint8_t isEnabled{};  // offset 2
    uint8_t twistAxis{};  // offset 3
    uint8_t refAxis{};  // offset 4
    float minAngle{};  // offset 8
    float maxAngle{};  // offset 12
    float angularLimitsTauFactor{};  // offset 16
    float angularLimitsDampFactor{};  // offset 20
};
static_assert(sizeof(hkpTwistLimitConstraintAtom) == 32,
              "Layout mismatch for hkpTwistLimitConstraintAtom");

/// Havok type "hkpRagdollConstraintData::Atoms"  (Python class: hkpRagdollConstraintDataAtoms)
/// byte_size=384, alignment=16, is_pod=False
struct hkpRagdollConstraintDataAtoms
{
    hkpSetLocalTransformsConstraintAtom transforms;  // offset 0
    hkpSetupStabilizationAtom setupStabilization;  // offset 144
    hkpRagdollMotorConstraintAtom ragdollMotors;  // offset 160
    hkpAngFrictionConstraintAtom angFriction;  // offset 256
    hkpTwistLimitConstraintAtom twistLimit;  // offset 272
    hkpConeLimitConstraintAtom coneLimit;  // offset 304
    hkpConeLimitConstraintAtom planesLimit;  // offset 336
    hkpBallSocketConstraintAtom ballSocket;  // offset 368
};

/// Havok type "hkpRagdollConstraintData"
/// byte_size=416, alignment=16, is_pod=False
struct hkpRagdollConstraintData : hkpConstraintData
{
    static constexpr std::string_view TypeName = "hkpRagdollConstraintData";
    [[nodiscard]] std::string_view GetTypeName() const noexcept override { return TypeName; }

    hkpRagdollConstraintDataAtoms atoms;  // offset 32
};

// Registers all deserializers for this type set.
// Call from your HKX subclass after constructing TagFileUnpacker.
void RegisterHkpDispatch(TagFileUnpacker& u);

}  // namespace Firelink::Havok::EldenRing