// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkCore/Havok/HkaiTypes.h>
#include <FirelinkCore/Havok/HkcdTypes.h>
#include <FirelinkCore/Havok/Tagfile.h>
#include <cstring>

namespace Firelink::Havok
{

std::shared_ptr<HkObject> Deser_hkaiStreamingSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiStreamingSet>();
    const size_t base = item.absoluteDataOffset;

    r->aSectionUid = u.ReadPodAt<uint32_t>(base + 24);
    r->bSectionUid = u.ReadPodAt<uint32_t>(base + 28);
    r->meshConnections = u.ReadPodArray<hkaiStreamingSetNavMeshConnection>(base + 32);
    r->graphConnections = u.ReadPodArray<hkaiStreamingSetGraphConnection>(base + 48);
    r->volumeConnections = u.ReadPodArray<hkaiStreamingSetVolumeConnection>(base + 64);
    r->aConnectionAabbs = u.ReadPodArray<hkAabb>(base + 80);
    r->bConnectionAabbs = u.ReadPodArray<hkAabb>(base + 96);

    return r;
}

static hkaiAnnotatedStreamingSet Deser_Inline_hkaiAnnotatedStreamingSet(TagFileUnpacker& u, size_t base)
{
    hkaiAnnotatedStreamingSet r{};
    r.side = u.ReadPodAt<uint8_t>(base + 0);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 8);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.streamingSet = std::static_pointer_cast<hkaiStreamingSet>(_obj);
    }
    return r;
}

std::shared_ptr<HkObject> Deser_hkaiNavMeshClearanceCache(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiNavMeshClearanceCache>();
    const size_t base = item.absoluteDataOffset;

    r->clearanceCeiling = u.ReadPodAt<float>(base + 24);
    r->clearanceIntToRealMultiplier = u.ReadPodAt<float>(base + 28);
    r->clearanceRealToIntMultiplier = u.ReadPodAt<float>(base + 32);
    r->faceOffsets = u.ReadPodArray<uint32_t>(base + 40);
    r->edgePairClearances = u.ReadPodArray<uint8_t>(base + 56);
    r->unusedEdgePairElements = u.ReadPodAt<int32_t>(base + 72);
    r->mcpData = u.ReadPodArray<hkaiNavMeshClearanceCacheMcpDataInteger>(base + 80);
    r->vertexClearances = u.ReadPodArray<uint8_t>(base + 96);
    r->uncalculatedFacesLowerBound = u.ReadPodAt<int32_t>(base + 112);

    return r;
}

static hkaiNavMeshClearanceCacheSeedingCacheData Deser_Inline_hkaiNavMeshClearanceCacheSeedingCacheData(TagFileUnpacker& u, size_t base)
{
    hkaiNavMeshClearanceCacheSeedingCacheData r{};
    r.id = u.ReadPodAt<uint64_t>(base + 0);
    r.info = u.ReadPodAt<uint32_t>(base + 8);
    r.infoMask = u.ReadPodAt<uint32_t>(base + 12);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 16);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.initialCache = std::static_pointer_cast<hkaiNavMeshClearanceCache>(_obj);
    }
    return r;
}

std::shared_ptr<HkObject> Deser_hkaiNavMeshClearanceCacheSeedingCacheDataSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiNavMeshClearanceCacheSeedingCacheDataSet>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->cacheDatas.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->cacheDatas[_i] = Deser_Inline_hkaiNavMeshClearanceCacheSeedingCacheData(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaiNavMesh(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiNavMesh>();
    const size_t base = item.absoluteDataOffset;

    r->faces = u.ReadPodArray<hkaiNavMeshFace>(base + 24);
    r->edges = u.ReadPodArray<hkaiNavMeshEdge>(base + 40);
    r->vertices = u.ReadPodArray<hkVector4>(base + 56);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 72));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->streamingSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->streamingSets[_i] = Deser_Inline_hkaiAnnotatedStreamingSet(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    r->faceData = u.ReadPodArray<int32_t>(base + 88);
    r->edgeData = u.ReadPodArray<int32_t>(base + 104);
    r->faceDataStriding = u.ReadPodAt<int32_t>(base + 120);
    r->edgeDataStriding = u.ReadPodAt<int32_t>(base + 124);
    r->flags = u.ReadPodAt<uint8_t>(base + 128);
    r->aabb = u.ReadPodAt<hkAabb>(base + 144);
    r->erosionRadius = u.ReadPodAt<float>(base + 176);
    r->userData = u.ReadPodAt<uint64_t>(base + 184);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 192);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->clearanceCacheSeedingDataSet = std::static_pointer_cast<hkaiNavMeshClearanceCacheSeedingCacheDataSet>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaiNavMeshQueryMediator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiNavMeshQueryMediator>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hkaiStaticTreeNavMeshQueryMediator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiStaticTreeNavMeshQueryMediator>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->tree = std::static_pointer_cast<hkcdStaticAabbTree>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 32);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->navMesh = std::static_pointer_cast<hkaiNavMesh>(_obj);
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaiUserEdgeSetupArray(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaiUserEdgeSetupArray>();
    const size_t base = item.absoluteDataOffset;

    r->edgeSetups = u.ReadPodArray<hkaiUserEdgeUtilsUserEdgeSetup>(base + 24);

    return r;
}

void RegisterHkaiDispatch(TagFileUnpacker& u)
{
    u.Register("hkaiStreamingSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiStreamingSet(u_, i_);
    });
    u.Register("hkaiNavMeshClearanceCache", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiNavMeshClearanceCache(u_, i_);
    });
    u.Register("hkaiNavMeshClearanceCacheSeeding::CacheDataSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiNavMeshClearanceCacheSeedingCacheDataSet(u_, i_);
    });
    u.Register("hkaiNavMesh", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiNavMesh(u_, i_);
    });
    u.Register("hkaiNavMeshQueryMediator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiNavMeshQueryMediator(u_, i_);
    });
    u.Register("hkaiStaticTreeNavMeshQueryMediator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiStaticTreeNavMeshQueryMediator(u_, i_);
    });
    u.Register("hkaiUserEdgeSetupArray", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaiUserEdgeSetupArray(u_, i_);
    });
}

}  // namespace Firelink::Havok