// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkCore/Havok/HkcdTypes.h>
#include <FirelinkCore/Havok/Tagfile.h>
#include <cstring>

namespace Firelink::Havok
{

static hkcdStaticTreeAabbTree Deser_Inline_hkcdStaticTreeAabbTree(TagFileUnpacker& u, size_t base)
{
    hkcdStaticTreeAabbTree r{};
    r.nodes = u.ReadPodArray<hkcdCompressedAabbCodecsAabb6BytesCodec>(base + 0);
    r.domain = u.ReadPodAt<hkAabb>(base + 16);
    return r;
}

static hkcdStaticTreeAabb6BytesTree Deser_Inline_hkcdStaticTreeAabb6BytesTree(TagFileUnpacker& u, size_t base)
{
    hkcdStaticTreeAabb6BytesTree r{};
    r.nodes = u.ReadPodArray<hkcdCompressedAabbCodecsAabb6BytesCodec>(base + 0);
    r.domain = u.ReadPodAt<hkAabb>(base + 16);
    return r;
}

std::unique_ptr<HkObject> Deser_hkcdStaticAabbTreeImpl(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_unique<hkcdStaticAabbTreeImpl>();
    const size_t base = item.absoluteDataOffset;

    r->tree = Deser_Inline_hkcdStaticTreeAabb6BytesTree(u, base + 32);

    return r;
}

std::unique_ptr<HkObject> Deser_hkcdStaticAabbTree(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_unique<hkcdStaticAabbTree>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->treePtr.reset(static_cast<hkcdStaticAabbTreeImpl*>(_obj.release()));
    }

    return r;
}

void RegisterHkcdDispatch(TagFileUnpacker& u)
{
    u.Register("hkcdStaticAabbTree::Impl", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::unique_ptr<HkObject>
    {
        return Deser_hkcdStaticAabbTreeImpl(u_, i_);
    });
    u.Register("hkcdStaticAabbTree", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::unique_ptr<HkObject>
    {
        return Deser_hkcdStaticAabbTree(u_, i_);
    });
}

}  // namespace Firelink::Havok