// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/base.h>
#include <cstring>
#include <FirelinkERHavok/Types/core.h>

namespace Firelink::Havok::EldenRing
{

static hkAssetRefPtr Deser_Inline_hkAssetRefPtr(TagFileUnpacker& u, size_t base)
{
    hkAssetRefPtr r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.ptr = std::static_pointer_cast<DefType>(_obj);
    }
    return r;
}

static hkBitFieldStorage Deser_Inline_hkBitFieldStorage(TagFileUnpacker& u, size_t base)
{
    hkBitFieldStorage r{};
    r.words = u.ReadPodArray<uint32_t>(base + 0);
    r.numBits = u.ReadPodAt<int32_t>(base + 16);
    return r;
}

static hkBitFieldBase Deser_Inline_hkBitFieldBase(TagFileUnpacker& u, size_t base)
{
    hkBitFieldBase r{};
    r.storage = Deser_Inline_hkBitFieldStorage(u, base + 0);
    return r;
}

static hkBitField Deser_Inline_hkBitField(TagFileUnpacker& u, size_t base)
{
    hkBitField r{};
    r.storage = Deser_Inline_hkBitFieldStorage(u, base + 0);
    return r;
}

static hkCompressedMassProperties Deser_Inline_hkCompressedMassProperties(TagFileUnpacker& u, size_t base)
{
    hkCompressedMassProperties r{};
    r.centerOfMass = u.ReadPodAt<hkPackedVector3>(base + 0);
    r.inertia = u.ReadPodAt<hkPackedVector3>(base + 8);
    r.majorAxisSpace = u.ReadPodAt<std::array<int16_t, 4>>(base + 16);
    r.mass = u.ReadPodAt<float>(base + 24);
    r.volume = u.ReadPodAt<float>(base + 28);
    return r;
}

static hkDefaultPropertyBag Deser_Inline_hkDefaultPropertyBag(TagFileUnpacker& u, size_t base)
{
    hkDefaultPropertyBag r{};
    r.propertyMap = u.ReadPodAt<hkHashMap>(base + 0);
    return r;
}

std::shared_ptr<HkObject> Deser_hkLocalFrame(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkLocalFrame>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

static hkMeshBoneIndexMapping Deser_Inline_hkMeshBoneIndexMapping(TagFileUnpacker& u, size_t base)
{
    hkMeshBoneIndexMapping r{};
    r.mapping = u.ReadPodArray<int16_t>(base + 0);
    return r;
}

static hkRefCountedPropertiesEntry Deser_Inline_hkRefCountedPropertiesEntry(TagFileUnpacker& u, size_t base)
{
    hkRefCountedPropertiesEntry r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.object = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    r.key = u.ReadPodAt<uint16_t>(base + 8);
    r.flags = u.ReadPodAt<uint16_t>(base + 10);
    return r;
}

std::shared_ptr<HkObject> Deser_hkRefCountedProperties(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkRefCountedProperties>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->entries.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->entries[_i] = Deser_Inline_hkRefCountedPropertiesEntry(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }

    return r;
}

static hkRootLevelContainerNamedVariant Deser_Inline_hkRootLevelContainerNamedVariant(TagFileUnpacker& u, size_t base)
{
    hkRootLevelContainerNamedVariant r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    r.className = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 8));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 16);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.variant = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    return r;
}

static hkRootLevelContainer Deser_Inline_hkRootLevelContainer(TagFileUnpacker& u, size_t base)
{
    hkRootLevelContainer r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 0));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.namedVariants.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.namedVariants[_i] = Deser_Inline_hkRootLevelContainerNamedVariant(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    return r;
}

void RegisterBaseDispatch(TagFileUnpacker& u)
{
    u.Register("hkLocalFrame", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkLocalFrame(u_, i_);
    });
    u.Register("hkRefCountedProperties", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkRefCountedProperties(u_, i_);
    });
}

}  // namespace Firelink::Havok::EldenRing