// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/core.h>
#include <cstring>

namespace Firelink::Havok::EldenRing
{

static hkReflectQualifiedType Deser_Inline_hkReflectQualifiedType(TagFileUnpacker& u, size_t base)
{
    hkReflectQualifiedType r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.type = std::static_pointer_cast<void>(_obj);
    }
    return r;
}

static hkPropertyDesc Deser_Inline_hkPropertyDesc(TagFileUnpacker& u, size_t base)
{
    hkPropertyDesc r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.type = std::static_pointer_cast<void>(_obj);
    }
    r.name = u.ReadPodAt<std::string>(base + 8);
    r.flags = u.ReadPodAt<uint32_t>(base + 16);
    return r;
}

static hkPtrAndInt Deser_Inline_hkPtrAndInt(TagFileUnpacker& u, size_t base)
{
    hkPtrAndInt r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.ptrAndInt = std::static_pointer_cast<hkPropertyDesc>(_obj);
    }
    return r;
}

static hkReflectAny Deser_Inline_hkReflectAny(TagFileUnpacker& u, size_t base)
{
    hkReflectAny r{};
    r.type = Deser_Inline_hkReflectQualifiedType(u, base + 0);
    r.status = u.ReadPodAt<uint8_t>(base + 8);
    r.buf = u.ReadPodAt<std::array<uint32_t, 4>>(base + 16);
    return r;
}

static hkPropertyId Deser_Inline_hkPropertyId(TagFileUnpacker& u, size_t base)
{
    hkPropertyId r{};
    return r;
}

static hkTuple Deser_Inline_hkTuple(TagFileUnpacker& u, size_t base)
{
    hkTuple r{};
    r._0 = Deser_Inline_hkPropertyId(u, base + 0);
    r._1 = Deser_Inline_hkReflectAny(u, base + 16);
    return r;
}

static hkHashMapDetailIndex Deser_Inline_hkHashMapDetailIndex(TagFileUnpacker& u, size_t base)
{
    hkHashMapDetailIndex r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.entries = std::static_pointer_cast<void>(_obj);
    }
    r.hashMod = u.ReadPodAt<int32_t>(base + 8);
    return r;
}

static hkHashMapDetailMapTuple Deser_Inline_hkHashMapDetailMapTuple(TagFileUnpacker& u, size_t base)
{
    hkHashMapDetailMapTuple r{};
    r._0 = Deser_Inline_hkPropertyId(u, base + 0);
    r._1 = Deser_Inline_hkReflectAny(u, base + 16);
    return r;
}

static hkHashBase Deser_Inline_hkHashBase(TagFileUnpacker& u, size_t base)
{
    hkHashBase r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 0));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.items.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.items[_i] = Deser_Inline_hkHashMapDetailMapTuple(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 48);
        }
    }
    return r;
}

static hkHashMap Deser_Inline_hkHashMap(TagFileUnpacker& u, size_t base)
{
    hkHashMap r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 0));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.items.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.items[_i] = Deser_Inline_hkHashMapDetailMapTuple(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 48);
        }
    }
    return r;
}

static hkDefaultPropertyBag Deser_Inline_hkDefaultPropertyBag(TagFileUnpacker& u, size_t base)
{
    hkDefaultPropertyBag r{};
    r.propertyMap = Deser_Inline_hkHashMap(u, base + 0);
    return r;
}

static hkPropertyBag Deser_Inline_hkPropertyBag(TagFileUnpacker& u, size_t base)
{
    hkPropertyBag r{};
    return r;
}

static hkReferencedObject Deser_Inline_hkReferencedObject(TagFileUnpacker& u, size_t base)
{
    hkReferencedObject r{};
    r.propertyBag = Deser_Inline_hkPropertyBag(u, base + 8);
    return r;
}

void RegisterCoreDispatch(TagFileUnpacker& u)
{
}

}  // namespace Firelink::Havok::EldenRing