// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/custom.h>
#include <cstring>
#include <FirelinkERHavok/Types/core.h FirelinkERHavok/Types/base.h FirelinkERHavok/Types/hkb.h>

namespace Firelink::Havok::EldenRing
{

static CustomLookAtTwistModifier Deser_Inline_CustomLookAtTwistModifier(TagFileUnpacker& u, size_t base)
{
    CustomLookAtTwistModifier r{};
    r.ModifierID = u.ReadPodAt<int32_t>(base + 104);
    r.rotationAxisType = u.ReadPodAt<int8_t>(base + 108);
    r.SensingDummyPoly = u.ReadPodAt<int32_t>(base + 112);
    r.twistParam = u.ReadPodArray<CustomLookAtTwistModifierTwistParam>(base + 120);
    r.UpLimitAngle = u.ReadPodAt<float>(base + 136);
    r.DownLimitAngle = u.ReadPodAt<float>(base + 140);
    r.RightLimitAngle = u.ReadPodAt<float>(base + 144);
    r.LeftLimitAngle = u.ReadPodAt<float>(base + 148);
    r.UpMinimumAngle = u.ReadPodAt<float>(base + 152);
    r.DownMinimumAngle = u.ReadPodAt<float>(base + 156);
    r.RightMinimumAngle = u.ReadPodAt<float>(base + 160);
    r.LeftMinimumAngle = u.ReadPodAt<float>(base + 164);
    r.SensingAngle = u.ReadPodAt<int16_t>(base + 168);
    r.setAngleMethod = u.ReadPodAt<int8_t>(base + 170);
    r.isAdditive = u.ReadPodAt<bool>(base + 171);
    return r;
}

static CustomManualSelectorGenerator Deser_Inline_CustomManualSelectorGenerator(TagFileUnpacker& u, size_t base)
{
    CustomManualSelectorGenerator r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 152));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r.generators.emplace_back(std::static_pointer_cast<hkbGenerator>(_el));
            }
        }
    }
    r.offsetType = u.ReadPodAt<int32_t>(base + 168);
    r.animId = u.ReadPodAt<int32_t>(base + 172);
    r.animeEndEventType = u.ReadPodAt<int32_t>(base + 176);
    r.enableScript = u.ReadPodAt<bool>(base + 180);
    r.enableTae = u.ReadPodAt<bool>(base + 181);
    r.changeTypeOfSelectedIndexAfterActivate = u.ReadPodAt<uint8_t>(base + 182);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 184);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.generatorChangedTransitionEffect = std::static_pointer_cast<hkbTransitionEffect>(_obj);
    }
    r.checkAnimEndSlotNo = u.ReadPodAt<int32_t>(base + 192);
    r.replanningAI = u.ReadPodAt<uint8_t>(base + 196);
    r.rideSync = u.ReadPodAt<uint8_t>(base + 197);
    return r;
}

void RegisterCustomDispatch(TagFileUnpacker& u)
{
}

}  // namespace Firelink::Havok::EldenRing