// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/hcl.h>
#include <cstring>
#include <FirelinkERHavok/Types/core.h FirelinkERHavok/Types/base.h>

namespace Firelink::Havok::EldenRing
{

std::shared_ptr<HkObject> Deser_hclAction(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclAction>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hclConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hclBendStiffnessConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclBendStiffnessConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);
    r->links = u.ReadPodArray<hclBendStiffnessConstraintSetLink>(base + 40);
    r->maxRestPoseHeightSq = u.ReadPodAt<float>(base + 56);
    r->clampBendStiffness = u.ReadPodAt<bool>(base + 60);
    r->useRestPoseConfig = u.ReadPodAt<bool>(base + 61);

    return r;
}

static hclBoneSpaceDeformer Deser_Inline_hclBoneSpaceDeformer(TagFileUnpacker& u, size_t base)
{
    hclBoneSpaceDeformer r{};
    r.fourBlendEntries = u.ReadPodArray<hclBoneSpaceDeformerFourBlendEntryBlock>(base + 0);
    r.threeBlendEntries = u.ReadPodArray<hclBoneSpaceDeformerThreeBlendEntryBlock>(base + 16);
    r.twoBlendEntries = u.ReadPodArray<hclBoneSpaceDeformerTwoBlendEntryBlock>(base + 32);
    r.oneBlendEntries = u.ReadPodArray<hclBoneSpaceDeformerOneBlendEntryBlock>(base + 48);
    r.controlBytes = u.ReadPodArray<uint8_t>(base + 64);
    r.startVertexIndex = u.ReadPodAt<uint16_t>(base + 80);
    r.endVertexIndex = u.ReadPodAt<uint16_t>(base + 82);
    r.partialWrite = u.ReadPodAt<bool>(base + 84);
    return r;
}

static hclTransformSetUsageTransformTracker Deser_Inline_hclTransformSetUsageTransformTracker(TagFileUnpacker& u, size_t base)
{
    hclTransformSetUsageTransformTracker r{};
    r.read = u.ReadPodAt<hkBitField>(base + 0);
    r.readBeforeWrite = u.ReadPodAt<hkBitField>(base + 24);
    r.written = u.ReadPodAt<hkBitField>(base + 48);
    return r;
}

static hclTransformSetUsage Deser_Inline_hclTransformSetUsage(TagFileUnpacker& u, size_t base)
{
    hclTransformSetUsage r{};
    r.perComponentFlags = u.ReadPodAt<std::array<uint8_t, 2>>(base + 0);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 8));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.perComponentTransformTrackers.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.perComponentTransformTrackers[_i] = Deser_Inline_hclTransformSetUsageTransformTracker(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 72);
        }
    }
    return r;
}

static hclClothStateTransformSetAccess Deser_Inline_hclClothStateTransformSetAccess(TagFileUnpacker& u, size_t base)
{
    hclClothStateTransformSetAccess r{};
    r.transformSetIndex = u.ReadPodAt<uint32_t>(base + 0);
    r.transformSetUsage = Deser_Inline_hclTransformSetUsage(u, base + 8);
    return r;
}

std::shared_ptr<HkObject> Deser_hclOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hclBoneSpaceMeshMeshDeformOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclBoneSpaceMeshMeshDeformOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->scaleNormalBehaviour = u.ReadPodAt<uint32_t>(base + 80);
    r->inputTrianglesSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->boneSpaceDeformer = Deser_Inline_hclBoneSpaceDeformer(u, base + 104);

    return r;
}

std::shared_ptr<HkObject> Deser_hclBoneSpaceMeshMeshDeformPOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclBoneSpaceMeshMeshDeformPOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->scaleNormalBehaviour = u.ReadPodAt<uint32_t>(base + 80);
    r->inputTrianglesSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->boneSpaceDeformer = Deser_Inline_hclBoneSpaceDeformer(u, base + 104);
    r->localPs = u.ReadPodArray<hclBoneSpaceDeformerLocalBlockP>(base + 192);
    r->localUnpackedPs = u.ReadPodArray<hclBoneSpaceDeformerLocalBlockUnpackedP>(base + 208);

    return r;
}

std::shared_ptr<HkObject> Deser_hclBufferDefinition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclBufferDefinition>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->type = u.ReadPodAt<int32_t>(base + 32);
    r->subType = u.ReadPodAt<int32_t>(base + 36);
    r->numVertices = u.ReadPodAt<uint32_t>(base + 40);
    r->numTriangles = u.ReadPodAt<uint32_t>(base + 44);
    r->bufferLayout = u.ReadPodAt<hclBufferLayout>(base + 48);

    return r;
}

std::shared_ptr<HkObject> Deser_hclShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclShape>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

std::shared_ptr<HkObject> Deser_hclCapsuleShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclCapsuleShape>();
    const size_t base = item.absoluteDataOffset;

    r->start = u.ReadPodAt<hkVector4>(base + 32);
    r->end = u.ReadPodAt<hkVector4>(base + 48);
    r->dir = u.ReadPodAt<hkVector4>(base + 64);
    r->radius = u.ReadPodAt<float>(base + 80);
    r->capLenSqrdInv = u.ReadPodAt<float>(base + 84);

    return r;
}

std::shared_ptr<HkObject> Deser_hclCollidable(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclCollidable>();
    const size_t base = item.absoluteDataOffset;

    r->transform = u.ReadPodAt<hkTransform>(base + 32);
    r->linearVelocity = u.ReadPodAt<hkVector4>(base + 96);
    r->angularVelocity = u.ReadPodAt<hkVector4>(base + 112);
    r->userData = u.ReadPodAt<uint64_t>(base + 128);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 136);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->shape = std::static_pointer_cast<hclShape>(_obj);
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 144));
    r->pinchDetectionRadius = u.ReadPodAt<float>(base + 152);
    r->pinchDetectionPriority = u.ReadPodAt<int8_t>(base + 156);
    r->pinchDetectionEnabled = u.ReadPodAt<bool>(base + 157);
    r->virtualCollisionPointCollisionEnabled = u.ReadPodAt<bool>(base + 158);
    r->enabled = u.ReadPodAt<bool>(base + 159);

    return r;
}

std::shared_ptr<HkObject> Deser_hclSimClothPose(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclSimClothPose>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->positions = u.ReadPodArray<hkVector4>(base + 32);

    return r;
}

static hclSimClothDataCollidableTransformMap Deser_Inline_hclSimClothDataCollidableTransformMap(TagFileUnpacker& u, size_t base)
{
    hclSimClothDataCollidableTransformMap r{};
    r.transformSetIndex = u.ReadPodAt<int32_t>(base + 0);
    r.transformIndices = u.ReadPodArray<uint32_t>(base + 8);
    r.offsets = u.ReadPodArray<hkMatrix4>(base + 24);
    return r;
}

static hclVirtualCollisionPointsData Deser_Inline_hclVirtualCollisionPointsData(TagFileUnpacker& u, size_t base)
{
    hclVirtualCollisionPointsData r{};
    r.blocks = u.ReadPodArray<hclVirtualCollisionPointsDataBlock>(base + 0);
    r.numVCPoints = u.ReadPodAt<uint16_t>(base + 16);
    r.landscapeParticlesBlockIndex = u.ReadPodArray<uint16_t>(base + 24);
    r.numLandscapeVCPoints = u.ReadPodAt<uint16_t>(base + 40);
    r.edgeBarycentricsDictionary = u.ReadPodArray<float>(base + 48);
    r.edgeDictionaryEntries = u.ReadPodArray<hclVirtualCollisionPointsDataBarycentricDictionaryEntry>(base + 64);
    r.triangleBarycentricsDictionary = u.ReadPodArray<hclVirtualCollisionPointsDataBarycentricPair>(base + 80);
    r.triangleDictionaryEntries = u.ReadPodArray<hclVirtualCollisionPointsDataBarycentricDictionaryEntry>(base + 96);
    r.edges = u.ReadPodArray<hclVirtualCollisionPointsDataEdgeFanSection>(base + 112);
    r.edgeFans = u.ReadPodArray<hclVirtualCollisionPointsDataEdgeFan>(base + 128);
    r.triangles = u.ReadPodArray<hclVirtualCollisionPointsDataTriangleFanSection>(base + 144);
    r.triangleFans = u.ReadPodArray<hclVirtualCollisionPointsDataTriangleFan>(base + 160);
    r.edgesLandscape = u.ReadPodArray<hclVirtualCollisionPointsDataEdgeFanSection>(base + 176);
    r.edgeFansLandscape = u.ReadPodArray<hclVirtualCollisionPointsDataEdgeFanLandscape>(base + 192);
    r.trianglesLandscape = u.ReadPodArray<hclVirtualCollisionPointsDataTriangleFanSection>(base + 208);
    r.triangleFansLandscape = u.ReadPodArray<hclVirtualCollisionPointsDataTriangleFanLandscape>(base + 224);
    r.edgeFanIndices = u.ReadPodArray<uint16_t>(base + 240);
    r.triangleFanIndices = u.ReadPodArray<uint16_t>(base + 256);
    r.edgeFanIndicesLandscape = u.ReadPodArray<uint16_t>(base + 272);
    r.triangleFanIndicesLandscape = u.ReadPodArray<uint16_t>(base + 288);
    return r;
}

std::shared_ptr<HkObject> Deser_hclSimClothData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclSimClothData>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->simulationInfo = u.ReadPodAt<hclSimClothDataOverridableSimulationInfo>(base + 32);
    r->particleDatas = u.ReadPodArray<hclSimClothDataParticleData>(base + 64);
    r->fixedParticles = u.ReadPodArray<uint16_t>(base + 80);
    r->doNormals = u.ReadPodAt<bool>(base + 96);
    r->simOpIds = u.ReadPodArray<uint32_t>(base + 104);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 120));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->simClothPoses.emplace_back(std::static_pointer_cast<hclSimClothPose>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 136));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->staticConstraintSets.emplace_back(std::static_pointer_cast<hclConstraintSet>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 152));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->antiPinchConstraintSets.emplace_back(std::static_pointer_cast<hclConstraintSet>(_el));
            }
        }
    }
    r->collidableTransformMap = Deser_Inline_hclSimClothDataCollidableTransformMap(u, base + 168);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 208));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->perInstanceCollidables.emplace_back(std::static_pointer_cast<hclCollidable>(_el));
            }
        }
    }
    r->maxParticleRadius = u.ReadPodAt<float>(base + 224);
    r->staticCollisionMasks = u.ReadPodArray<uint32_t>(base + 232);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 248));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->actions.emplace_back(std::static_pointer_cast<hclAction>(_el));
            }
        }
    }
    r->totalMass = u.ReadPodAt<float>(base + 264);
    r->transferMotionData = u.ReadPodAt<hclSimClothDataTransferMotionData>(base + 268);
    r->transferMotionEnabled = u.ReadPodAt<bool>(base + 316);
    r->landscapeCollisionEnabled = u.ReadPodAt<bool>(base + 317);
    r->landscapeCollisionData = u.ReadPodAt<hclSimClothDataLandscapeCollisionData>(base + 320);
    r->numLandscapeCollidableParticles = u.ReadPodAt<uint32_t>(base + 344);
    r->triangleIndices = u.ReadPodArray<uint16_t>(base + 352);
    r->triangleFlips = u.ReadPodArray<uint8_t>(base + 368);
    r->pinchDetectionEnabled = u.ReadPodAt<bool>(base + 384);
    r->perParticlePinchDetectionEnabledFlags = u.ReadPodArray<bool>(base + 392);
    r->collidablePinchingDatas = u.ReadPodArray<hclSimClothDataCollidablePinchingData>(base + 408);
    r->minPinchedParticleIndex = u.ReadPodAt<uint16_t>(base + 424);
    r->maxPinchedParticleIndex = u.ReadPodAt<uint16_t>(base + 426);
    r->maxCollisionPairs = u.ReadPodAt<uint32_t>(base + 428);
    r->virtualCollisionPointsData = Deser_Inline_hclVirtualCollisionPointsData(u, base + 432);

    return r;
}

std::shared_ptr<HkObject> Deser_hclTransformSetDefinition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclTransformSetDefinition>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->type = u.ReadPodAt<int32_t>(base + 32);
    r->numTransforms = u.ReadPodAt<uint32_t>(base + 36);

    return r;
}

static hclStateDependencyGraphBranch Deser_Inline_hclStateDependencyGraphBranch(TagFileUnpacker& u, size_t base)
{
    hclStateDependencyGraphBranch r{};
    r.branchId = u.ReadPodAt<int32_t>(base + 0);
    r.stateOperatorIndices = u.ReadPodArray<int32_t>(base + 8);
    r.parentBranches = u.ReadPodArray<int32_t>(base + 24);
    r.childBranches = u.ReadPodArray<int32_t>(base + 40);
    return r;
}

std::shared_ptr<HkObject> Deser_hclStateDependencyGraph(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclStateDependencyGraph>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->branches.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->branches[_i] = Deser_Inline_hclStateDependencyGraphBranch(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 56);
        }
    }
    r->rootBranchIds = u.ReadPodArray<int32_t>(base + 40);
    r->children = u.ReadPodArray<std::vector<int32_t>>(base + 56);
    r->parents = u.ReadPodArray<std::vector<int32_t>>(base + 72);
    r->multiThreadable = u.ReadPodAt<bool>(base + 88);

    return r;
}

std::shared_ptr<HkObject> Deser_hclClothState(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclClothState>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operators = u.ReadPodArray<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 48);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 64));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->usedSimCloths = u.ReadPodArray<uint32_t>(base + 80);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 96);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->dependencyGraph = std::static_pointer_cast<hclStateDependencyGraph>(_obj);
    }

    return r;
}

static hclStateTransitionSimClothTransitionData Deser_Inline_hclStateTransitionSimClothTransitionData(TagFileUnpacker& u, size_t base)
{
    hclStateTransitionSimClothTransitionData r{};
    r.isSimulated = u.ReadPodAt<bool>(base + 0);
    r.transitionConstraints = u.ReadPodArray<hkHandle>(base + 8);
    r.transitionType = u.ReadPodAt<uint32_t>(base + 24);
    return r;
}

static hclStateTransitionBlendOpTransitionData Deser_Inline_hclStateTransitionBlendOpTransitionData(TagFileUnpacker& u, size_t base)
{
    hclStateTransitionBlendOpTransitionData r{};
    r.bufferASimCloths = u.ReadPodArray<int32_t>(base + 0);
    r.bufferBSimCloths = u.ReadPodArray<int32_t>(base + 16);
    r.transitionType = u.ReadPodAt<uint32_t>(base + 32);
    r.blendWeightType = u.ReadPodAt<hk>(base + 36);
    r.blendOperatorId = u.ReadPodAt<uint32_t>(base + 40);
    return r;
}

static hclStateTransitionStateTransitionData Deser_Inline_hclStateTransitionStateTransitionData(TagFileUnpacker& u, size_t base)
{
    hclStateTransitionStateTransitionData r{};
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 0));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.simClothTransitionData.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.simClothTransitionData[_i] = Deser_Inline_hclStateTransitionSimClothTransitionData(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 16));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.blendOpTransitionData.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.blendOpTransitionData[_i] = Deser_Inline_hclStateTransitionBlendOpTransitionData(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 48);
        }
    }
    r.simulatedState = u.ReadPodAt<bool>(base + 32);
    r.emptyState = u.ReadPodAt<bool>(base + 33);
    return r;
}

std::shared_ptr<HkObject> Deser_hclStateTransition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclStateTransition>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->stateIds = u.ReadPodArray<uint32_t>(base + 32);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->stateTransitionData.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->stateTransitionData[_i] = Deser_Inline_hclStateTransitionStateTransitionData(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 40);
        }
    }
    r->simClothTransitionConstraints = u.ReadPodArray<std::vector<hkHandle>>(base + 64);

    return r;
}

std::shared_ptr<HkObject> Deser_hclClothData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclClothData>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 32));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->simClothDatas.emplace_back(std::static_pointer_cast<hclSimClothData>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->bufferDefinitions.emplace_back(std::static_pointer_cast<hclBufferDefinition>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 64));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->transformSetDefinitions.emplace_back(std::static_pointer_cast<hclTransformSetDefinition>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 80));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->operators.emplace_back(std::static_pointer_cast<hclOperator>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 96));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->clothStateDatas.emplace_back(std::static_pointer_cast<hclClothState>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 112));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->stateTransitions.emplace_back(std::static_pointer_cast<hclStateTransition>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 128));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->actions.emplace_back(std::static_pointer_cast<hclAction>(_el));
            }
        }
    }
    r->targetPlatform = u.ReadPodAt<uint32_t>(base + 144);

    return r;
}

std::shared_ptr<HkObject> Deser_hclClothContainer(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclClothContainer>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->collidables.emplace_back(std::static_pointer_cast<hclCollidable>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 40));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->clothDatas.emplace_back(std::static_pointer_cast<hclClothData>(_el));
            }
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hclCopyVerticesOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclCopyVerticesOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->numberOfVertices = u.ReadPodAt<uint32_t>(base + 80);
    r->startVertexIn = u.ReadPodAt<uint32_t>(base + 84);
    r->startVertexOut = u.ReadPodAt<uint32_t>(base + 88);
    r->copyNormals = u.ReadPodAt<bool>(base + 92);

    return r;
}

std::shared_ptr<HkObject> Deser_hclGatherAllVerticesOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclGatherAllVerticesOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->vertexInputFromVertexOutput = u.ReadPodArray<int16_t>(base + 72);
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 88);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 92);
    r->gatherNormals = u.ReadPodAt<bool>(base + 96);
    r->partialGather = u.ReadPodAt<bool>(base + 97);

    return r;
}

std::shared_ptr<HkObject> Deser_hclInputConvertOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclInputConvertOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->userBufferIndex = u.ReadPodAt<uint32_t>(base + 72);
    r->shadowBufferIndex = u.ReadPodAt<uint32_t>(base + 76);
    r->conversionInfo = u.ReadPodAt<hclRuntimeConversionInfo>(base + 80);

    return r;
}

std::shared_ptr<HkObject> Deser_hclLocalRangeConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclLocalRangeConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);
    r->localConstraints = u.ReadPodArray<hclLocalRangeConstraintSetLocalConstraint>(base + 40);
    r->referenceMeshBufferIdx = u.ReadPodAt<uint32_t>(base + 56);
    r->stiffness = u.ReadPodAt<float>(base + 60);
    r->shapeType = u.ReadPodAt<uint32_t>(base + 64);
    r->applyNormalComponent = u.ReadPodAt<bool>(base + 68);

    return r;
}

std::shared_ptr<HkObject> Deser_hclMoveParticlesOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclMoveParticlesOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->vertexParticlePairs = u.ReadPodArray<hclMoveParticlesOperatorVertexParticlePair>(base + 72);
    r->simClothIndex = u.ReadPodAt<uint32_t>(base + 88);
    r->refBufferIdx = u.ReadPodAt<uint32_t>(base + 92);

    return r;
}

static hclObjectSpaceDeformer Deser_Inline_hclObjectSpaceDeformer(TagFileUnpacker& u, size_t base)
{
    hclObjectSpaceDeformer r{};
    r.eightBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerEightBlendEntryBlock>(base + 0);
    r.sevenBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerSevenBlendEntryBlock>(base + 16);
    r.sixBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerSixBlendEntryBlock>(base + 32);
    r.fiveBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerFiveBlendEntryBlock>(base + 48);
    r.fourBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerFourBlendEntryBlock>(base + 64);
    r.threeBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerThreeBlendEntryBlock>(base + 80);
    r.twoBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerTwoBlendEntryBlock>(base + 96);
    r.oneBlendEntries = u.ReadPodArray<hclObjectSpaceDeformerOneBlendEntryBlock>(base + 112);
    r.controlBytes = u.ReadPodArray<uint8_t>(base + 128);
    r.startVertexIndex = u.ReadPodAt<uint16_t>(base + 144);
    r.endVertexIndex = u.ReadPodAt<uint16_t>(base + 146);
    r.partialWrite = u.ReadPodAt<bool>(base + 148);
    return r;
}

std::shared_ptr<HkObject> Deser_hclObjectSpaceMeshMeshDeformOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclObjectSpaceMeshMeshDeformOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->scaleNormalBehaviour = u.ReadPodAt<uint32_t>(base + 80);
    r->inputTrianglesSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->triangleFromMeshTransforms = u.ReadPodArray<hkMatrix4>(base + 104);
    r->objectSpaceDeformer = Deser_Inline_hclObjectSpaceDeformer(u, base + 120);
    r->customSkinDeform = u.ReadPodAt<bool>(base + 272);

    return r;
}

std::shared_ptr<HkObject> Deser_hclObjectSpaceMeshMeshDeformPOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclObjectSpaceMeshMeshDeformPOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputBufferIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->scaleNormalBehaviour = u.ReadPodAt<uint32_t>(base + 80);
    r->inputTrianglesSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->triangleFromMeshTransforms = u.ReadPodArray<hkMatrix4>(base + 104);
    r->objectSpaceDeformer = Deser_Inline_hclObjectSpaceDeformer(u, base + 120);
    r->customSkinDeform = u.ReadPodAt<bool>(base + 272);
    r->localPs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockP>(base + 280);
    r->localUnpackedPs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockUnpackedP>(base + 296);

    return r;
}

std::shared_ptr<HkObject> Deser_hclObjectSpaceSkinOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclObjectSpaceSkinOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->boneFromSkinMeshTransforms = u.ReadPodArray<hkMatrix4>(base + 72);
    r->transformSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->outputBufferIndex = u.ReadPodAt<uint32_t>(base + 104);
    r->transformSetIndex = u.ReadPodAt<uint32_t>(base + 108);
    r->objectSpaceDeformer = Deser_Inline_hclObjectSpaceDeformer(u, base + 112);

    return r;
}

std::shared_ptr<HkObject> Deser_hclObjectSpaceSkinPNOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclObjectSpaceSkinPNOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->boneFromSkinMeshTransforms = u.ReadPodArray<hkMatrix4>(base + 72);
    r->transformSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->outputBufferIndex = u.ReadPodAt<uint32_t>(base + 104);
    r->transformSetIndex = u.ReadPodAt<uint32_t>(base + 108);
    r->objectSpaceDeformer = Deser_Inline_hclObjectSpaceDeformer(u, base + 112);
    r->localPNs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockPN>(base + 264);
    r->localUnpackedPNs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockUnpackedPN>(base + 280);

    return r;
}

std::shared_ptr<HkObject> Deser_hclObjectSpaceSkinPNTOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclObjectSpaceSkinPNTOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->boneFromSkinMeshTransforms = u.ReadPodArray<hkMatrix4>(base + 72);
    r->transformSubset = u.ReadPodArray<uint16_t>(base + 88);
    r->outputBufferIndex = u.ReadPodAt<uint32_t>(base + 104);
    r->transformSetIndex = u.ReadPodAt<uint32_t>(base + 108);
    r->objectSpaceDeformer = Deser_Inline_hclObjectSpaceDeformer(u, base + 112);
    r->localPNTs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockPNT>(base + 264);
    r->localUnpackedPNTs = u.ReadPodArray<hclObjectSpaceDeformerLocalBlockUnpackedPNT>(base + 280);

    return r;
}

std::shared_ptr<HkObject> Deser_hclOutputConvertOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclOutputConvertOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->userBufferIndex = u.ReadPodAt<uint32_t>(base + 72);
    r->shadowBufferIndex = u.ReadPodAt<uint32_t>(base + 76);
    r->conversionInfo = u.ReadPodAt<hclRuntimeConversionInfo>(base + 80);

    return r;
}

std::shared_ptr<HkObject> Deser_hclScratchBufferDefinition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclScratchBufferDefinition>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->type = u.ReadPodAt<int32_t>(base + 32);
    r->subType = u.ReadPodAt<int32_t>(base + 36);
    r->numVertices = u.ReadPodAt<uint32_t>(base + 40);
    r->numTriangles = u.ReadPodAt<uint32_t>(base + 44);
    r->bufferLayout = u.ReadPodAt<hclBufferLayout>(base + 48);
    r->triangleIndices = u.ReadPodArray<uint16_t>(base + 80);
    r->storeNormals = u.ReadPodAt<bool>(base + 96);
    r->storeTangentsAndBiTangents = u.ReadPodAt<bool>(base + 97);

    return r;
}

std::shared_ptr<HkObject> Deser_hclShadowBufferDefinition(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclShadowBufferDefinition>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->type = u.ReadPodAt<int32_t>(base + 32);
    r->subType = u.ReadPodAt<int32_t>(base + 36);
    r->numVertices = u.ReadPodAt<uint32_t>(base + 40);
    r->numTriangles = u.ReadPodAt<uint32_t>(base + 44);
    r->bufferLayout = u.ReadPodAt<hclBufferLayout>(base + 48);
    r->triangleIndices = u.ReadPodArray<uint16_t>(base + 80);
    r->shadowPositions = u.ReadPodAt<bool>(base + 96);
    r->shadowNormals = u.ReadPodAt<bool>(base + 97);
    r->shadowTangents = u.ReadPodAt<bool>(base + 98);
    r->shadowBiTangents = u.ReadPodAt<bool>(base + 99);

    return r;
}

std::shared_ptr<HkObject> Deser_hclSimpleMeshBoneDeformOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclSimpleMeshBoneDeformOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->inputBufferIdx = u.ReadPodAt<uint32_t>(base + 72);
    r->outputTransformSetIdx = u.ReadPodAt<uint32_t>(base + 76);
    r->triangleBonePairs = u.ReadPodArray<hclSimpleMeshBoneDeformOperatorTriangleBonePair>(base + 80);
    r->localBoneTransforms = u.ReadPodArray<hkMatrix4>(base + 96);

    return r;
}

static hclSimulateOperatorConfig Deser_Inline_hclSimulateOperatorConfig(TagFileUnpacker& u, size_t base)
{
    hclSimulateOperatorConfig r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    r.constraintExecution = u.ReadPodArray<int32_t>(base + 8);
    r.instanceCollidablesUsed = u.ReadPodArray<bool>(base + 24);
    r.subSteps = u.ReadPodAt<uint8_t>(base + 40);
    r.numberOfSolveIterations = u.ReadPodAt<uint8_t>(base + 41);
    r.useAllInstanceCollidables = u.ReadPodAt<bool>(base + 42);
    r.adaptConstraintStiffness = u.ReadPodAt<bool>(base + 43);
    return r;
}

std::shared_ptr<HkObject> Deser_hclSimulateOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclSimulateOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->simClothIndex = u.ReadPodAt<uint32_t>(base + 72);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 80));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->simulateOpConfigs.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->simulateOpConfigs[_i] = Deser_Inline_hclSimulateOperatorConfig(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 48);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hclStandardLinkConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclStandardLinkConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);
    r->links = u.ReadPodArray<hclStandardLinkConstraintSetLink>(base + 40);

    return r;
}

std::shared_ptr<HkObject> Deser_hclStretchLinkConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclStretchLinkConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);
    r->links = u.ReadPodArray<hclStretchLinkConstraintSetLink>(base + 40);

    return r;
}

std::shared_ptr<HkObject> Deser_hclTaperedCapsuleShape(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclTaperedCapsuleShape>();
    const size_t base = item.absoluteDataOffset;

    r->small = u.ReadPodAt<hkVector4>(base + 32);
    r->big = u.ReadPodAt<hkVector4>(base + 48);
    r->coneApex = u.ReadPodAt<hkVector4>(base + 64);
    r->coneAxis = u.ReadPodAt<hkVector4>(base + 80);
    r->lVec = u.ReadPodAt<hkVector4>(base + 96);
    r->dVec = u.ReadPodAt<hkVector4>(base + 112);
    r->tanThetaVecNeg = u.ReadPodAt<hkVector4>(base + 128);
    r->smallRadius = u.ReadPodAt<float>(base + 144);
    r->bigRadius = u.ReadPodAt<float>(base + 148);
    r->l = u.ReadPodAt<float>(base + 152);
    r->d = u.ReadPodAt<float>(base + 156);
    r->cosTheta = u.ReadPodAt<float>(base + 160);
    r->sinTheta = u.ReadPodAt<float>(base + 164);
    r->tanTheta = u.ReadPodAt<float>(base + 168);
    r->tanThetaSqr = u.ReadPodAt<float>(base + 172);

    return r;
}

std::shared_ptr<HkObject> Deser_hclTransitionConstraintSet(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclTransitionConstraintSet>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->constraintId = u.ReadPodAt<hkHandle>(base + 32);
    r->perParticleData = u.ReadPodArray<hclTransitionConstraintSetPerParticle>(base + 40);
    r->toAnimPeriod = u.ReadPodAt<float>(base + 56);
    r->toAnimPlusDelayPeriod = u.ReadPodAt<float>(base + 60);
    r->toSimPeriod = u.ReadPodAt<float>(base + 64);
    r->toSimPlusDelayPeriod = u.ReadPodAt<float>(base + 68);
    r->referenceMeshBufferIdx = u.ReadPodAt<uint32_t>(base + 72);

    return r;
}

std::shared_ptr<HkObject> Deser_hclUpdateAllVertexFramesOperator(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hclUpdateAllVertexFramesOperator>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->operatorID = u.ReadPodAt<uint32_t>(base + 32);
    r->usedBuffers = u.ReadPodArray<hclClothStateBufferAccess>(base + 40);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->usedTransformSets.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->usedTransformSets[_i] = Deser_Inline_hclClothStateTransformSetAccess(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 32);
        }
    }
    r->vertToNormalID = u.ReadPodArray<uint16_t>(base + 72);
    r->triangleFlips = u.ReadPodArray<uint8_t>(base + 88);
    r->referenceVertices = u.ReadPodArray<uint16_t>(base + 104);
    r->tangentEdgeCosAngle = u.ReadPodArray<float>(base + 120);
    r->tangentEdgeSinAngle = u.ReadPodArray<float>(base + 136);
    r->biTangentFlip = u.ReadPodArray<float>(base + 152);
    r->bufferIdx = u.ReadPodAt<uint32_t>(base + 168);
    r->numUniqueNormalIDs = u.ReadPodAt<uint32_t>(base + 172);
    r->updateNormals = u.ReadPodAt<bool>(base + 176);
    r->updateTangents = u.ReadPodAt<bool>(base + 177);
    r->updateBiTangents = u.ReadPodAt<bool>(base + 178);

    return r;
}

void RegisterHclDispatch(TagFileUnpacker& u)
{
    u.Register("hclAction", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclAction(u_, i_);
    });
    u.Register("hclConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclConstraintSet(u_, i_);
    });
    u.Register("hclBendStiffnessConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclBendStiffnessConstraintSet(u_, i_);
    });
    u.Register("hclOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclOperator(u_, i_);
    });
    u.Register("hclBoneSpaceMeshMeshDeformOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclBoneSpaceMeshMeshDeformOperator(u_, i_);
    });
    u.Register("hclBoneSpaceMeshMeshDeformPOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclBoneSpaceMeshMeshDeformPOperator(u_, i_);
    });
    u.Register("hclBufferDefinition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclBufferDefinition(u_, i_);
    });
    u.Register("hclShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclShape(u_, i_);
    });
    u.Register("hclCapsuleShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclCapsuleShape(u_, i_);
    });
    u.Register("hclCollidable", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclCollidable(u_, i_);
    });
    u.Register("hclSimClothPose", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclSimClothPose(u_, i_);
    });
    u.Register("hclSimClothData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclSimClothData(u_, i_);
    });
    u.Register("hclTransformSetDefinition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclTransformSetDefinition(u_, i_);
    });
    u.Register("hclStateDependencyGraph", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclStateDependencyGraph(u_, i_);
    });
    u.Register("hclClothState", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclClothState(u_, i_);
    });
    u.Register("hclStateTransition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclStateTransition(u_, i_);
    });
    u.Register("hclClothData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclClothData(u_, i_);
    });
    u.Register("hclClothContainer", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclClothContainer(u_, i_);
    });
    u.Register("hclCopyVerticesOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclCopyVerticesOperator(u_, i_);
    });
    u.Register("hclGatherAllVerticesOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclGatherAllVerticesOperator(u_, i_);
    });
    u.Register("hclInputConvertOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclInputConvertOperator(u_, i_);
    });
    u.Register("hclLocalRangeConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclLocalRangeConstraintSet(u_, i_);
    });
    u.Register("hclMoveParticlesOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclMoveParticlesOperator(u_, i_);
    });
    u.Register("hclObjectSpaceMeshMeshDeformOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclObjectSpaceMeshMeshDeformOperator(u_, i_);
    });
    u.Register("hclObjectSpaceMeshMeshDeformPOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclObjectSpaceMeshMeshDeformPOperator(u_, i_);
    });
    u.Register("hclObjectSpaceSkinOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclObjectSpaceSkinOperator(u_, i_);
    });
    u.Register("hclObjectSpaceSkinPNOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclObjectSpaceSkinPNOperator(u_, i_);
    });
    u.Register("hclObjectSpaceSkinPNTOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclObjectSpaceSkinPNTOperator(u_, i_);
    });
    u.Register("hclOutputConvertOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclOutputConvertOperator(u_, i_);
    });
    u.Register("hclScratchBufferDefinition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclScratchBufferDefinition(u_, i_);
    });
    u.Register("hclShadowBufferDefinition", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclShadowBufferDefinition(u_, i_);
    });
    u.Register("hclSimpleMeshBoneDeformOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclSimpleMeshBoneDeformOperator(u_, i_);
    });
    u.Register("hclSimulateOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclSimulateOperator(u_, i_);
    });
    u.Register("hclStandardLinkConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclStandardLinkConstraintSet(u_, i_);
    });
    u.Register("hclStretchLinkConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclStretchLinkConstraintSet(u_, i_);
    });
    u.Register("hclTaperedCapsuleShape", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclTaperedCapsuleShape(u_, i_);
    });
    u.Register("hclTransitionConstraintSet", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclTransitionConstraintSet(u_, i_);
    });
    u.Register("hclUpdateAllVertexFramesOperator", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hclUpdateAllVertexFramesOperator(u_, i_);
    });
}

}  // namespace Firelink::Havok::EldenRing