// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/hka.h>
#include <cstring>
#include <FirelinkERHavok/Types/core.h FirelinkERHavok/Types/base.h>

namespace Firelink::Havok::EldenRing
{

std::shared_ptr<HkObject> Deser_hkaAnimatedReferenceFrame(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaAnimatedReferenceFrame>();
    const size_t base = item.absoluteDataOffset;


    return r;
}

static hkaAnnotationTrackAnnotation Deser_Inline_hkaAnnotationTrackAnnotation(TagFileUnpacker& u, size_t base)
{
    hkaAnnotationTrackAnnotation r{};
    r.time = u.ReadPodAt<float>(base + 0);
    r.text = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 8));
    return r;
}

static hkaAnnotationTrack Deser_Inline_hkaAnnotationTrack(TagFileUnpacker& u, size_t base)
{
    hkaAnnotationTrack r{};
    r.trackName = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 8));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r.annotations.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r.annotations[_i] = Deser_Inline_hkaAnnotationTrackAnnotation(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    return r;
}

std::shared_ptr<HkObject> Deser_hkaAnimation(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaAnimation>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int32_t>(base + 24);
    r->duration = u.ReadPodAt<float>(base + 28);
    r->numberOfTransformTracks = u.ReadPodAt<int32_t>(base + 32);
    r->numberOfFloatTracks = u.ReadPodAt<int32_t>(base + 36);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->extractedMotion = std::static_pointer_cast<hkaAnimatedReferenceFrame>(_obj);
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->annotationTracks.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->annotationTracks[_i] = Deser_Inline_hkaAnnotationTrack(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaAnimationBinding(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaAnimationBinding>();
    const size_t base = item.absoluteDataOffset;

    r->originalSkeletonName = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 32);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->animation = std::static_pointer_cast<hkaAnimation>(_obj);
    }
    r->transformTrackToBoneIndices = u.ReadPodArray<int16_t>(base + 40);
    r->floatTrackToFloatSlotIndices = u.ReadPodArray<int16_t>(base + 56);
    r->partitionIndices = u.ReadPodArray<int16_t>(base + 72);
    r->blendHint = u.ReadPodAt<int8_t>(base + 88);

    return r;
}

static hkaBone Deser_Inline_hkaBone(TagFileUnpacker& u, size_t base)
{
    hkaBone r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    r.lockTranslation = u.ReadPodAt<bool>(base + 8);
    return r;
}

static hkaSkeletonLocalFrameOnBone Deser_Inline_hkaSkeletonLocalFrameOnBone(TagFileUnpacker& u, size_t base)
{
    hkaSkeletonLocalFrameOnBone r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.localFrame = std::static_pointer_cast<hkLocalFrame>(_obj);
    }
    r.boneIndex = u.ReadPodAt<int16_t>(base + 8);
    return r;
}

static hkaSkeletonPartition Deser_Inline_hkaSkeletonPartition(TagFileUnpacker& u, size_t base)
{
    hkaSkeletonPartition r{};
    r.name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 0));
    r.startBoneIndex = u.ReadPodAt<int16_t>(base + 8);
    r.numBones = u.ReadPodAt<int16_t>(base + 10);
    return r;
}

std::shared_ptr<HkObject> Deser_hkaSkeleton(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaSkeleton>();
    const size_t base = item.absoluteDataOffset;

    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->parentIndices = u.ReadPodArray<int16_t>(base + 32);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->bones.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->bones[_i] = Deser_Inline_hkaBone(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    r->referencePose = u.ReadPodArray<hkQsTransform>(base + 64);
    r->referenceFloats = u.ReadPodArray<float>(base + 80);
    r->floatSlots = u.ReadPodArray<std::string>(base + 96);
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 112));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->localFrames.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->localFrames[_i] = Deser_Inline_hkaSkeletonLocalFrameOnBone(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 128));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->partitions.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->partitions[_i] = Deser_Inline_hkaSkeletonPartition(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaBoneAttachment(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaBoneAttachment>();
    const size_t base = item.absoluteDataOffset;

    r->originalSkeletonName = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 24));
    r->boneFromAttachment = u.ReadPodAt<hkMatrix4>(base + 32);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 96);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->attachment = std::static_pointer_cast<hkReferencedObject>(_obj);
    }
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 104));
    r->boneIndex = u.ReadPodAt<int16_t>(base + 112);

    return r;
}

static hkaMeshBindingMapping Deser_Inline_hkaMeshBindingMapping(TagFileUnpacker& u, size_t base)
{
    hkaMeshBindingMapping r{};
    r.mapping = u.ReadPodArray<int16_t>(base + 0);
    return r;
}

std::shared_ptr<HkObject> Deser_hkaMeshBinding(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaMeshBinding>();
    const size_t base = item.absoluteDataOffset;

    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 24);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->mesh = std::static_pointer_cast<hkxMesh>(_obj);
    }
    r->originalSkeletonName = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 32));
    r->name = u.FollowStringPtr(u.ReadPodAt<uint64_t>(base + 40));
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 48);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->skeleton = std::static_pointer_cast<hkaSkeleton>(_obj);
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->mappings.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->mappings[_i] = Deser_Inline_hkaMeshBindingMapping(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 16);
        }
    }
    r->boneFromSkinMeshTransforms = u.ReadPodArray<hkTransform>(base + 72);

    return r;
}

std::shared_ptr<HkObject> Deser_hkaAnimationContainer(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaAnimationContainer>();
    const size_t base = item.absoluteDataOffset;

    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 24));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->skeletons.emplace_back(std::static_pointer_cast<hkaSkeleton>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 40));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->animations.emplace_back(std::static_pointer_cast<hkaAnimation>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 56));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->bindings.emplace_back(std::static_pointer_cast<hkaAnimationBinding>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 72));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->attachments.emplace_back(std::static_pointer_cast<hkaBoneAttachment>(_el));
            }
        }
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 88));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            for (int _i = 0; _i < _arrItem.length; ++_i) {
                const uint64_t _pIdx = u.ReadPodAt<uint64_t>(_arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 8);
                auto _el = u.FollowObjectPtr(_pIdx);
                if (_el) r->skins.emplace_back(std::static_pointer_cast<hkaMeshBinding>(_el));
            }
        }
    }

    return r;
}

std::shared_ptr<HkObject> Deser_hkaDefaultAnimatedReferenceFrame(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaDefaultAnimatedReferenceFrame>();
    const size_t base = item.absoluteDataOffset;

    r->up = u.ReadPodAt<hkVector4>(base + 32);
    r->forward = u.ReadPodAt<hkVector4>(base + 48);
    r->duration = u.ReadPodAt<float>(base + 64);
    r->referenceFrameSamples = u.ReadPodArray<hkVector4>(base + 72);

    return r;
}

std::shared_ptr<HkObject> Deser_hkaInterleavedUncompressedAnimation(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaInterleavedUncompressedAnimation>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int32_t>(base + 24);
    r->duration = u.ReadPodAt<float>(base + 28);
    r->numberOfTransformTracks = u.ReadPodAt<int32_t>(base + 32);
    r->numberOfFloatTracks = u.ReadPodAt<int32_t>(base + 36);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->extractedMotion = std::static_pointer_cast<hkaAnimatedReferenceFrame>(_obj);
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->annotationTracks.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->annotationTracks[_i] = Deser_Inline_hkaAnnotationTrack(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    r->transforms = u.ReadPodArray<hkQsTransform>(base + 56);
    r->floats = u.ReadPodArray<float>(base + 72);

    return r;
}

static hkaSkeletonMapperData Deser_Inline_hkaSkeletonMapperData(TagFileUnpacker& u, size_t base)
{
    hkaSkeletonMapperData r{};
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 0);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.skeletonA = std::static_pointer_cast<hkaSkeleton>(_obj);
    }
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 8);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.skeletonB = std::static_pointer_cast<hkaSkeleton>(_obj);
    }
    r.partitionMap = u.ReadPodArray<int16_t>(base + 16);
    r.simpleMappingPartitionRanges = u.ReadPodArray<hkaSkeletonMapperDataPartitionMappingRange>(base + 32);
    r.chainMappingPartitionRanges = u.ReadPodArray<hkaSkeletonMapperDataPartitionMappingRange>(base + 48);
    r.simpleMappings = u.ReadPodArray<hkaSkeletonMapperDataSimpleMapping>(base + 64);
    r.chainMappings = u.ReadPodArray<hkaSkeletonMapperDataChainMapping>(base + 80);
    r.unmappedBones = u.ReadPodArray<int16_t>(base + 96);
    r.extractedMotionMapping = u.ReadPodAt<hkQsTransform>(base + 112);
    r.keepUnmappedLocal = u.ReadPodAt<bool>(base + 160);
    r.mappingType = u.ReadPodAt<int32_t>(base + 164);
    return r;
}

std::shared_ptr<HkObject> Deser_hkaSkeletonMapper(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaSkeletonMapper>();
    const size_t base = item.absoluteDataOffset;

    r->mapping = Deser_Inline_hkaSkeletonMapperData(u, base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hkaSplineCompressedAnimation(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkaSplineCompressedAnimation>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int32_t>(base + 24);
    r->duration = u.ReadPodAt<float>(base + 28);
    r->numberOfTransformTracks = u.ReadPodAt<int32_t>(base + 32);
    r->numberOfFloatTracks = u.ReadPodAt<int32_t>(base + 36);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 40);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r->extractedMotion = std::static_pointer_cast<hkaAnimatedReferenceFrame>(_obj);
    }
    {
        const auto _arrIdx = static_cast<int>(u.ReadPodAt<uint64_t>(base + 48));
        if (_arrIdx > 0 && _arrIdx < static_cast<int>(u.items.size())) {
            const auto& _arrItem = u.items[_arrIdx];
            r->annotationTracks.resize(static_cast<size_t>(_arrItem.length));
            for (int _i = 0; _i < _arrItem.length; ++_i)
                r->annotationTracks[_i] = Deser_Inline_hkaAnnotationTrack(u, _arrItem.absoluteDataOffset + static_cast<size_t>(_i) * 24);
        }
    }
    r->numFrames = u.ReadPodAt<int32_t>(base + 64);
    r->numBlocks = u.ReadPodAt<int32_t>(base + 68);
    r->maxFramesPerBlock = u.ReadPodAt<int32_t>(base + 72);
    r->maskAndQuantizationSize = u.ReadPodAt<int32_t>(base + 76);
    r->blockDuration = u.ReadPodAt<float>(base + 80);
    r->blockInverseDuration = u.ReadPodAt<float>(base + 84);
    r->frameDuration = u.ReadPodAt<float>(base + 88);
    r->blockOffsets = u.ReadPodArray<uint32_t>(base + 96);
    r->floatBlockOffsets = u.ReadPodArray<uint32_t>(base + 112);
    r->transformOffsets = u.ReadPodArray<uint32_t>(base + 128);
    r->floatOffsets = u.ReadPodArray<uint32_t>(base + 144);
    r->data = u.ReadPodArray<uint8_t>(base + 160);
    r->endian = u.ReadPodAt<int32_t>(base + 176);

    return r;
}

void RegisterHkaDispatch(TagFileUnpacker& u)
{
    u.Register("hkaAnimatedReferenceFrame", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaAnimatedReferenceFrame(u_, i_);
    });
    u.Register("hkaAnimation", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaAnimation(u_, i_);
    });
    u.Register("hkaAnimationBinding", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaAnimationBinding(u_, i_);
    });
    u.Register("hkaSkeleton", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaSkeleton(u_, i_);
    });
    u.Register("hkaBoneAttachment", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaBoneAttachment(u_, i_);
    });
    u.Register("hkaMeshBinding", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaMeshBinding(u_, i_);
    });
    u.Register("hkaAnimationContainer", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaAnimationContainer(u_, i_);
    });
    u.Register("hkaDefaultAnimatedReferenceFrame", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaDefaultAnimatedReferenceFrame(u_, i_);
    });
    u.Register("hkaInterleavedUncompressedAnimation", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaInterleavedUncompressedAnimation(u_, i_);
    });
    u.Register("hkaSkeletonMapper", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaSkeletonMapper(u_, i_);
    });
    u.Register("hkaSplineCompressedAnimation", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkaSplineCompressedAnimation(u_, i_);
    });
}

}  // namespace Firelink::Havok::EldenRing