// AUTO-GENERATED by gen_hk_types.py — do not edit manually
#include <FirelinkERHavok/Types/hkp.h>
#include <cstring>
#include <FirelinkERHavok/Types/core.h FirelinkERHavok/Types/base.h>

namespace Firelink::Havok::EldenRing
{

std::shared_ptr<HkObject> Deser_hkpConstraintMotor(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpConstraintMotor>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int8_t>(base + 20);

    return r;
}

static hkpAngMotorConstraintAtom Deser_Inline_hkpAngMotorConstraintAtom(TagFileUnpacker& u, size_t base)
{
    hkpAngMotorConstraintAtom r{};
    r.type = u.ReadPodAt<uint16_t>(base + 0);
    r.isEnabled = u.ReadPodAt<bool>(base + 2);
    r.motorAxis = u.ReadPodAt<uint8_t>(base + 3);
    {
        const uint64_t _idx = u.ReadPodAt<uint64_t>(base + 8);
        auto _obj = u.FollowObjectPtr(_idx);
        if (_obj) r.motor = std::static_pointer_cast<hkpConstraintMotor>(_obj);
    }
    r.targetAngle = u.ReadPodAt<float>(base + 16);
    return r;
}

std::shared_ptr<HkObject> Deser_hkpConstraintData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpConstraintData>();
    const size_t base = item.absoluteDataOffset;

    r->userData = u.ReadPodAt<uint64_t>(base + 24);

    return r;
}

std::shared_ptr<HkObject> Deser_hkpLimitedForceConstraintMotor(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpLimitedForceConstraintMotor>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int8_t>(base + 20);
    r->minForce = u.ReadPodAt<float>(base + 24);
    r->maxForce = u.ReadPodAt<float>(base + 28);

    return r;
}

static hkpLimitedHingeConstraintDataAtoms Deser_Inline_hkpLimitedHingeConstraintDataAtoms(TagFileUnpacker& u, size_t base)
{
    hkpLimitedHingeConstraintDataAtoms r{};
    r.transforms = u.ReadPodAt<hkpSetLocalTransformsConstraintAtom>(base + 0);
    r.setupStabilization = u.ReadPodAt<hkpSetupStabilizationAtom>(base + 144);
    r.angMotor = Deser_Inline_hkpAngMotorConstraintAtom(u, base + 160);
    r.angFriction = u.ReadPodAt<hkpAngFrictionConstraintAtom>(base + 192);
    r.angLimit = u.ReadPodAt<hkpAngLimitConstraintAtom>(base + 208);
    r._2dAng = u.ReadPodAt<hkp2dAngConstraintAtom>(base + 240);
    r.ballSocket = u.ReadPodAt<hkpBallSocketConstraintAtom>(base + 256);
    return r;
}

std::shared_ptr<HkObject> Deser_hkpLimitedHingeConstraintData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpLimitedHingeConstraintData>();
    const size_t base = item.absoluteDataOffset;

    r->userData = u.ReadPodAt<uint64_t>(base + 24);
    r->atoms = Deser_Inline_hkpLimitedHingeConstraintDataAtoms(u, base + 32);

    return r;
}

std::shared_ptr<HkObject> Deser_hkpPositionConstraintMotor(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpPositionConstraintMotor>();
    const size_t base = item.absoluteDataOffset;

    r->type = u.ReadPodAt<int8_t>(base + 20);
    r->minForce = u.ReadPodAt<float>(base + 24);
    r->maxForce = u.ReadPodAt<float>(base + 28);
    r->tau = u.ReadPodAt<float>(base + 32);
    r->damping = u.ReadPodAt<float>(base + 36);
    r->proportionalRecoveryVelocity = u.ReadPodAt<float>(base + 40);
    r->constantRecoveryVelocity = u.ReadPodAt<float>(base + 44);

    return r;
}

static hkpRagdollConstraintDataAtoms Deser_Inline_hkpRagdollConstraintDataAtoms(TagFileUnpacker& u, size_t base)
{
    hkpRagdollConstraintDataAtoms r{};
    r.transforms = u.ReadPodAt<hkpSetLocalTransformsConstraintAtom>(base + 0);
    r.setupStabilization = u.ReadPodAt<hkpSetupStabilizationAtom>(base + 144);
    r.ragdollMotors = u.ReadPodAt<hkpRagdollMotorConstraintAtom>(base + 160);
    r.angFriction = u.ReadPodAt<hkpAngFrictionConstraintAtom>(base + 256);
    r.twistLimit = u.ReadPodAt<hkpTwistLimitConstraintAtom>(base + 272);
    r.coneLimit = u.ReadPodAt<hkpConeLimitConstraintAtom>(base + 304);
    r.planesLimit = u.ReadPodAt<hkpConeLimitConstraintAtom>(base + 336);
    r.ballSocket = u.ReadPodAt<hkpBallSocketConstraintAtom>(base + 368);
    return r;
}

std::shared_ptr<HkObject> Deser_hkpRagdollConstraintData(TagFileUnpacker& u, const TagFileItem& item)
{
    auto r = std::make_shared<hkpRagdollConstraintData>();
    const size_t base = item.absoluteDataOffset;

    r->userData = u.ReadPodAt<uint64_t>(base + 24);
    r->atoms = Deser_Inline_hkpRagdollConstraintDataAtoms(u, base + 32);

    return r;
}

void RegisterHkpDispatch(TagFileUnpacker& u)
{
    u.Register("hkpConstraintMotor", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpConstraintMotor(u_, i_);
    });
    u.Register("hkpConstraintData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpConstraintData(u_, i_);
    });
    u.Register("hkpLimitedForceConstraintMotor", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpLimitedForceConstraintMotor(u_, i_);
    });
    u.Register("hkpLimitedHingeConstraintData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpLimitedHingeConstraintData(u_, i_);
    });
    u.Register("hkpPositionConstraintMotor", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpPositionConstraintMotor(u_, i_);
    });
    u.Register("hkpRagdollConstraintData", [](TagFileUnpacker& u_, const TagFileItem& i_) -> std::shared_ptr<HkObject>
    {
        return Deser_hkpRagdollConstraintData(u_, i_);
    });
}

}  // namespace Firelink::Havok::EldenRing